-- EmoteControl - Common Pack
-- Universal triggers that work for all classes and races

EmoteControl = EmoteControl or {}
local addon = EmoteControl

local pack = {
  name = "Common",
  version = "0.8.0",
  triggers = {
    -- ========================================
    -- Death & Resurrection
    -- ========================================
    {
      id = "player_died",
      event = "PLAYER_DEAD",
      cooldown = 5,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "has fallen in <zone>.",
        "lies defeated in <subzone>.",
        "collapses, lifeless.",
        "has been slain in <zone>!",
        "meets an untimely demise.",
        "takes a dirt nap in <zone>.",
        "fell to <target>.",
        "wasn't prepared for <target> in <zone>.",
        "adds another death to the count.",
        "will be back... eventually.",
        "Tactical reset triggered.",
        "I was just inspecting the floor textures. High quality.",
        "Lag! It was definitely lag.",
        "My health bar just did a disappearing act.",
        "Releasing spirit in <zone>... and my dignity.",
        "Goes down. Spectator mode engaged.",
        "Falls with dramatic flair.",
        "Hits the ground. Hard.",
        "Enters the respawn queue.",
        "Makes friends with the dirt.",
        "Gets deleted from existence.",
        "Becomes permanently horizontal.",
        "Embraces the void.",
        "Takes an unscheduled break.",
        "Gets sent to the shadow realm of <instanceName>.",
        "Checks out early from this party.",
        "Becomes a ghost. How thrilling.",
        "Phases out of reality.",
        "Loses the game. Literally.",
        "Encounters an unbeatable foe.",
        "Gets out-dps'd by a fire elemental.",
        "Falls over with a thud.",
        "Becomes one with the ground.",
        "Takes the long sleep.",
        "Respawn timer: go!",
        "Returns to dust.",
        "Gets owned. Spectacularly.",
        "Falls down. Way down.",
        "Meets the boss's arena in <instanceName>.",
        "Becomes corpse decor.",
        "Gets pushed off a cliff (metaphorically).",
        "Joins the hall of the permanently defeated.",
        "Takes a nap that lasts forever.",
      },
    },
    {
      id = "player_resurrected",
      event = "PLAYER_ALIVE",
      cooldown = 5,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "returns from the grave in <zone>!",
        "is back in action in <subzone>!",
        "has been resurrected at <time>.",
        "shakes off death's grip.",
        "rises once more!",
        "dusts themself off and gets back up.",
        "cheated death... this time.",
        "respawns with renewed determination.",
        "is alive and ready for round two!",
        "returns, a bit worse for wear.",
        "I live! ...unfortunately.",
        "The walk of shame is over.",
        "Back from the twisting nether.",
        "Mana check? Just kidding, let's pull in <instanceName>.",
        "Who has a repair bot in <instanceName>?",
        "Reappears from the ether.",
        "Claws their way back to life.",
        "Emerges from the void.",
        "Awakens with renewed purpose.",
        "Gets a second chance. Or fifth.",
        "Materializes back into existence.",
        "Crawls out of the grave.",
        "Gasps for air dramatically.",
        "Becomes un-dead. Again.",
        "Returns with vengeance in mind.",
        "Stretches and cracks neck loudly.",
        "Brushes off death like it's nothing.",
        "Shimmers back into reality.",
        "Rejoins the land of the living.",
        "Stands up despite every bone aching.",
        "Returns with a vengeance.",
        "Gets a redo button. How nice.",
        "Phases back in smoothly.",
        "Rises from the ashes.",
        "Comes back angrier than before.",
        "Resurrects with dramatic music.",
        "Shakes it off and keeps going.",
        "Returns from beyond, confused.",
        "Bounces back immediately.",
        "Is miraculously alive again.",
        "Gains another life. Cat approved.",
        "Respawns with determination.",
        "Comes back for round three.",
        "Returns like nothing happened in <zone>.",
      },
    },
    {
      id = "player_resurrected_by_other",
      event = "RESURRECT_REQUEST",
      cooldown = 5,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Thank you for the rez in <zone>!",
        "Appreciate the save!",
        "Back in the fight in <instanceName>, thanks!",
        "You're a lifesaver at <time>!",
        "Ready to go again, thanks!",
        "Much obliged for the resurrection!",
        "That was close, thanks for pulling me back!",
        "You are a saint among murder-hobos.",
        "Accepting. Don't let me die again.",
        "Is this a combat res? I feel special.",
        "Rise, champion! (That's me).",
        "I owe you a mana bun.",
        "Clicking 'Accept' with enthusiasm.",
        "Saving me the run back? Marry me.",
        "I promise to dodge the fire this time in <instanceName>.",
        "Blessed are the healers who res.",
        "You're my hero. Literally.",
        "Thanks for not letting me stay dead.",
        "Accepting this gift with gratitude.",
        "May your heals be hot and your crits bigger.",
        "You just saved a wipe. You're welcome.",
        "Rez received. All is forgiven.",
        "I accept my second chance.",
        "The circle of life continues!",
        "You make me want to dodge more.",
        "Thanks for the vote of confidence.",
        "Standing up now in <zone>. Ready to fail again.",
        "Appreciating your healing efforts.",
        "Clicking yes before you change your mind.",
        "Best healer award goes to you.",
        "I'll try not to disappoint. Probably.",
        "Life tap? No. You tapped life for me.",
        "You're getting a 5-star review.",
        "Accepting resurrection with open arms.",
        "This time I'll pay attention. Maybe.",
        "Thanks for believing in me.",
        "You're the glue holding this group together.",
        "Rez me once, shame on you. You rezed me thrice.",
        "Off the ground now. Don't judge my skill.",
        "You're like a second chance machine.",
        "Gratefully accepting this resurrection.",
      },
    },
    
    -- ========================================
    -- Combat Entry/Exit
    -- ========================================
    {
      id = "combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "readies for battle!",
        "enters combat stance.",
        "draws their weapon.",
        "prepares to engage <target>!",
        "charges into the fray!",
        "Roll for initiative!",
        "Wait, my food buff!",
        "Pulling <target> in <zone>!",
        "Time to pad the meters.",
        "Less talking, more slaying.",
        "If we wipe, I'm blaming the hunter.",
        "Target acquired: <target>.",
        "Everyone remember your rotation?",
        "I have aggro? Why do I have aggro?",
        "Leeeeroooy!",
        "Weapons drawn. Game on.",
        "Time to hurt <target>.",
        "Engaging threat management mode.",
        "Preparing for inevitable chaos.",
        "Battle stations: ACTIVATED.",
        "Let's get this over with.",
        "Combat initiated. Panic override: disabled.",
        "Standing up to face the music.",
        "Time to make some noise.",
        "Entering the pain zone.",
        "Adrenaline surging.",
        "I'm ready. Mostly ready. Sort of ready.",
        "Drawing steel and courage.",
        "Focusing on the target.",
        "Channeling battle spirit.",
        "Game face: on for <instanceName>.",
        "Switching from pacifist to chaos.",
        "Unleashing the beast within.",
        "Entering kill zone.",
        "Locked and loaded.",
        "Ready to bring the pain.",
        "Engaging combat mode.",
        "Preparing for the fight of my life.",
        "Tensing up for impact.",
        "Bloodlust activated.",
        "Here we go again.",
        "Time for some justice.",
        "Preparing for the moment of truth.",
      },
    },
    {
      id = "combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "sheathes their weapon.",
        "relaxes their stance.",
        "wipes the blood from their blade.",
        "catches their breath.",
        "stands victorious.",
        "And stay dead!",
        "Loot? Did it drop loot in <instanceName>?",
        "Checking DPS meters in <instanceName>... acceptable.",
        "Everyone drink up.",
        "Is it safe? It looks safe.",
        "We survived <instanceName>! Surprisingly.",
        "Nothing to see here, just corpses.",
        "Combat log reset.",
        "Okay, who pulled extra in <instanceName>?",
        "Break time?",
        "Putting weapons away. Peace restored.",
        "The battle is finished.",
        "Letting the adrenaline fade.",
        "Everything went better than expected.",
        "Nobody important died. Probably.",
        "Combat concluded. Damage check incoming.",
        "Breathing heavily. Exhausted.",
        "Wounds treated. Slightly.",
        "That went swimmingly. Define swimmingly.",
        "Cleaning up the mess.",
        "Another battle, another victory.",
        "Settling down from the chaos.",
        "The dust settles in <zone>. And the looting begins.",
        "One moment of peace achieved.",
        "Exiting threat zone.",
        "Weapons secured. Safety mode: engaged.",
        "All's well that ends in loot.",
        "Sheathing and feeling victorious.",
        "That wasn't so bad.",
        "Stretching sore muscles.",
        "The quiet after the storm.",
        "Safe again. For now.",
        "Enjoying the silence.",
        "Taking a well-deserved break.",
        "Checking for injuries. Minor bruises.",
        "Standing tall in victory.",
        "Time to heal up and recover.",
      },
    },

    -- ========================================
    -- Level Up
    -- ========================================
    {
      id = "level_up",
      event = "PLAYER_LEVEL_UP",
      cooldown = 10,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Level <level>! Growing stronger in <zone>!",
        "DING! Level <level> achieved at <time>!",
        "Another level, another challenge! Level <level>!",
        "Hit level <level> in <subzone>! Onward and upward!",
        "Level <level> unlocked in <zone>! Progress!",
        "Reached level <level>! The journey continues!",
        "Level <level> complete! What's next?",
        "Ding! Grats to me.",
        "Power overwhelming!",
        "One step closer to level cap in <zone>.",
        "New talent point unlocked (that I will copy from a guide).",
        "Shiny lights and a loud noise!",
        "I feel taller. Do I look taller?",
        "Experience bar go brrr.",
        "Unstoppable force growing stronger.",
        "Another notch on the experience belt.",
        "Level <level> acquired! Celebration time!",
        "Getting stronger with each level.",
        "That was fast. Is time broken?",
        "Leveling up at the speed of slightly faster.",
        "New number go brrr.",
        "The grind continues toward cap.",
        "I am become powerful, destroyer of mobs.",
        "Level up animation is beautiful.",
        "Stat boost unlocked!",
        "Feeling more powerful already.",
        "Another day, another level.",
        "Progression achieved!",
        "The journey to max level continues.",
        "Getting that shiny new achievement.",
        "Ability improvement incoming!",
        "More health. More damage. More problems.",
        "Leveling up is my favorite hobby.",
        "Experience converted to power.",
        "The experience fairy visited.",
        "Another milestone reached.",
        "Growth is beautiful. Especially exponential growth.",
        "Level up sensation is real.",
        "Time to celebrate with more grinding.",
        "Getting close to elite status.",
        "Each level makes me cooler.",
        "The climb to greatness continues.",
        "Feeling the rush of new power.",
      },
    },

    -- ========================================
    -- Achievement Earned
    -- ========================================
    {
      id = "achievement_earned",
      event = "ACHIEVEMENT_EARNED",
      cooldown = 10,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Achievement unlocked: <achievement>!",
        "Just earned <achievement>!",
        "Completed <achievement>!",
        "Check it out: <achievement>!",
        "<achievement> - another one for the collection!",
        "Finally got <achievement>!",
        "Validation acquired.",
        "Look at me, achieving things.",
        "Another arbitrary milestone met.",
        "Does this come with a mount?",
        "Screenshotting this for posterity.",
        "I'd like to thank the academy.",
        "Points! Useless, glorious points.",
        "Completionist mode: Active.",
        "Worth the grind? Debatable.",
        "Achievement <achievement> is now in my trophy case.",
        "One more achievement closer to perfection.",
        "Earning achievements one at a time.",
        "This achievement is a big deal. Probably.",
        "Adding to my resume of virtual accomplishments.",
        "That was a long farm. Worth it.",
        "<achievement> acquired! Goals are within reach.",
        "The achievement gods smile upon me.",
        "This is going on the mantle.",
        "Bragging rights unlocked.",
        "Another reason to feel accomplished.",
        "Achievement hunting never stops.",
        "Got the thing! It's a thing!",
        "Unlocking the path to greatness.",
        "That achievement felt good.",
        "Collection updated successfully.",
        "Feeling the sweet taste of achievement.",
        "Mount or cosmetic? Let's hope!",
        "Achievement momentum: building.",
        "The grind paid off in gold achievements.",
        "That felt rewarding somehow.",
        "Checking the achievement off the list.",
        "Fame and glory incoming!",
        "More points for my metaphorical portfolio.",
        "The achievement ladder ascends.",
        "Updating LinkedIn with this.",
        "Legend status: enhancing.",
      },
    },

    -- ========================================
    -- Loot (Epic+ items)
    -- ========================================
    {
      id = "loot_epic",
      event = "CHAT_MSG_LOOT",
      cooldown = 30,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Nice! Just looted <item>!",
        "Epic drop: <item>!",
        "Score! Got <item>!",
        "RNG blessed me with <item>!",
        "Finally! <item> is mine!",
        "Look at this beauty: <item>!",
        "Purple! My favorite color.",
        "Is it an upgrade? I don't care, it's purple.",
        "Mine? Is it mine?",
        "Finally, a drop.",
        "Linking in chat in 3, 2, 1...",
        "RNGesus smiles upon us.",
        "Into the bags you go.",
        "Vendor trash? No, this is treasure.",
        "My gear score just went up.",
        "Shiny new loot acquired!",
        "That's going straight in my stash.",
        "Another epic to add to the collection.",
        "Luck factor: Maximum.",
        "This item is mine. Touch it and you lose fingers.",
        "Rolling need on this gorgeous piece of equipment.",
        "The RNG gods are feeling generous.",
        "Looting: it's my favorite activity.",
        "That glows so pretty.",
        "New item. New possibilities.",
        "Purple goodness acquired.",
        "Can't help but smile at this drop.",
        "This is why we raid.",
        "Quality loot. Excellence achieved.",
        "Adding another trophy to the vault.",
        "That's a definite keeper.",
        "My collection grows stronger.",
        "Is this account even real?",
        "Lucky drops incoming.",
        "This is what epic looks like.",
        "My mother would be proud. Maybe.",
        "The loot god has spoken!",
        "Another upgrade for the arsenal.",
        "Holding this like it's a newborn.",
        "This brings a tear to my eye.",
      },
    },

    -- ========================================
    -- Social Interactions
    -- ========================================
    {
      id = "party_invite_accepted",
      event = "GROUP_JOINED",
      cooldown = 60,
      category = "flavor",
      channel = "PARTY",
      messages = {
        "Ready when you are. Group size: <group-size>.",
        "Let's do this!",
        "Joined up in <zone>! What's the plan?",
        "Here and ready to go!",
        "Party time in <instanceName>!",
        "Reporting for duty!",
        "The cavalry has arrived.",
        "I was told there would be loot.",
        "Who summoned the protagonist?",
        "Ready to carry... or be carried.",
        "Greetings, fellow adventurers of <zone>.",
        "Let's make this quick.",
        "I hope you all know tactics.",
        "Please tell me we have a tank.",
        "Party time!",
        "In the group now. Size: <group-size>.",
        "Joining forces with you lovely people.",
        "Adventures await!",
        "Team assembled. Mission: possible.",
        "Ready to rumble with the squad.",
        "Your new party member has arrived.",
        "Syncing up with the team.",
        "Let's make this legendary.",
        "I'm in! Now what?",
        "Party assembled. Chaos incoming.",
        "Ready to show my worth.",
        "New best friends acquired.",
        "Rolling into action with you all.",
        "All aboard the adventure train!",
        "Let's be a team. A good team. Preferably.",
        "In the group! All systems go!",
        "Here comes the reinforcements.",
        "Ready to pull my weight.",
        "Standing with my new friends.",
        "Party status: solid.",
        "Weapons ready. Spells loaded. Let's roll.",
        "Joining the ranks. Literally.",
        "Teammates acquired. Success rate: TBD.",
        "In the fight. For the glory.",
        "Ready to achieve things together.",
        "Team completed. Destiny awaits.",
      },
    },
    {
      id = "party_left",
      event = "GROUP_LEFT",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "parts ways with the group in <zone>.",
        "heads off solo in <subzone>.",
        "waves goodbye to the party.",
        "departs from the group.",
        "My people need me.",
        "Hearthstone out.",
        "It's not you, it's... actually, it might be you.",
        "Server restart? No, just leaving.",
        "I'm out of mana/patience.",
        "Thanks for the run in <instanceName>!",
        "Disbanding.",
        "Time to go solo again.",
        "Real life calls.",
        "Leaving <instanceName>.",
        "Later, nerds.",
        "Solo mode: re-enabled.",
        "Farewell, brave adventurers.",
        "Party ended. Moving on to solo adventures.",
        "Gotta fly. Catch you later!",
        "The adventure ends here. For now.",
        "Leaving the group to pursue other goals.",
        "Saying goodbyes and moving on.",
        "Time to explore new horizons alone.",
        "Group disbanded successfully.",
        "Taking my leave with a smile.",
        "Parting is such sweet sorrow.",
        "Adventures that were had: fond.",
        "Leaving to find new adventures.",
        "The party is no more. I'll survive.",
        "Off into the sunset solo.",
        "Friendship: temporary. Loot: permanent.",
        "Group exit complete.",
        "That was fun! Mostly.",
        "Leaving before the drama starts.",
        "See you around, friend!",
        "Party ended. Next adventure in <zone> awaits.",
        "Logging off with good memories.",
        "Thanks for the memories, team.",
        "On to bigger and better things.",
        "Waving as I leave the premises.",
        "Gone but not forgotten.",
      },
    },

    -- ========================================
    -- Zone Changes
    -- ========================================
    {
      id = "zone_changed",
      event = "ZONE_CHANGED_NEW_AREA",
      cooldown = 120,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "arrives in <zone> at <time>.",
        "enters <zone> (<subzone>) cautiously.",
        "steps into <zone> territory on <weekday>.",
        "makes their way to <zone> from <continent>.",
        "explores the lands of <zone> and <subzone>.",
        "Loading map data...",
        "New zone, who dis?",
        "Please let there be a flight path here.",
        "Scanning for rares.",
        "The music changed, must be a new area.",
        "Entering hostile territory.",
        "Why is the sky green here?",
        "Exploration XP incoming.",
        "I forgot to repair before leaving town.",
        "Does anyone have a map?",
        "Arriving at my new destination.",
        "Welcome to <zone>. Population: wandering mobs.",
        "The scenery sure is something.",
        "Setting foot in <zone> for the first time.",
        "New landscape. Same old problems.",
        "Where am I? <zone>. Cool.",
        "Travel successful. Navigation: questionable.",
        "Into the unknown of <zone>!",
        "Zone transition complete.",
        "Looking for points of interest in <zone>.",
        "The local flora looks strange.",
        "I hope I'm not lost.",
        "New place. New adventure potential.",
        "Zoning into <zone> with hopes and dreams.",
        "That's a new background.",
        "Expanding my horizons to <zone>.",
        "The air smells different here.",
        "Quest markers visible. Let's go.",
        "Moving to fresh territory.",
        "Zone detected. XP farming mode: engaged.",
        "Travel goals: achieved.",
        "The landscape of <zone> awaits exploration.",
        "New zone means new things to kill.",
        "Settling into <zone> for a bit.",
        "The journey continues in <zone>.",
        "Breathing in that <zone> air.",
      },
    },
    {
      id = "entered_dungeon",
      event = "PLAYER_ENTERING_WORLD",
      cooldown = 120,
      category = "flavor",
      channel = "INSTANCE",
      conditions = { inInstance = true },
      messages = {
        "Ready for this challenge: <instanceName>!",
        "Let's clear <instanceName>!",
        "Time to show them what we've got in <instanceName>!",
        "Ready to roll!",
        "Here we go: <instanceDifficulty>!",
        "Dungeon logic engaged in <instanceName>.",
        "Don't stand in the bad stuff.",
        "If the tank dies, it's the healer's fault.",
        "If the healer dies, it's the tank's fault.",
        "If the DPS dies, it's their own fault.",
        "Let's get this valor.",
        "Speed run?",
        "Skip the cutscenes, please.",
        "Boss 1: Prepare to be farmed.",
        "Remember to interrupt.",
        "Instance entered: <instanceName>.",
        "Welcome to the danger zone.",
        "Let's make this fast and painless.",
        "Preparing for boss mechanics.",
        "Everyone know their roles?",
        "Dungeon entrance secured.",
        "Ready to unleash chaos.",
        "Here's hoping nobody messes this up.",
        "Pull management: engaged.",
        "Let's demonstrate our skill.",
        "Dungeon protocol: activated.",
        "Entering the realm of challenges.",
        "Boss defeating time!",
        "Teamwork makes the dream work.",
        "Pointing at the first mob.",
        "This dungeon doesn't stand a chance.",
        "Let's show this place who's boss.",
        "Readying battle formations.",
        "The dungeon gods await our arrival.",
        "Clearing incoming!",
        "Every challenge is just practice.",
        "Let's make some noise.",
        "Announcing arrival to all mobs.",
        "It's on now.",
        "Dungeon run: commencing.",
        "Preparing for the inevitable wipes.",
      },
    },
    
    -- ========================================
    -- Combat Log Reactions
    -- ========================================
    {
      id = "combat_crit",
      event = "COMBAT_CRITICAL_HIT",
      cooldown = 15,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "lands a devastating critical hit on <target>!",
        "strikes with lethal precision!",
        "deals a crushing blow to <target>!",
        "finds the weak spot!",
        "hits with maximum force!",
        "unleashes a critical strike!",
        "Boom! <target> headshot!",
        "Critical mass achieved.",
        "That looked painful.",
        "Maximum effort!",
        "Big numbers make brain happy.",
        "Deleted.",
        "Did you see that number on <target>?!",
        "Crit happens.",
        "Melting face.",
        "Scoring the critical jackpot!",
        "That's a big one!",
        "Precision damage achieved!",
        "Bull's-eye!",
        "Weakness detected and exploited.",
        "Critical strike success!",
        "Massive damage incoming!",
        "Armor? What armor?",
        "One-shot potential unlocked.",
        "Vulnerabilities exposed.",
        "That enemy won't recover from that.",
        "The numbers speak for themselves.",
        "Big crit energy detected.",
        "Overkill status: activated.",
        "That was aggressive.",
        "Hitting where it counts.",
        "Critical hit. Fatality incoming.",
        "The ultimate strike lands true.",
        "Damage thresholds exceeded.",
        "Lucky roll achieved.",
        "Pain delivered with precision.",
        "Target vulnerable. Strike lands.",
        "Catastrophic damage deployed.",
        "That's going in the <instanceName> highlight reel.",
        "Critical success on all counts.",
      },
    },
    {
      id = "combat_dodged",
      event = "COMBAT_DODGED",
      cooldown = 20,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "watches <target> dodge their attack!",
        "misses as <target> sidesteps!",
        "swings wide as <target> dodges!",
        "is evaded!",
        "<target> can't touch this.",
        "<target> missed me.",
        "Too slow!",
        "Reflexes of a cat.",
        "Not today, Satan.",
        "I am the wind.",
        "Nice try.",
        "You swing like a goblin.",
        "Bob and weave!",
        "Was that an attack?",
        "Matrix mode engaged.",
        "That breeze felt nice.",
        "Almost got me!",
        "Close, but no cigar.",
        "My dodge game is strong.",
        "Evasion stat: maxed.",
        "Not this time!",
        "That blade found only air.",
        "Swift footwork saves the day.",
        "Unstoppable object meets immovable me.",
        "Ninja skills unlocked.",
        "Missed! Try again.",
        "The attack passes harmlessly.",
        "Reaction time: excellent.",
        "Danger avoided!",
        "That was a near miss.",
        "I have been speed.",
        "Tactical dodge successful.",
        "Getting out of the way is my hobby.",
        "Prediction game is on point.",
        "That attack was doomed from the start.",
        "My positioning is impeccable.",
        "Slipped right through their defense.",
        "Another miss for you, buddy.",
        "Untouchable status: confirmed.",
        "Dodging is an art form.",
        "That didn't come close.",
      },
    },
    {
      id = "combat_parried",
      event = "COMBAT_PARRIED",
      cooldown = 20,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "has their attack parried by <target>!",
        "is deflected by <target>'s weapon!",
        "strikes but <target> turns it aside!",
        "is blocked skillfully by <target>!",
        "Denied by <target>.",
        "Sword meet sword.",
        "Get that weak stuff out of here.",
        "Parry! Riposte!",
        "Your technique is lacking.",
        "Defense rating doing work.",
        "Clang!",
        "Nope.",
        "Try again.",
        "I can do this all day.",
        "My weapon is also a shield.",
        "Blocked and countered!",
        "Not this round!",
        "Steel meets steel!",
        "Defensive stance holds!",
        "Attack redirected!",
        "The parry was flawless.",
        "That blow didn't land!",
        "Pushed back by superior skill.",
        "The offense fails.",
        "Blocked like a boss.",
        "Skill advantage: mine.",
        "Another parry in the books.",
        "That didn't work.",
        "My defense is impenetrable.",
        "Strike turned aside.",
        "The blade was caught and deflected.",
        "Oof, denied!",
        "Parrying like a champion.",
        "That attack just bounced off.",
        "Weapon dexterity: off the charts.",
        "Not even close!",
        "The counter is ready.",
        "Technical mastery on display.",
        "That was laughably easy to block.",
        "Riposte incoming!",
      },
    },
    {
      id = "combat_interrupt",
      event = "COMBAT_INTERRUPTED",
      cooldown = 20,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Not casting that, <target>!",
        "Interrupted <target>!",
        "Shut down, <target>!",
        "Spell canceled!",
        "No you don't, <target>!",
        "Shhh. No casting.",
        "Silence, fool!",
        "Kick!",
        "Interrupted <target>! You're welcome.",
        "Stop that.",
        "No spell for you.",
        "Gag order enforced.",
        "C-C-Combo breaker!",
        "Not on my watch.",
        "Counterspell!",
        "Spell line broken!",
        "That casting is finished!",
        "Momentum halted!",
        "Your spell is going nowhere!",
        "Interruption successful!",
        "Shutting down your plans!",
        "Spellcasting denied!",
        "Not happening!",
        "That incantation stops here!",
        "Your magic is blocked!",
        "The casting fails spectacularly!",
        "Defensive measure engaged!",
        "Immediate countermeasure activated!",
        "Your turn is over!",
        "No more words for you!",
        "Silencing achieved!",
        "Chat bubble: disabled.",
        "That's not allowed!",
        "Interrupt success!",
        "Your plan B is also canceled.",
        "The spell never happens!",
        "Breaking concentration since day one!",
        "Mana wasted!",
        "Better luck next cast!",
        "Casting denied by skill!",
      },
    },

    -- ========================================
    -- Group Utility
    -- ========================================
    {
      id = "ready_check",
      event = "READY_CHECK",
      cooldown = 30,
      category = "flavor",
      channel = "RAID",
      messages = {
        "Ready. As ready as anyone can be in this chaos. Size: <group-size>.",
        "Ready check? Emotionally, no.",
        "Ready. My repairs are not. <instanceName> will know.",
        "Ready. I have snacks and poor decisions.",
        "Ready. I will still stand in something bad.",
        "Ready. Please pull before my food buff expires in <instanceName>.",
        "Ready. My cooldowns are ready. My brain is not.",
        "Ready. I have absolutely read the <instanceName> mechanics. Totally.",
        "Ready. If we wipe, it was lag.",
        "Ready. I have a plan. It is called improvising.",
        "Ready. I believe in us. Barely.",
        "Ready. This will be fine. Probably.",
        "Ready. Someone mark skull so I can pretend I know what is happening.",
        "Ready. I have my interrupt keybind. Somewhere.",
        "Ready. Confirmed. Certified. Questionable.",
        "Ready as I'll ever be.",
        "Standing by for action!",
        "I'm as ready as my preparation allows.",
        "Ready and waiting!",
        "All systems nominal.",
        "Ready. My bars are full and my expectations are low.",
        "Ready. The chaos awaits.",
        "Standing by. Panic? No. Slight concern? Yes.",
        "Ready. My monitor is on. My brain: debatable.",
        "Ready! I think. Pretty sure.",
        "Affirmative. I'm combat-capable.",
        "Ready. Only mostly nervous.",
        "Ready. I know what I'm doing. Maybe.",
        "Standing ready. Let's not die.",
        "Ready. I promise to try.",
        "Ready to commence operations!",
        "I'm prepared. Sort of.",
        "Ready! Enthusiasm: 60%.",
        "All set. Let's do this thing.",
        "Ready check accepted in <instanceName>!",
        "Confirmed ready for the upcoming challenge.",
        "Standing by and ready!",
        "I'm mentally prepared. Physically? We'll see.",
        "Ready. My confidence: fragile.",
        "Ready to make history. Or wipes.",
      },
    },
    {
      id = "summon_request",
      event = "CONFIRM_SUMMON",
      cooldown = 30,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Summon incoming to <instanceName>. Lazy travel engaged.",
        "Accepting the teleport of shame to <zone>.",
        "Being yoinked across the world in 3, 2, 1.",
        "Teleport taxi is here. No tip required. But appreciated.",
        "Click accept and pretend I walked here.",
        "I am being summoned because walking is a myth.",
        "Portal delivery service. I love modern convenience.",
        "On my way. Virtually.",
        "If this is to a wipe, I demand hazard pay.",
        "Summoned to <instanceName>. My legs thank you.",
        "The warlock Uber is here.",
        "I did not forget where the dungeon is. I chose this.",
        "Transporting my entire personality to your location.",
        "Dragging my soul across Azeroth.",
        "If this pulls me into lava, I am suing.",
        "Accepting the summon with grace.",
        "Fast travel unlocked!",
        "Being teleported with enthusiasm.",
        "Yes, I accept this free ride!",
        "Warlock taxi service to <zone>: appreciated.",
        "Clicking yes faster than light.",
        "Portal magic? Don't mind if I do.",
        "Accepting mystical transportation!",
        "This is the laziest I've been all day.",
        "Your summoning ritual is accepted!",
        "Beam me up, Scotty!",
        "Distance conquered through magic!",
        "Summon accepted. Arriving in <instanceName> in style.",
        "Taking the express route!",
        "Your summon is my command!",
        "Teleportation confirmed!",
        "Magic > walking always.",
        "Accepting interdimensional travel!",
        "The summon is received and accepted.",
        "No walking required. Excellent.",
        "Portal incoming. Stand back!",
        "Yes to free transportation!",
        "Summoning magic received successfully!",
        "Time to experience fast travel!",
        "The warlock has proven their usefulness.",
      },
    },

    -- ========================================
    -- Inventory / Repairs
    -- ========================================
    {
      id = "bag_full",
      event = "BAG_FULL",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      messages = {
        "My bags are full of treasures and poor choices from <zone>.",
        "Inventory full in <zone>. Time to vendor my dignity.",
        "Bags full in <subzone>. I am carrying the entire economy.",
        "I need bigger bags. And smaller hobbies.",
        "If it does not stack, it does not belong.",
        "My backpack is now a crime scene in <zone>.",
        "Too much loot. Not enough management skills.",
        "Bags full. Please hold while I delete something important.",
        "I can't pick that up. I am emotionally overloaded.",
        "Inventory full at <time>. Time to play Sorting Simulator.",
        "I looted one too many regrets.",
        "This is fine. I will just drop the gray items. Again.",
        "Bags full. I am one item away from becoming a hoarder.",
        "I swear I will clean my bags. Eventually.",
        "I have room in my heart, not in my bags.",
        "My bags have gained sentience and refused more items.",
        "Inventory management: failed.",
        "Space optimization: needed urgently.",
        "Bags at maximum capacity.",
        "Carrying more than a pack mule.",
        "Bag space: nonexistent.",
        "My bags are screaming.",
        "Inventory bursting at the seams.",
        "Too much stuff. Not enough space.",
        "Belongings exceed storage. Crisis time.",
        "Space allocation: critical error.",
        "My bags demand a raise.",
        "Organization: optional at this point.",
        "Packing efficiency: 0%.",
        "This is how hoarding starts.",
        "Bags full. I am now a mobile storage facility.",
        "I should probably vendor something.",
        "My bags are in pain.",
        "Maximum hoarding achieved.",
        "Bag real estate: fully developed.",
        "Room for improvement: literally needed.",
        "I can't fit my own body parts.",
        "The bags are waving a white flag.",
        "Inventory tetris: maximum difficulty.",
        "Bags shouting for mercy.",
      },
    },
    {
      id = "repair_needed",
      event = "REPAIR_NEEDED",
      cooldown = 300,
      category = "flavor",
      channel = "SAY",
      messages = {
        "My armor is held together by vibes.",
        "Durability low. My outfit is mostly hopes now.",
        "I need repairs before I become a naked ghost.",
        "Repair bill incoming. My wallet is afraid.",
        "My gear is crying. Literally.",
        "Everything is fine. Nothing is fine. Repair.",
        "My shield has more cracks than my sleep schedule.",
        "If I take one more hit, my boots will uninstall.",
        "Durability warning. I am one pull away from embarrassment.",
        "Please tell me someone brought a repair mount.",
        "My gear is turning into gray items in real time.",
        "Repair time. I am sponsored by duct tape.",
        "My armor has seen better expansions.",
        "This is not plate. This is paper mache.",
        "Repairing soon. Definitely. Probably.",
        "My gear is held together by prayers and prayers only.",
        "Armor integrity: compromised and desperate.",
        "I am one hit away from becoming paper.",
        "My equipment needs an emergency room visit.",
        "Durability check: catastrophic failure.",
        "My gear is filing for unemployment.",
        "The blacksmith has my credit card on file.",
        "This armor has seen better centuries. Way better.",
        "I am wearing what amounts to Swiss cheese.",
        "Repairs needed. Immortality would work too.",
        "My gear is literally falling off in pieces.",
        "Equipment condition: critical and worsening.",
        "The smithy is my second home. My expensive second home.",
        "My armor is dissolving into cosmic dust.",
        "I break things faster than I fix them.",
        "My gear is a constitutional crisis waiting to happen.",
        "Durability: entering the twilight zone.",
        "I need a blacksmith's on-call schedule.",
        "My armor is waving its white flag.",
        "Gear status: flirting with total collapse.",
        "This equipment requires last rites and a prayer.",
        "My armor is aging backwards. Badly.",
        "Repairs have become mandatory now.",
        "I am wearing a tragedy.",
        "Equipment cohesion: questionable at best.",
        "My gear had a committee meeting. Repairs demanded.",
      },
    },

    -- ========================================
    -- Boss / M+ Events
    -- ========================================
    {
      id = "boss_kill",
      event = "BOSS_KILL",
      cooldown = 60,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Boss down. Ego up.",
        "Another one bites the dust.",
        "That was clean. Do not check the logs.",
        "Loot time. Please be my item.",
        "Boss defeated. Mechanics ignored successfully.",
        "We did it. Mostly by accident.",
        "Victory achieved. Barely.",
        "That boss was free. Totally free.",
        "Good job team. Panic worked.",
        "Boss down. Someone clip that.",
        "That was smooth. Like gravel.",
        "Add this to my list of accomplishments.",
        "We are unstoppable. For the next 10 seconds.",
        "Boss down. Now we argue about loot.",
        "Next boss. Same chaos.",
        "Boss eliminated. Next victim awaits.",
        "That boss never stood a chance. Probably.",
        "Victory! I mean, we got lucky.",
        "Boss down. My DPS was definitely not terrible.",
        "That was totally planned.",
        "Defeated. With style. Questionable style.",
        "Boss goes poof. Permanently.",
        "Another scalp for the trophy wall.",
        "That was a proper beatdown.",
        "Boss falls. Loot table quivers in fear.",
        "We are the mightiest warriors. Sometimes.",
        "Boss down. My healer did most of it.",
        "That encounter was a joke. We laughed. Nervously.",
        "Boss defeated. Probably not on first try though.",
        "That was our best attempt yet. Third time counts.",
        "Glorious victory achieved.",
        "Boss down. Let the arguing begin.",
        "Another boss. Another day.",
        "That was our cleanest kill. From this expansion.",
        "Boss dies. We live. Math checks out.",
        "Victorious! Time to brag to guild.",
        "Boss down. My stance rotation was impeccable.",
        "That fight was epic. Mostly stressful.",
        "Another boss bites the grass.",
        "We won. Despite ourselves.",
      },
    },
    {
      id = "mythic_plus_start",
      event = "CHALLENGE_MODE_START",
      cooldown = 30,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Key in. Timer started.",
        "Mythic+ go time.",
        "Let's make the timer cry.",
        "Pull fast, die slow.",
        "Key started. Focus up.",
        "Time trial begins!",
        "M+ engaged. No pressure.",
        "Speed run time. Maybe.",
        "No deaths, please.",
        "Mythic+ underway.",
        "Timer's ticking. Let's move.",
        "Key up. Let's go.",
        "Challenge mode: activated.",
        "Run starts now!",
        "Let's beat this key.",
        "Key started. Panic mode optional.",
        "Timer engaged. Speedrunner mode activated.",
        "M+ time. Show me what you got.",
        "Challenge accepted. Barely.",
        "Key is live. My anxiety too.",
        "Let us conquer this mythic.",
        "Timer running. Calmness optional.",
        "M+ key inserted. Chaos commencing.",
        "Run beginning. Mistakes incoming.",
        "Key activated. May fortune be with us.",
        "Timer counting down our hopes.",
        "Mythic plus engagement protocol initiated.",
        "Speed is key. Literally.",
        "Let us make this look easy.",
        "Challenge started. My sanity at risk.",
        "Key in. Coordination required.",
        "This run will test us all.",
        "Timer running. Time is merciless.",
        "Speed run commencing. Organized chaos begins.",
        "Let's pretend we know what we are doing.",
        "Key engaged. Prayer required.",
        "M+ mode: fully activated.",
        "We got this. Probably.",
        "Timer up. Skill check begins.",
        "Mythic plus: go time for real.",
      },
    },
    {
      id = "mythic_plus_complete",
      event = "CHALLENGE_MODE_COMPLETED",
      cooldown = 30,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Key complete!",
        "We timed it. Nice.",
        "Mythic+ done. GG.",
        "Chest secured.",
        "Timer stopped. Loot awaits.",
        "We survived the key.",
        "Good run, team.",
        "Challenge complete.",
        "M+ finished. Breathe.",
        "Key over. Congrats.",
        "Loot time. Let's see the drops.",
        "Completion achieved.",
        "Mythic+ cleared.",
        "We did it. Score!",
        "Key complete. Solid work.",
        "Key finished. That was almost smooth.",
        "Mythic plus conquered.",
        "Chest awarded. We earned it.",
        "Completion confirmed. Anxiety subsiding.",
        "Key timed. Minimal panic.",
        "We made it. All of us alive.",
        "Challenge defeated. Timer is our friend.",
        "Loot incoming. Fingers crossed.",
        "M+ finished. No one died. Success!",
        "Key complete. My hands can relax now.",
        "Mythic+ run complete. Excellence achieved.",
        "We timed it without dying. Bonus.",
        "Key done. That was surprisingly smooth.",
        "Chest awaits. Our reward for chaos.",
        "Challenge mastered. Well, survived.",
        "Completion! Time check: we made it.",
        "Key cleared. Spirits high. Loot incoming.",
        "Mythic+ success. Round of applause.",
        "We did not wipe. That is a win.",
        "Key finished. My stress levels returning to normal.",
        "Challenge passed. Next difficulty up.",
        "M+ complete. Another notch in the belt.",
        "Timer beaten. Victory achieved.",
        "Key timed. Celebrate good times.",
        "Mythic plus triumph. Chest secured.",
        "Completion! Another key conquered.",
      },
    },
  },
}

addon:RegisterPack(pack)

