-- EmoteControl - Common Pack
-- Universal triggers that work for all classes and races

EmoteControl = EmoteControl or {}
local addon = EmoteControl

local pack = {
  name = "Common",
  version = "0.8.0",
  triggers = {
    -- ========================================
    -- Death & Resurrection
    -- ========================================
    {
      id = "player_died",
      event = "PLAYER_DEAD",
      cooldown = 5,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "has fallen.",
        "lies defeated on the ground.",
        "collapses, lifeless.",
        "has been slain!",
        "meets an untimely demise.",
        "takes a dirt nap.",
        "fell to <target>.",
        "wasn't prepared for that.",
        "adds another death to the count.",
        "will be back... eventually.",
        "Tactical reset triggered.",
        "I was just inspecting the floor textures. High quality.",
        "Lag! It was definitely lag.",
        "My health bar just did a disappearing act.",
        "Releasing spirit... and my dignity.",
      },
    },
    {
      id = "player_resurrected",
      event = "PLAYER_ALIVE",
      cooldown = 5,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "returns from the grave!",
        "is back in action!",
        "has been resurrected.",
        "shakes off death's grip.",
        "rises once more!",
        "dusts themself off and gets back up.",
        "cheated death... this time.",
        "respawns with renewed determination.",
        "is alive and ready for round two!",
        "returns, a bit worse for wear.",
        "I live! ...unfortunately.",
        "The walk of shame is over.",
        "Back from the twisting nether.",
        "Mana check? Just kidding, let's pull.",
        "Who has a repair bot?",
      },
    },
    {
      id = "player_resurrected_by_other",
      event = "RESURRECT_REQUEST",
      cooldown = 5,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Thank you for the rez!",
        "Appreciate the save!",
        "Back in the fight, thanks!",
        "You're a lifesaver!",
        "Ready to go again, thanks!",
        "Much obliged for the resurrection!",
        "That was close, thanks for pulling me back!",
        "You are a saint among murder-hobos.",
        "Accepting. Don't let me die again.",
        "Is this a combat res? I feel special.",
        "Rise, champion! (That's me).",
        "I owe you a mana bun.",
        "Clicking 'Accept' with enthusiasm.",
        "Saving me the run back? Marry me.",
        "I promise to dodge the fire this time.",
      },
    },
    
    -- ========================================
    -- Combat Entry/Exit
    -- ========================================
    {
      id = "combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "readies for battle!",
        "enters combat stance.",
        "draws their weapon.",
        "prepares to engage!",
        "charges into the fray!",
        "Roll for initiative!",
        "Wait, my food buff!",
        "Pulling! (I hope the tank is ready).",
        "Time to pad the meters.",
        "Less talking, more slaying.",
        "If we wipe, I'm blaming the hunter.",
        "Target acquired. Engaging.",
        "Everyone remember your rotation?",
        "I have aggro? Why do I have aggro?",
        "Leeeeroooy!",
      },
    },
    {
      id = "combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "sheathes their weapon.",
        "relaxes their stance.",
        "wipes the blood from their blade.",
        "catches their breath.",
        "stands victorious.",
        "And stay dead!",
        "Loot? Did it drop loot?",
        "Checking DPS meters... acceptable.",
        "Everyone drink up.",
        "Is it safe? It looks safe.",
        "We survived! Surprisingly.",
        "Nothing to see here, just corpses.",
        "Combat log reset.",
        "Okay, who pulled extra?",
        "Break time?",
      },
    },

    -- ========================================
    -- Level Up
    -- ========================================
    {
      id = "level_up",
      event = "PLAYER_LEVEL_UP",
      cooldown = 10,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Level <level>! Growing stronger!",
        "DING! Level <level> achieved!",
        "Another level, another challenge! Level <level>!",
        "Hit level <level>! Onward and upward!",
        "Level <level> unlocked! Progress!",
        "Reached level <level>! The journey continues!",
        "Level <level> complete! What's next?",
        "Ding! Grats to me.",
        "Power overwhelming!",
        "One step closer to level cap.",
        "New talent point unlocked (that I will copy from a guide).",
        "Shiny lights and a loud noise!",
        "I feel taller. Do I look taller?",
        "Experience bar go brrr.",
        "Unstoppable force growing stronger.",
      },
    },

    -- ========================================
    -- Achievement Earned
    -- ========================================
    {
      id = "achievement_earned",
      event = "ACHIEVEMENT_EARNED",
      cooldown = 10,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Achievement unlocked: <achievement>!",
        "Just earned <achievement>!",
        "Completed <achievement>!",
        "Check it out: <achievement>!",
        "<achievement> - another one for the collection!",
        "Finally got <achievement>!",
        "Validation acquired.",
        "Look at me, achieving things.",
        "Another arbitrary milestone met.",
        "Does this come with a mount?",
        "Screenshotting this for posterity.",
        "I'd like to thank the academy.",
        "Points! Useless, glorious points.",
        "Completionist mode: Active.",
        "Worth the grind? Debatable.",
      },
    },

    -- ========================================
    -- Loot (Epic+ items)
    -- ========================================
    {
      id = "loot_epic",
      event = "CHAT_MSG_LOOT",
      cooldown = 30,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Nice! Just looted <item>!",
        "Epic drop: <item>!",
        "Score! Got <item>!",
        "RNG blessed me with <item>!",
        "Finally! <item> is mine!",
        "Look at this beauty: <item>!",
        "Purple! My favorite color.",
        "Is it an upgrade? I don't care, it's purple.",
        "Mine? Is it mine?",
        "Finally, a drop.",
        "Linking in chat in 3, 2, 1...",
        "RNGesus smiles upon us.",
        "Into the bags you go.",
        "Vendor trash? No, this is treasure.",
        "My gear score just went up.",
      },
    },

    -- ========================================
    -- Social Interactions
    -- ========================================
    {
      id = "party_invite_accepted",
      event = "GROUP_JOINED",
      cooldown = 60,
      category = "flavor",
      channel = "PARTY",
      messages = {
        "Ready when you are!",
        "Let's do this!",
        "Joined up! What's the plan?",
        "Here and ready to go!",
        "Party time!",
        "Reporting for duty!",
        "The cavalry has arrived.",
        "I was told there would be loot.",
        "Who summoned the protagonist?",
        "Ready to carry... or be carried.",
        "Greetings, fellow adventurers.",
        "Let's make this quick.",
        "I hope you all know tactics.",
        "Please tell me we have a tank.",
        "Party time!",
      },
    },
    {
      id = "party_left",
      event = "GROUP_LEFT",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "parts ways with the group.",
        "heads off solo.",
        "waves goodbye to the party.",
        "departs from the group.",
        "My people need me.",
        "Hearthstone out.",
        "It's not you, it's... actually, it might be you.",
        "Server restart? No, just leaving.",
        "I'm out of mana/patience.",
        "Thanks for the run!",
        "Disbanding.",
        "Time to go solo again.",
        "Real life calls.",
        "Leaving instance group.",
        "Later, nerds.",
      },
    },

    -- ========================================
    -- Zone Changes
    -- ========================================
    {
      id = "zone_changed",
      event = "ZONE_CHANGED_NEW_AREA",
      cooldown = 120,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "arrives in <zone>.",
        "enters <zone> cautiously.",
        "steps into <zone> territory.",
        "makes their way to <zone>.",
        "explores the lands of <zone>.",
        "Loading map data...",
        "New zone, who dis?",
        "Please let there be a flight path here.",
        "Scanning for rares.",
        "The music changed, must be a new area.",
        "Entering hostile territory.",
        "Why is the sky green here?",
        "Exploration XP incoming.",
        "I forgot to repair before leaving town.",
        "Does anyone have a map?",
      },
    },
    {
      id = "entered_dungeon",
      event = "PLAYER_ENTERING_WORLD",
      cooldown = 120,
      category = "flavor",
      channel = "INSTANCE",
      conditions = { inInstance = true },
      messages = {
        "Ready for this challenge!",
        "Let's clear this place!",
        "Time to show them what we've got!",
        "Ready to roll!",
        "Here we go!",
        "Dungeon logic engaged.",
        "Don't stand in the bad stuff.",
        "If the tank dies, it's the healer's fault.",
        "If the healer dies, it's the tank's fault.",
        "If the DPS dies, it's their own fault.",
        "Let's get this valor.",
        "Speed run?",
        "Skip the cutscenes, please.",
        "Boss 1: Prepare to be farmed.",
        "Remember to interrupt.",
      },
    },
    
    -- ========================================
    -- Combat Log Reactions
    -- ========================================
    {
      id = "combat_crit",
      event = "COMBAT_CRITICAL_HIT",
      cooldown = 15,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "lands a devastating critical hit!",
        "strikes with lethal precision!",
        "deals a crushing blow!",
        "finds the weak spot!",
        "hits with maximum force!",
        "unleashes a critical strike!",
        "Boom! Headshot!",
        "Critical mass achieved.",
        "That looked painful.",
        "Maximum effort!",
        "Big numbers make brain happy.",
        "Deleted.",
        "Did you see that number?!",
        "Crit happens.",
        "Melting face.",
      },
    },
    {
      id = "combat_dodged",
      event = "COMBAT_DODGED",
      cooldown = 20,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "watches their attack get dodged!",
        "misses as the enemy sidesteps!",
        "swings wide as the foe dodges!",
        "is evaded!",
        "Can't touch this.",
        "Missed me.",
        "Too slow!",
        "Reflexes of a cat.",
        "Not today, Satan.",
        "I am the wind.",
        "Nice try.",
        "You swing like a goblin.",
        "Bob and weave!",
        "Was that an attack?",
        "Matrix mode engaged.",
      },
    },
    {
      id = "combat_parried",
      event = "COMBAT_PARRIED",
      cooldown = 20,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "has their attack parried!",
        "is deflected by the enemy's weapon!",
        "strikes but is turned aside!",
        "is blocked skillfully!",
        "Denied.",
        "Sword meet sword.",
        "Get that weak stuff out of here.",
        "Parry! Riposte!",
        "Your technique is lacking.",
        "Defense rating doing work.",
        "Clang!",
        "Nope.",
        "Try again.",
        "I can do this all day.",
        "My weapon is also a shield.",
      },
    },
    {
      id = "combat_interrupt",
      event = "COMBAT_INTERRUPTED",
      cooldown = 20,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Not casting that!",
        "Interrupted!",
        "Shut down!",
        "Spell canceled!",
        "No you don't!",
        "Shhh. No casting.",
        "Silence, fool!",
        "Kick!",
        "Interrupted! You're welcome.",
        "Stop that.",
        "No spell for you.",
        "Gag order enforced.",
        "C-C-Combo breaker!",
        "Not on my watch.",
        "Counterspell!",
      },
    },

    -- ========================================
    -- Group Utility
    -- ========================================
    {
      id = "ready_check",
      event = "READY_CHECK",
      cooldown = 30,
      category = "flavor",
      channel = "RAID",
      messages = {
        "Ready. As ready as anyone can be in this chaos.",
        "Ready check? Emotionally, no.",
        "Ready. My repairs are not.",
        "Ready. I have snacks and poor decisions.",
        "Ready. I will still stand in something bad.",
        "Ready. Please pull before my food buff expires.",
        "Ready. My cooldowns are ready. My brain is not.",
        "Ready. I have absolutely read the mechanics. Totally.",
        "Ready. If we wipe, it was lag.",
        "Ready. I have a plan. It is called improvising.",
        "Ready. I believe in us. Barely.",
        "Ready. This will be fine. Probably.",
        "Ready. Someone mark skull so I can pretend I know what is happening.",
        "Ready. I have my interrupt keybind. Somewhere.",
        "Ready. Confirmed. Certified. Questionable.",
      },
    },
    {
      id = "summon_request",
      event = "CONFIRM_SUMMON",
      cooldown = 30,
      category = "flavor",
      channel = "SAY",
      messages = {
        "Summon incoming. Lazy travel engaged.",
        "Accepting the teleport of shame.",
        "Being yoinked across the world in 3, 2, 1.",
        "Teleport taxi is here. No tip required. But appreciated.",
        "Click accept and pretend I walked here.",
        "I am being summoned because walking is a myth.",
        "Portal delivery service. I love modern convenience.",
        "On my way. Virtually.",
        "If this is to a wipe, I demand hazard pay.",
        "Summoned. My legs thank you.",
        "The warlock Uber is here.",
        "I did not forget where the dungeon is. I chose this.",
        "Transporting my entire personality to your location.",
        "Dragging my soul across Azeroth.",
        "If this pulls me into lava, I am suing.",
      },
    },

    -- ========================================
    -- Inventory / Repairs
    -- ========================================
    {
      id = "bag_full",
      event = "BAG_FULL",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      messages = {
        "My bags are full of treasures and poor choices.",
        "Inventory full. Time to vendor my dignity.",
        "Bags full. I am carrying the entire economy.",
        "I need bigger bags. And smaller hobbies.",
        "If it does not stack, it does not belong.",
        "My backpack is now a crime scene.",
        "Too much loot. Not enough management skills.",
        "Bags full. Please hold while I delete something important.",
        "I can't pick that up. I am emotionally overloaded.",
        "Inventory full. Time to play Sorting Simulator.",
        "I looted one too many regrets.",
        "This is fine. I will just drop the gray items. Again.",
        "Bags full. I am one item away from becoming a hoarder.",
        "I swear I will clean my bags. Eventually.",
        "I have room in my heart, not in my bags.",
      },
    },
    {
      id = "repair_needed",
      event = "REPAIR_NEEDED",
      cooldown = 300,
      category = "flavor",
      channel = "SAY",
      messages = {
        "My armor is held together by vibes.",
        "Durability low. My outfit is mostly hopes now.",
        "I need repairs before I become a naked ghost.",
        "Repair bill incoming. My wallet is afraid.",
        "My gear is crying. Literally.",
        "Everything is fine. Nothing is fine. Repair.",
        "My shield has more cracks than my sleep schedule.",
        "If I take one more hit, my boots will uninstall.",
        "Durability warning. I am one pull away from embarrassment.",
        "Please tell me someone brought a repair mount.",
        "My gear is turning into gray items in real time.",
        "Repair time. I am sponsored by duct tape.",
        "My armor has seen better expansions.",
        "This is not plate. This is paper mache.",
        "Repairing soon. Definitely. Probably.",
      },
    },

    -- ========================================
    -- Boss / M+ Events
    -- ========================================
    {
      id = "boss_kill",
      event = "BOSS_KILL",
      cooldown = 60,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Boss down. Ego up.",
        "Another one bites the dust.",
        "That was clean. Do not check the logs.",
        "Loot time. Please be my item.",
        "Boss defeated. Mechanics ignored successfully.",
        "We did it. Mostly by accident.",
        "Victory achieved. Barely.",
        "That boss was free. Totally free.",
        "Good job team. Panic worked.",
        "Boss down. Someone clip that.",
        "That was smooth. Like gravel.",
        "Add this to my list of accomplishments.",
        "We are unstoppable. For the next 10 seconds.",
        "Boss down. Now we argue about loot.",
        "Next boss. Same chaos.",
      },
    },
    {
      id = "mythic_plus_start",
      event = "CHALLENGE_MODE_START",
      cooldown = 30,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Key in. Timer started.",
        "Mythic+ go time.",
        "Let's make the timer cry.",
        "Pull fast, die slow.",
        "Key started. Focus up.",
        "Time trial begins!",
        "M+ engaged. No pressure.",
        "Speed run time. Maybe.",
        "No deaths, please.",
        "Mythic+ underway.",
        "Timer's ticking. Let's move.",
        "Key up. Let's go.",
        "Challenge mode: activated.",
        "Run starts now!",
        "Let's beat this key.",
      },
    },
    {
      id = "mythic_plus_complete",
      event = "CHALLENGE_MODE_COMPLETED",
      cooldown = 30,
      category = "flavor",
      channel = "INSTANCE",
      messages = {
        "Key complete!",
        "We timed it. Nice.",
        "Mythic+ done. GG.",
        "Chest secured.",
        "Timer stopped. Loot awaits.",
        "We survived the key.",
        "Good run, team.",
        "Challenge complete.",
        "M+ finished. Breathe.",
        "Key over. Congrats.",
        "Loot time. Let's see the drops.",
        "Completion achieved.",
        "Mythic+ cleared.",
        "We did it. Score!",
        "Key complete. Solid work.",
      },
    },
  },
}

addon:RegisterPack(pack)

