-- EmoteControl - Warlock Pack

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "warlock",
  name = "Warlock Pack",
  defaults = { class = "WARLOCK", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "warlock_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "channels fel energy, eyes glowing green.",
        "summons demonic power for battle.",
        "embraces the darkness within.",
        "prepares to unleash chaos.",
        "enters combat with sinister purpose.",
      },
    },
    {
      id = "warlock_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "smirks, fel magic subsiding.",
        "dismisses the chaotic energies.",
        "stands victorious, pact fulfilled.",
        "nods darkly, another soul tested.",
        "relaxes, the Legion approves.",
      },
    },

    -- Demons
    {
      id = "summon_demon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Summon" },
      messages = {
        "Summoning demon. Backup from the Twisting Nether.",
        "Demon deployed. Please do not pet it.",
        "Fel minion online.",
        "If Midnight wanted holy, wrong class.",
        "Demon summoning complete.",
        "Minion from the void engaged.",
      },
    },
    {
      id = "summon_infernal",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Summon Infernal" },
      messages = {
        "Summon Infernal. Meteor demon incoming.",
        "Infernal deployed from orbit.",
        "Calling down a burning problem.",
        "If Midnight wanted calm, too bad.",
        "Infernal online. Stand back.",
        "Demon meteor engaged.",
      },
    },
    {
      id = "summon_darkglare",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Summon Darkglare" },
      messages = {
        "Summon Darkglare. Eye demon online.",
        "Darkglare deployed. It sees all.",
        "Summoning the all-seeing horror.",
        "If Midnight brought eyes, I brought more eyes.",
        "Darkglare engaged.",
        "Vision demon activated.",
      },
    },

    -- Utility
    {
      id = "ritual_of_summoning",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Ritual of Summoning" },
      messages = {
        "Ritual of Summoning. Click the portal.",
        "Summoning online. Clicking is mandatory.",
        "Warlock Uber deployed.",
        "If you need transport, click here.",
        "Portal online. Please participate.",
        "Ritual engaged. Help required.",
      },
    },
    {
      id = "healthstone",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Create Healthstone" },
      messages = {
        "Create Healthstone. Emergency HP rock.",
        "Healthstone deployed. Use when dying.",
        "Magic healing candy created.",
        "If you need HP, I made a stone.",
        "Healthstone online. Take one.",
        "Life rock crafted.",
      },
    },
    {
      id = "soulstone",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "utility",
      conditions = { spellName = "Soulstone" },
      messages = {
        "Soulstone. Death insurance deployed.",
        "Soul backup created.",
        "If you die, the stone remembers.",
        "Resurrection insurance granted.",
        "Soulstone online. Die responsibly.",
        "Soul saved. Just in case.",
      },
    },

    -- Defensives
    {
      id = "unending_resolve",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Unending Resolve" },
      messages = {
        "Unending Resolve. Damage reduced dramatically.",
        "Resolve engaged. I am stubborn.",
        "If Midnight hits me, less effective.",
        "Defensive resolve online.",
        "Unending defense activated.",
        "Damage mitigation via determination.",
      },
    },
    {
      id = "dark_pact",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Dark Pact" },
      messages = {
        "Dark Pact. Shield via demon sacrifice.",
        "Pact deployed. Demon donates HP.",
        "If the demon has HP, I borrow it.",
        "Dark shield engaged.",
        "Pact shield online.",
        "Demon sacrifice shield activated.",
      },
    },

    -- Crowd Control
    {
      id = "fear",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Fear" },
      messages = {
        "Fear. Running away is now mandatory.",
        "Terrifying <target>.",
        "If Midnight wanted courage, denied.",
        "Fear deployed. Panic engaged.",
        "Terror protocol online.",
        "Scaring enemies professionally.",
      },
    },
    {
      id = "banish",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Banish" },
      messages = {
        "Banish. Removed from reality.",
        "Banishing to another plane.",
        "If Midnight wanted presence, denied.",
        "Banish protocol engaged.",
        "Reality removal activated.",
        "Dimensional timeout deployed.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Fel tactics adjusted.",
        "<spec> mode. The Legion approves.",
        "Switched to <spec>. Demon pact recalibrated.",
        "<spec> selected. Chaos strategy changed.",
        "New spec, same warlock: <spec>.",
      },
    },

    -- ====================================================================
    -- AFFLICTION WARLOCK SPEC-SPECIFIC TRIGGERS (SpecID: 265)
    -- ====================================================================
    {
      id = "warlock_unstable_affliction",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 265, spellName = "Unstable Affliction" },
      messages = {
        "Unstable Affliction. Ticking time bomb applied.",
        "Affliction deployed. Unstable and painful.",
        "DoT placed. Very unstable.",
        "If you dispel this, you explode.",
        "Unstable curse engaged.",
        "Volatile suffering online.",
        "Affliction with explosive clauses.",
      },
    },
    {
      id = "warlock_agony",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 265, spellName = "Agony" },
      messages = {
        "Agony. Suffering over time.",
        "Applying agony. Slowly.",
        "Pain DoT deployed.",
        "Suffering has begun.",
        "Agony stacking engaged.",
        "Incremental torment activated.",
        "Agony grows. Patiently.",
      },
    },
    {
      id = "warlock_corruption",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 265, spellName = "Corruption" },
      messages = {
        "Corruption. Rot applied.",
        "Corrupting <target>.",
        "DoT engaged. Corruption spreads.",
        "Rot protocol online.",
        "Corruption deployed.",
        "Decay initiated. Enjoy.",
        "Corruption spreads like gossip.",
      },
    },
    {
      id = "warlock_siphon_life",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 265, spellName = "Siphon Life" },
      messages = {
        "Siphon Life. Your HP is now mine.",
        "Life drain engaged. Slowly.",
        "Siphoning with patience.",
        "Your vitality: borrowed.",
        "Life theft protocol online.",
      },
    },
    {
      id = "warlock_malefic_rapture",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 265, spellName = "Malefic Rapture" },
      messages = {
        "Malefic Rapture. All DoTs explode.",
        "Rapture deployed. Pain detonated.",
        "Exploding all afflictions.",
        "Malefic burst engaged.",
        "DoT detonation online.",
        "Rapture protocol: suffering multiplied.",
        "All your pain, at once.",
      },
    },
    {
      id = "warlock_vile_taint",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 265, spellName = "Vile Taint" },
      messages = {
        "Vile Taint. Area corruption.",
        "Taint deployed. Everyone gets sick.",
        "Vile contamination online.",
        "If Midnight brought adds, they all get tainted.",
        "Area affliction engaged.",
      },
    },
    {
      id = "warlock_phantom_singularity",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 265, spellName = "Phantom Singularity" },
      messages = {
        "Phantom Singularity. Void collapse deployed.",
        "Singularity engaged. Black hole time.",
        "Void implosion online.",
        "Collapsing reality locally.",
        "Phantom vortex activated.",
        "If physics applies, not anymore.",
        "Gravity well of suffering.",
      },
    },
    {
      id = "warlock_soul_rot",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 265, spellName = "Soul Rot" },
      messages = {
        "Soul Rot. Decay spreads.",
        "Rotting souls engaged.",
        "Soul decay deployed.",
        "Spreading corruption.",
        "Rot protocol online.",
        "If you had a soul, it's rotting now.",
        "Soul putrefaction activated.",
      },
    },
    {
      id = "warlock_haunt",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 265, spellName = "Haunt" },
      messages = {
        "Haunt. You are now haunted.",
        "Haunting deployed. Enjoy the ghosts.",
        "Spectral torment engaged.",
        "If you wanted peace, I brought ghosts.",
        "Haunting protocol online.",
      },
    },

    -- ====================================================================
    -- DEMONOLOGY WARLOCK SPEC-SPECIFIC TRIGGERS (SpecID: 266)
    -- ====================================================================
    {
      id = "warlock_hand_of_guldan",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 266, spellName = "Hand of Gul'dan" },
      messages = {
        "Hand of Gul'dan. Meteor shower deployed.",
        "Gul'dan's hand engaged.",
        "Fel meteors incoming.",
        "Demon rock rain activated.",
        "Hand deployed. Duck.",
        "Gul'dan approves this violence.",
        "Meteor swarm of demons.",
      },
    },
    {
      id = "warlock_demonbolt",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 266, spellName = "Demonbolt" },
      messages = {
        "Demonbolt. Fel projectile deployed.",
        "Demon-powered bolt engaged.",
        "Fel energy launched.",
        "Demonbolt online.",
        "Demon magic projectile.",
        "Bolt charged with demonic fury.",
        "If fel was subtle, this is not.",
      },
    },
    {
      id = "warlock_shadow_bolt_demo",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 266, spellName = "Shadow Bolt" },
      messages = {
        "Shadow Bolt. Classic dark magic.",
        "Bolt of shadow deployed.",
        "Shadow projectile online.",
        "Dark magic, traditional recipe.",
        "Shadow bolt engaged.",
      },
    },
    {
      id = "warlock_implosion",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 266, spellName = "Implosion" },
      messages = {
        "Implosion. Sacrificing imps for AoE.",
        "Imps explode. As intended.",
        "Demon detonation engaged.",
        "Implosion protocol online.",
        "Imp sacrifice activated.",
        "If my imps complained, I did not listen.",
        "Explosive demon retirement plan.",
      },
    },
    {
      id = "warlock_bilescourge_bombers",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 266, spellName = "Bilescourge Bombers" },
      messages = {
        "Bilescourge Bombers. Demon air support.",
        "Bombers deployed. From the Twisting Nether.",
        "Aerial demon bombardment.",
        "If Midnight flies, bombers object.",
        "Bile bombardment online.",
      },
    },
    {
      id = "warlock_nether_portal",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 266, spellName = "Nether Portal" },
      messages = {
        "Nether Portal. Demon highway opened.",
        "Portal engaged. Demons incoming.",
        "Opening gateway to Twisting Nether.",
        "Portal online. Army deploying.",
        "Nether gateway activated.",
        "If you wanted alone time, I brought a portal.",
        "Demon immigration: approved.",
      },
    },
    {
      id = "warlock_summon_demonic_tyrant",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 266, spellName = "Summon Demonic Tyrant" },
      messages = {
        "Summon Demonic Tyrant. Big demon time.",
        "Tyrant deployed. Bow before it.",
        "Big boss demon summoned.",
        "Demonic overlord online.",
        "Tyrant engaged. Fear appropriately.",
        "If Midnight brought minions, I brought a manager.",
        "The big demon has arrived. Please panic.",
      },
    },
    {
      id = "warlock_call_dreadstalkers",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 266, spellName = "Call Dreadstalkers" },
      messages = {
        "Call Dreadstalkers. Dog demons deployed.",
        "Dreadstalkers engaged.",
        "Demon hounds summoned.",
        "Stalkers online. Attack mode.",
        "Dread dogs activated.",
        "Hell hounds on the hunt.",
        "If you wanted puppies, wrong summon.",
      },
    },
    {
      id = "warlock_guillotine",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 266, spellName = "Guillotine" },
      messages = {
        "Guillotine. Demon sacrifice for power.",
        "Sacrificing my felguard. For science.",
        "Guillotine engaged. Demon donation.",
        "If the demon had opinions, too late.",
        "Felguard sacrificed. Power gained.",
      },
    },

    -- ====================================================================
    -- DESTRUCTION WARLOCK SPEC-SPECIFIC TRIGGERS (SpecID: 267)
    -- ====================================================================
    {
      id = "warlock_chaos_bolt",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "cooldowns",
      conditions = { specID = 267, spellName = "Chaos Bolt" },
      messages = {
        "Chaos Bolt. Delivery for <target>.",
        "Sending a slow green problem.",
        "Critical strike pending.",
        "Chaos engaged. Incoming.",
        "Bolt of chaos deployed.",
        "Green death approaching.",
        "If you wanted predictable, wrong bolt.",
        "Chaos bolt: guaranteed crit edition.",
      },
    },
    {
      id = "warlock_incinerate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 267, spellName = "Incinerate" },
      messages = {
        "Incinerate. Burning with purpose.",
        "Incineration protocol online.",
        "Fire deployed. Destruction style.",
        "Incinerate engaged.",
        "Burning with fel efficiency.",
      },
    },
    {
      id = "warlock_immolate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 267, spellName = "Immolate" },
      messages = {
        "Immolate. You are now on fire.",
        "Immolation applied. Enjoy the flames.",
        "Setting <target> ablaze.",
        "Fire DoT deployed.",
        "Immolate online. Burns over time.",
      },
    },
    {
      id = "warlock_rain_of_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 267, spellName = "Rain of Fire" },
      messages = {
        "Rain of Fire. Fire from above.",
        "Raining fel flames.",
        "Fire rain deployed.",
        "Infernal weather engaged.",
        "Fel fire falling.",
        "If Midnight wanted dry, I brought rain. Fire rain.",
        "Weather forecast: burning.",
      },
    },
    {
      id = "warlock_conflagrate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 267, spellName = "Conflagrate" },
      messages = {
        "Conflagrate. Quick burn deployed.",
        "Conflagration engaged.",
        "Fast fire online.",
        "Burning with efficiency.",
        "Conflagrate activated.",
        "Instant immolation.",
      },
    },
    {
      id = "warlock_havoc",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 267, spellName = "Havoc" },
      messages = {
        "Havoc. Double the target, double the fun.",
        "Havoc engaged. Two problems.",
        "Casting on two targets. Efficiency.",
        "Havoc protocol online.",
        "If one target is good, two is better.",
      },
    },
    {
      id = "warlock_cataclysm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 267, spellName = "Cataclysm" },
      messages = {
        "Cataclysm. World-ending fire.",
        "Apocalyptic flames deployed.",
        "Cataclysm engaged. Duck.",
        "Destruction at scale.",
        "Fire apocalypse online.",
        "If Midnight wanted subtle, I brought cataclysm.",
        "End times, fire edition.",
      },
    },
    {
      id = "warlock_channel_demonfire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 267, spellName = "Channel Demonfire" },
      messages = {
        "Channel Demonfire. Demon fire barrage.",
        "Channeling flames of chaos.",
        "Demon fire online.",
        "Fire barrage engaged.",
        "Channeling destruction.",
        "Demon-powered flamethrower.",
      },
    },
    {
      id = "warlock_shadowburn",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 267, spellName = "Shadowburn" },
      messages = {
        "Shadowburn. Execute protocol.",
        "Burning shadows engaged.",
        "Shadow fire deployed.",
        "Finisher online.",
        "Shadowburn activated.",
        "Low HP detected. Shadowburn deployed.",
      },
    },
    {
      id = "warlock_dark_soul_instability",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 267, spellName = "Dark Soul: Instability" },
      messages = {
        "Dark Soul: Instability. Chaos maximized.",
        "Soul instability engaged. Power spike.",
        "Dark soul online. Destruction amplified.",
        "Instability activated. Crit incoming.",
        "If Midnight wanted stable, wrong cooldown.",
      },
    },
  },
})
