-- EmoteControl - Evoker Pack

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "evoker",
  name = "Evoker Pack",
  defaults = { class = "EVOKER", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "evoker_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "channels draconic power, essence awakening.",
        "enters combat, dragonflights united in purpose.",
        "prepares to weave time and magic.",
        "assumes battle stance, scales shimmering.",
        "readies breath and spell alike.",
      },
    },
    {
      id = "evoker_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "relaxes, draconic essence calming.",
        "stands tall, dragonkind victorious.",
        "nods with ancient wisdom.",
        "exhales, magic dissipating gracefully.",
        "returns to contemplation.",
      },
    },

    -- Mobility
    {
      id = "hover",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "movement",
      conditions = { spellName = "Hover" },
      messages = {
        "Hover. Dragon flight engaged.",
        "Hovering with draconic grace.",
        "If Midnight wanted me grounded, denied.",
        "Flight mode activated.",
        "Hovering above problems.",
        "Dragon hover online.",
        "Airborne. Stylishly.",
        "Hover protocol engaged.",
      },
    },
    {
      id = "deep_breath",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "movement",
      conditions = { spellName = "Deep Breath" },
      messages = {
        "Deep Breath. Strafing run deployed.",
        "Dragon breath from above.",
        "If Midnight wanted calm, I brought fire.",
        "Aerial assault engaged.",
        "Breath attack from the sky.",
        "Deep breath protocol activated.",
        "Strafing with dragon fire.",
        "Breath run complete.",
      },
    },

    -- Defensive
    {
      id = "obsidian_scales",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Obsidian Scales" },
      messages = {
        "Obsidian Scales. Dragon armor engaged.",
        "Scales hardened. Damage reduced.",
        "If Midnight hits me, obsidian says no.",
        "Dragon defense online.",
        "Obsidian protocol activated.",
        "Scales fortified.",
        "Dragon armor deployed.",
        "Obsidian shield engaged.",
      },
    },
    {
      id = "renewing_blaze",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "defensive",
      conditions = { spellName = "Renewing Blaze" },
      messages = {
        "Renewing Blaze. Fire heals now.",
        "Flames of renewal engaged.",
        "If HP was low, fire provides.",
        "Renewing fire online.",
        "Blaze protocol activated.",
        "Healing flames deployed.",
        "Fire renewal complete.",
        "Blaze healing engaged.",
      },
    },

    -- Offensive CDs
    {
      id = "dragonrage",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Dragonrage" },
      messages = {
        "Dragonrage. Ultimate dragon fury.",
        "Rage mode: draconic.",
        "If Midnight wanted calm, wrong cooldown.",
        "Dragon fury unleashed.",
        "Dragonrage protocol engaged.",
        "Ultimate rage online.",
        "Fury of dragons deployed.",
        "Dragonrage complete.",
      },
    },
    {
      id = "tip_the_scales",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Tip the Scales" },
      messages = {
        "Tip the Scales. Instant empowerment.",
        "Time manipulation engaged.",
        "If Midnight wanted casting time, denied.",
        "Scales tipped. Power instant.",
        "Empowerment protocol activated.",
        "Instant cast online.",
        "Scales balanced. Instantly.",
        "Time bending complete.",
      },
    },

    -- Utility
    {
      id = "quell",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Quell" },
      messages = {
        "Quell. Cast interrupted.",
        "Dragon interrupt deployed.",
        "If Midnight wanted to cast, quelled.",
        "Silence via dragon authority.",
        "Quell protocol engaged.",
        "Cast cancelled by dragon.",
        "Interrupt complete.",
        "Quelled into silence.",
      },
    },
    {
      id = "blessing_of_the_bronze",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Blessing of the Bronze" },
      messages = {
        "Blessing of the Bronze. Time gifts granted.",
        "Bronze blessing deployed.",
        "If Midnight wanted linear time, the Bronze disagrees.",
        "Temporal blessing online.",
        "Bronze protocol engaged.",
        "Time magic bestowed.",
        "Blessing of time activated.",
        "Bronze dragonflight approves.",
      },
    },
    {
      id = "rescue",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Rescue" },
      messages = {
        "Rescue. Pulling ally to safety.",
        "Dragon rescue deployed.",
        "If you are in fire, not anymore.",
        "Rescue protocol engaged.",
        "Ally relocated via dragon.",
        "Rescue complete.",
        "Pulled to safety.",
        "Dragon save activated.",
      },
    },

    -- Empower spells
    {
      id = "fire_breath",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Fire Breath" },
      messages = {
        "Fire Breath. Dragon fire deployed.",
        "Breathing fire. As dragons do.",
        "If Midnight wanted cold, wrong breath.",
        "Fire breath engaged.",
        "Draconic flames online.",
        "Breath weapon activated.",
        "Fire protocol deployed.",
        "Dragon fire complete.",
      },
    },
    {
      id = "eternity_surge",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Eternity Surge" },
      messages = {
        "Eternity Surge. Magic unleashed.",
        "Surging with eternal power.",
        "If Midnight wanted finite, denied.",
        "Eternity protocol engaged.",
        "Surge deployed.",
        "Eternal magic online.",
        "Surge complete.",
        "Eternity unleashed.",
      },
    },
    {
      id = "disintegrate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Disintegrate" },
      messages = {
        "Disintegrate. Unmaking reality.",
        "Disintegration beam engaged.",
        "If Midnight existed, past tense.",
        "Unmaking protocol online.",
        "Disintegrate deployed.",
        "Reality beam activated.",
        "Disintegration complete.",
        "Unmade via dragon magic.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Draconic magic adjusted.",
        "<spec> mode. The dragonflights adapt.",
        "Switched to <spec>. Dragon aspect recalibrated.",
        "<spec> selected. Wyrmrest strategy changed.",
        "New spec, same evoker: <spec>.",
      },
    },

    -- ====================================================================
    -- DEVASTATION EVOKER SPEC-SPECIFIC TRIGGERS (SpecID: 1467)
    -- ====================================================================
    {
      id = "evoker_living_flame_dev",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 1467, spellName = "Living Flame" },
      messages = {
        "Living Flame. Dragon fire.",
        "Flame deployed.",
        "Living fire online.",
        "Flame engaged.",
        "Dragon flame activated.",
      },
    },
    {
      id = "evoker_pyre",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 1467, spellName = "Pyre" },
      messages = {
        "Pyre. AoE dragon fire.",
        "Pyre deployed.",
        "Fire AoE online.",
        "Pyre engaged.",
        "Funeral fire activated.",
      },
    },
    {
      id = "evoker_azure_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 1467, spellName = "Azure Strike" },
      messages = {
        "Azure Strike. Blue magic.",
        "Azure deployed.",
        "Blue strike online.",
        "Azure engaged.",
        "Blue dragon activated.",
      },
    },
    {
      id = "evoker_shattering_star",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 1467, spellName = "Shattering Star" },
      messages = {
        "Shattering Star. Vulnerability.",
        "Star deployed.",
        "Shatter online.",
        "Star engaged.",
        "Shattering activated.",
      },
    },

    -- ====================================================================
    -- PRESERVATION EVOKER SPEC-SPECIFIC TRIGGERS (SpecID: 1468)
    -- ====================================================================
    {
      id = "evoker_living_flame_pres",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 1468, spellName = "Living Flame" },
      messages = {
        "Living Flame. Heal or harm.",
        "Flame deployed.",
        "Living fire online.",
        "Versatile flame engaged.",
        "Dragon flame activated.",
      },
    },
    {
      id = "evoker_emerald_blossom",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 1468, spellName = "Emerald Blossom" },
      messages = {
        "Emerald Blossom. AoE heal.",
        "Blossom deployed.",
        "Emerald heal online.",
        "Green heal engaged.",
        "Blossom activated.",
      },
    },
    {
      id = "evoker_dream_breath",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 1468, spellName = "Dream Breath" },
      messages = {
        "Dream Breath. HoT breath.",
        "Dream deployed.",
        "Breath HoT online.",
        "Dream engaged.",
        "Healing breath activated.",
      },
    },
    {
      id = "evoker_reversion",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 1468, spellName = "Reversion" },
      messages = {
        "Reversion. Time heal.",
        "Reversion deployed.",
        "Temporal heal online.",
        "Reversion engaged.",
        "Time healing activated.",
      },
    },
    {
      id = "evoker_rewind",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 1468, spellName = "Rewind" },
      messages = {
        "Rewind. Time reversal heal.",
        "Rewind deployed.",
        "Time heal online.",
        "Rewind engaged.",
        "Temporal restoration activated.",
      },
    },

    -- ====================================================================
    -- AUGMENTATION EVOKER SPEC-SPECIFIC TRIGGERS (SpecID: 1473)
    -- ====================================================================
    {
      id = "evoker_eruption",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 1473, spellName = "Eruption" },
      messages = {
        "Eruption. Essence burst.",
        "Eruption deployed.",
        "Burst online.",
        "Eruption engaged.",
        "Essence activated.",
      },
    },
    {
      id = "evoker_upheaval",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 1473, spellName = "Upheaval" },
      messages = {
        "Upheaval. Ground eruption.",
        "Upheaval deployed.",
        "Earth burst online.",
        "Upheaval engaged.",
        "Ground shake activated.",
      },
    },
    {
      id = "evoker_prescience",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 1473, spellName = "Prescience" },
      messages = {
        "Prescience. Damage buff.",
        "Prescience deployed.",
        "Foresight online.",
        "Buff engaged.",
        "Prescience activated.",
      },
    },
    {
      id = "evoker_breath_of_eons",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 1473, spellName = "Breath of Eons" },
      messages = {
        "Breath of Eons. Time breath.",
        "Eons deployed.",
        "Temporal breath online.",
        "Eons engaged.",
        "Time breath activated.",
      },
    },
  },
})
