-- EmoteControl - Daily Activities Pack
-- Non-combat flavor triggers for everyday activities

EmoteControl = EmoteControl or {}
local addon = EmoteControl

local pack = {
  name = "DailyActivities",
  version = "0.8.0",
  triggers = {
    -- ========================================
    -- Mount Summons
    -- ========================================
    {
      id = "mount_ground",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Traveling Mount" },
      messages = {
        "summons their trusty mount.",
        "hops onto their mount with practiced ease.",
        "calls forth their mount.",
        "mounts up and prepares to ride.",
        "whistles for their loyal companion.",
        "Engaging travel mode.",
        "Get in loser, we're doing dailies.",
        "Mount up!",
        "My other ride is a dragon.",
        "Why walk when you can ride?",
        "Saddle sore incoming.",
        "Gotta go fast.",
        "Autopilot engaged.",
        "Summoning the beast of burden.",
        "Please don't daze me.",
        "Hops onto steed with confidence.",
        "Calls forth their land-based companion.",
        "Ground travel commencing.",
        "Mounts with practiced grace.",
        "Summons their overland transport.",
        "Ready to roam the world.",
        "Engaging speed mode.",
        "Let's hit the road.",
        "Four hooves thundering forth.",
        "My personal carriage arrives.",
        "The beast answers the call.",
        "Saddle secured. Journey begins.",
        "No more foot travel.",
        "Transportation acquired.",
        "Journey mode: activated.",
        "Mounted and ready to explore.",
        "Stomping toward adventure.",
        "The mount emerges from shadow.",
        "Ride like the wind awaits.",
        "Sure-footed companion summoned.",
        "Let's cover some ground.",
        "The faithful steed returns.",
        "Mounted up. Distance is nothing.",
      },
    },
    {
      id = "mount_flying",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Flying Mount" },
      messages = {
        "takes to the skies!",
        "spreads their wings and prepares for flight.",
        "summons their flying mount with a flourish.",
        "prepares for aerial travel.",
        "calls down their winged companion.",
        "Engaging travel mode.",
        "Get in loser, we're doing dailies.",
        "Mount up!",
        "My other ride is a dragon.",
        "Why walk when you can ride?",
        "Saddle sore incoming.",
        "Gotta go fast.",
        "Autopilot engaged.",
        "Summoning the beast of burden.",
        "Please don't daze me.",
        "Wings spread wide for adventure.",
        "Ascends toward the heavens.",
        "A flying creature emerges.",
        "Takes flight with determination.",
        "Airborne travel commencing.",
        "Ready to soar across the skies.",
        "Engaging aerial mode.",
        "Up, up, and away!",
        "My kingdom for some wings.",
        "Watch me fly.",
        "The sky awaits my presence.",
        "Flying high above the ground.",
        "Wings beating. Journey beginning.",
        "Sky travel acquired.",
        "Aerial transportation ready.",
        "Time to fly this route.",
        "Ascending gracefully.",
        "The mount rises majestically.",
        "Preparing to touch the clouds.",
        "Soaring toward my destination.",
        "The sky is my highway.",
        "Flying over the world below.",
        "Elevation gain: maximum.",
        "Airborne and heading out.",
      },
    },

    -- ========================================
    -- Hunter Pets
    -- ========================================
    {
      id = "call_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 883 }, -- Call Pet 1
      messages = {
        "whistles loudly, calling their faithful companion.",
        "summons their loyal beast.",
        "calls their pet to their side.",
        "beckons their animal companion.",
        "reunites with their trusted pet.",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
        "Calls forth their beast companion.",
        "A furry guardian appears.",
        "The pet answers the call.",
        "Summoning the four-legged friend.",
        "Pet acquisition: complete.",
        "Let's hunt together.",
        "Ready for some teamwork.",
        "The beast joins the adventure.",
        "Howling echoes through the land.",
        "My companion has arrived.",
        "Attack buddy engaged.",
        "The hunting pack assembles.",
        "Together we are stronger.",
        "Pet call accepted.",
        "Claw and fang unite.",
        "The partnership begins.",
        "Come to me, old friend.",
        "Bonded hunter and beast.",
        "Time to hunt with my pal.",
        "Two become one force.",
        "My animal ally returns.",
        "The beast stirs at my call.",
        "Ready to fight alongside my pet.",
        "Together we roam the lands.",
      },
    },
    {
      id = "revive_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellID = 982 }, -- Revive Pet
      messages = {
        "It's okay, <pet>. I've got you.",
        "Come back to me, friend.",
        "Not losing you today!",
        "Rise, my companion!",
        "Welcome back, <pet>!",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
        "Pet resurrection initiated.",
        "Second wind granted to my ally.",
        "The beast awakens once more.",
        "Breath returns to my companion.",
        "Bringing back my trusted friend.",
        "Life force restored.",
        "My pet will not be defeated.",
        "Back from the brink, buddy.",
        "Together again, <pet>.",
        "Bringing vitality to my beast.",
        "The bond pulls my pet back.",
        "Resurrection complete.",
        "Welcome home, old friend.",
        "Standing tall together once more.",
        "My pet refuses to fall.",
        "Life returns to my companion.",
        "The fight is not over.",
        "My beast rises with renewed vigor.",
        "Resurrection magic flows.",
        "Companion called back from death.",
        "<pet>, I need you.",
        "Never leaving you behind.",
        "Revival spell flows.",
        "The battle continues with us both.",
        "My loyal friend returns.",
      },
    },
    {
      id = "dismiss_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 2641 }, -- Dismiss Pet
      messages = {
        "sends their pet away for now.",
        "dismisses their companion.",
        "bids farewell to their pet temporarily.",
        "releases their beast from service.",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
        "Go to your room.",
        "Unsummoning the zoo.",
        "You're free... for now.",
        "Pet enters standby mode.",
        "Dismissing my hunting companion.",
        "Releasing the beast temporarily.",
        "Pet takes a break.",
        "Farewell for now, faithful friend.",
        "Beast withdraws to the shadows.",
        "Companion returns to the wilds.",
        "Sending my ally to rest.",
        "Pet departs peacefully.",
        "Releasing the hunter's bond.",
        "The creature phases out.",
        "Dismissal spell activated.",
        "Back to wherever beasts go.",
        "My pet awaits the next call.",
        "Temporary parting engaged.",
        "The beast returns to slumber.",
        "Pet summoning reversed.",
        "A moment of peace without combat.",
        "Companion energy dissipates.",
        "Unsummoning the loyal beast.",
        "The hunt pauses for now.",
        "My friend departs willingly.",
      },
    },

    -- ========================================
    -- Warlock Pets
    -- ========================================
    {
      id = "summon_imp",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 688 },
      messages = {
        "summons an imp with a puff of fel energy.",
        "calls forth their impish servant.",
        "conjures an imp to do their bidding.",
        "beckons forth a cackling imp.",
        "Little firestarter, get out here.",
        "I need a stamina buff and sarcasm.",
        "Imp: 'Is this really necessary?' Me: 'Yes.'",
        "Don't touch the contract.",
        "Fireball cannon deployed.",
        "He's small, annoying, and burns things.",
        "Try not to pull the whole room.",
        "Portable lighter summoned.",
        "Stop complaining and shoot.",
        "The only friend I need is a chaotic imp.",
        "Phase shift isn't going to save you from work.",
        "Imp summons with typical rudeness.",
        "A tiny demon emerges cackling.",
        "The fiery menace answers the call.",
        "My sarcastic familiar arrives.",
        "Conjuring a pint-sized troublemaker.",
        "The imp phase-shifts into being.",
        "Getting my miniature chaos engine.",
        "Imp incoming. Complaints welcome.",
        "Summoning annoyance incarnate.",
        "The cackling beast manifests.",
        "Imp ready. Attitude guaranteed.",
        "My tiny infernal overlord appears.",
        "The imp demands to know why.",
        "Summoned: one sarcastic imp.",
        "Impish servant, at your service. Reluctantly.",
      },
    },
    {
      id = "summon_voidwalker",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 697 },
      messages = {
        "tears open reality, summoning a voidwalker.",
        "calls a voidwalker from the shadows.",
        "conjures a hulking voidwalker guardian.",
        "rips a voidwalker from the void itself.",
        "I need a meat shield. Well, void shield.",
        "Blueberry, you're up.",
        "Prepare to suffer... for my benefit.",
        "Tank mode engaged.",
        "Big blue bodyguard.",
        "I don't like you, you don't like me, let's kill things.",
        "Send him in first.",
        "Absorb my problems, please.",
        "Voidwalker: 'Send me back.' Me: 'No.'",
        "Taunt everything.",
        "My personal wall of shadow.",
        "Void guardian materializes.",
        "A massive void presence emerges.",
        "The blue sentinel rises.",
        "Voidwalker answers the call.",
        "Summoning a wall of protection.",
        "My tank arrives from the void.",
        "The shield generator activates.",
        "Void energy coalesces into form.",
        "Blueberry demands snacks.",
        "Go soak up the damage.",
        "Tank spawned. Aggro incoming.",
        "The fortress of void arrives.",
        "My blue friend emerges ready.",
        "Void guardian, your time has come.",
        "Shadow takes tangible form.",
        "Standing between me and harm.",
        "The void yields its warden.",
        "Bodyguard acquired.",
        "Voidwalker: reluctantly here.",
        "Tank mode: activated.",
        "My shadow companion manifests.",
        "Pull everything. I dare you.",
        "Blue wall of frustration.",
        "Void summons its protector.",
      },
    },
    {
      id = "summon_succubus",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 712 },
      messages = {
        "summons a seductive succubus.",
        "calls forth a deadly succubus.",
        "conjures a charming yet dangerous ally.",
        "beckons a succubus from the nether.",
        "Time for some charm.",
        "Don't get too attached.",
        "Seduction tactic initiated.",
        "Whip it good.",
        "She's just here for the DPS, I swear.",
        "Crowd control? Or crowd pleaser?",
        "Lash of pain incoming.",
        "Behave yourself.",
        "Kiss of death.",
        "Invisibility on.",
        "Distracting the humanoids.",
        "Succubus emerges from shadow.",
        "A dangerous beauty appears.",
        "Charm offensive engaged.",
        "The seductress manifests.",
        "Demonic charm summoned.",
        "She exists primarily for DPS.",
        "Whipping demon arrives.",
        "Succubus: ready and sarcastic.",
        "Control lost. As usual.",
        "Charm, whip, repeat.",
        "The demon of seduction emerges.",
        "My little nightmare helper.",
        "Summoning: one deadly succubus.",
        "Nether's charms made manifest.",
        "She makes sarcastic comments.",
        "Demon arrives with attitude.",
        "Succubus: questioning my life choices.",
        "Prepare for demonic charm.",
        "The enchantress materializes.",
        "Invisible crowd control incoming.",
        "Kiss of death ready.",
        "The whip cracks ominously.",
        "Summoned: one charming demon.",
        "My demon companion appears.",
      },
    },
    {
      id = "summon_felhunter",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 691 },
      messages = {
        "summons a felhunter to devour magic.",
        "calls forth a mana-hungry felhunter.",
        "conjures a felhunter demon.",
        "releases a felhunter from the Twisting Nether.",
        "Sniff out the magic.",
        "Good dog. Scary dog.",
        "Time to eat some buffs.",
        "Silence the casters.",
        "Who's a good mage-eater?",
        "Anti-magic shield generator.",
        "Devour magic!",
        "He bites.",
        "Tracking demons and wizards.",
        "Interrupt bot engaged.",
        "Don't drool on the loot.",
        "Felhunter arrives. Hunt begins.",
        "A vicious beast emerges.",
        "Magic devoured incoming.",
        "The creature awakens.",
        "Felhunter summoned to feed.",
        "My mana-hungry helper arrives.",
        "The hunter of magic materializes.",
        "Silence incoming from the beast.",
        "Felhunter ready to feast.",
        "The nightmare hound appears.",
        "Anti-magic protection engaged.",
        "The spell devouerer awakens.",
        "Felhunter: snarling and hungry.",
        "Cast interruption ready.",
        "Mana-eater engaged.",
        "The beast hungers for caster buffs.",
        "Felhunter demands sacrifice.",
        "Magic will be consumed.",
        "The hunter rises to feed.",
        "Warding the warlocks.",
        "Felhunter: terror of mages.",
        "The demonic hound materializes.",
        "Interrupt: standing by.",
        "Devouring spells and hope.",
        "Felhunter, time to hunt magic.",
      },
    },

    -- ========================================
    -- Mage Summons
    -- ========================================
    {
      id = "conjure_refreshment",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 190336 },
      messages = {
        "conjures fresh food and water from thin air.",
        "creates magical refreshments with a wave.",
        "summons a feast of arcane sustenance.",
        "produces food and drink through magic.",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the raid.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
        "Arcane supplies materialize.",
        "Magical snacks appear.",
        "Conjuring provisions.",
        "Food summon spell complete.",
        "Feeding time for adventurers.",
        "Arcane cuisine ready.",
        "Mana buns: fresh from the ether.",
        "Refreshment tower established.",
        "Sustenance flows from magic.",
        "Chef mode: initiated.",
        "Nourishment acquired through spellcraft.",
        "Table waiting for hungry heroes.",
        "Summoned: snacks and hydration.",
        "Magical kitchen opens.",
        "Food conjuration successful.",
        "Feast emerges from nothingness.",
        "Sharing arcane provisions.",
        "Refreshment available to all.",
        "Mage's pantry opens.",
        "Sustenance emerges from arcane energy.",
        "Everyone, grab a bite!",
        "Catering services activated.",
        "Food table: ready for consumption.",
        "Magical provisions distributed.",
      },
    },
    {
      id = "summon_table",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellID = 43987 },
      messages = {
        "Table's up! Help yourselves!",
        "Conjured a feast for everyone!",
        "Food and drink ready!",
        "Refreshments for all!",
        "Banquet is served!",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the raid.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
        "Portal to sustenance opened.",
        "Mage's banquet manifests.",
        "Summoned: entire feast.",
        "Dining table appears.",
        "Arcane dining hall established.",
        "Feast for the weary adventurers.",
        "Table of plenty summoned.",
        "Everyone eats. Now.",
        "The table is set.",
        "Magical dining furniture appears.",
        "Food service: activated.",
        "Refreshment headquarters online.",
        "Summon complete: full buffet.",
        "Banquet hall formed from magic.",
        "The gathering food conjures itself.",
        "Table manifests for sustenance.",
        "Mage's table: premium quality.",
        "Dining services established.",
        "Feast materials summoned.",
        "The table awaits diners.",
        "Conjured: the ultimate table.",
        "Food table ready for service.",
        "All welcome to the feast.",
        "Magical dining: now available.",
      },
    },

    -- ========================================
    -- Other Activities
    -- ========================================
    {
      id = "check_mail",
      event = "MAIL_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "checks their mailbox, hoping for a letter.",
        "opens the mailbox, expecting something important.",
        "rummages through the mail, looking for treasures.",
        "checks for new mail, a daily ritual.",
        "sorts through their correspondence.",
        "Checking for hate mail.",
        "Please be gold, please be gold.",
        "Postmaster again? I looted that!",
        "Spam mail in a fantasy game? Really?",
        "Collecting my auction house dividends.",
        "Fan mail? Nope, just expired auctions.",
        "Mailbox dance initiated.",
        "You've got mail! (In 2004 voice).",
        "Why is the mailbox always so far away?",
        "Sending angry letters to the RNG gods.",
        "Mail check time. The daily grind continues.",
        "Perhaps this time there's treasure.",
        "Mailbox opens. Disappointment awaits.",
        "Checking correspondence.",
        "The postmaster visits again.",
        "Mail notifications: a cruel mistress.",
        "Opening: mostly junk mail.",
        "Auction house results revealed.",
        "Inbox investigation commencing.",
        "Sent items returned? Excellent.",
        "Mailbox: gateway to hope and despair.",
        "Is that gold? Probably not.",
        "Checking messages from five expansions ago.",
        "Mailbox contents: always disappointing.",
        "The postmaster knows my secrets.",
        "Mail received. Usually vendor spam.",
        "Mailbox: where dreams go to die.",
        "Opening mail with low expectations. Still disappointed.",
        "The daily mail check ritual begins.",
        "Another round of auction House fees.",
        "Mailbox opens. Mostly cobwebs.",
        "Checking for letters of import.",
        "The mail awaits my attention.",
        "Mailbox unlocked. Contents: meh.",
        "Postal service: still overdue.",
      },
    },
    {
      id = "open_bank",
      event = "BANKFRAME_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "accesses their bank vault.",
        "opens their personal storage.",
        "digs through their stashed belongings.",
        "checks their savings and stored items.",
        "visits the bank to manage their hoard.",
        "Opening the vault.",
        "Dumping mats.",
        "Into the abyss of hoarding.",
        "Where did I put that item from three expansions ago?",
        "Visiting my frozen assets.",
        "Bag space is temporary, bank space is... also full.",
        "Depositing my regrets.",
        "I swear I have a sorting system (I don't).",
        "Goblins charge too much interest.",
        "Safe deposit box: Accessed.",
        "Bank vault: time to organize chaos.",
        "The hoard grows larger.",
        "Bank interface: unlocked.",
        "Storage solutions needed urgently.",
        "The dragon's treasure trove.",
        "Banking: separating junk from treasure.",
        "Vault contents: 80 percent vendor trash.",
        "Organized hoarding commences.",
        "Bank time: where did I put that?",
        "The deposit box welcomes me.",
        "Banking on hope and chaos.",
        "Opening: prepared for disappointment.",
        "Vaults within vaults.",
        "My financial empire displayed.",
        "Bank access: granted (with interest charges).",
        "Storing: more stuff than sense.",
        "The vault: my second home.",
        "Banking: professions hoarded.",
        "Storage optimization: failing.",
        "The deposit box awaits.",
        "Vault inspection time.",
        "Banks: where gold goes to sleep.",
        "Organizing the carefully curated mess.",
        "Opening my treasure chest of mostly trash.",
      },
    },
    {
      id = "talk_to_vendor",
      event = "MERCHANT_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "browses the merchant's wares.",
        "examines the goods for sale.",
        "haggles with the vendor.",
        "looks for useful supplies.",
        "considers making a purchase.",
        "Vendor: 'What can I do for you?' Me: 'Buy my trash.'",
        "Selling gray items. Profit: 4 copper.",
        "Show me your wares.",
        "I am here to sell 400 gray items.",
        "Do you accept exposure as payment?",
        "Just browsing, thanks.",
        "Repair my armor, you greedy NPC.",
        "Selling wolf tails. Don't ask where I got them.",
        "Liquidation sale in progress.",
        "Haggling protocol... failed.",
        "Vendor interaction engaged.",
        "Selling my valuables for pennies.",
        "Merchant assessment: expensive and unhelpful.",
        "Vendor wares: underwhelming.",
        "Hawking gray items for copper.",
        "The merchant's prices remain ridiculous.",
        "Browsing: looking for bargains.",
        "Vendor negotiation: imminent.",
        "Trade: one-sided economic depression.",
        "The vendor surveys my garbage.",
        "Shopping spree: curtailed by finances.",
        "Vendor window: opened with regret.",
        "Gray items sold. Profits: negligible.",
        "The merchant calculates my worth.",
        "Selling stuff I don't need for stuff I don't need.",
        "Vendor assessment complete.",
        "Purchasing decisions: painful.",
        "The vendor marks me as predictable.",
        "Browsing goods I cannot afford.",
        "Vendor transaction: activated.",
        "Turning trash into copper.",
        "The merchant has seen better days. So have I.",
        "Shopping: a necessary financial evil.",
        "Vendor: my best friend and worst enemy.",
        "Haggling: my specialty. His: not listening.",
      },
    },
    {
      id = "start_fishing",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 131474 }, -- Fishing
      messages = {
        "casts their line, hoping for a bite.",
        "settles in for some peaceful fishing.",
        "patiently waits for a tug on the line.",
        "begins fishing, the water looks promising.",
        "drops a line into the water.",
        "Gone fishing. Don't text.",
        "Equipping the Pole of Patience.",
        "Time to stare at water for an hour.",
        "I hope I catch a mount this time.",
        "Master Angler mode: On.",
        "Splash. Now we wait.",
        "Fish fear me. Women fear me.",
        "Relaxing... or falling asleep?",
        "Is this bait fresh? It smells like ghoul.",
        "Just one more cast (said ten casts ago).",
        "Fishing line: cast into destiny.",
        "Waiting for the aquatic to bite.",
        "The fishing begins in earnest.",
        "Patience activated. Actively.",
        "Water awaits my fishing expertise.",
        "Hook, line, and meditative sinker.",
        "Fishing meditation commences.",
        "The catch awaits discovery.",
        "Line cast. Dreams await.",
        "Angler mode: fully engaged.",
        "The water calls to my fishing soul.",
        "Patience tested by boredom.",
        "Fishing rod: instrument of zen.",
        "Cast complete. Vibing with fish.",
        "Awaiting the ultimate catch.",
        "The pole awaits its purpose.",
        "Fish somewhere in this water.",
        "Fishing: meditation with a rod.",
        "The water keeps its secrets.",
        "Line cast toward fortune.",
        "Fishing for luck and sea creatures.",
        "Patient as stone. Well, trying.",
        "The water has spoken. Silence.",
        "Fishing: the ultimate AFK activity.",
        "Cast. Wait. Hope.",
      },
    },
    {
      id = "cooking",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 818 }, -- Basic Campfire
      messages = {
        "starts a fire and prepares to cook.",
        "sets up camp and lights a fire.",
        "creates a cozy campfire.",
        "kindles a fire for cooking.",
        "builds a campfire with practiced hands.",
        "Cooking skill: Burnt to perfection.",
        "Iron Chef Azeroth.",
        "Don't ask what kind of meat this is.",
        "Adding +30 Stamina to the pot.",
        "Preparing the pre-raid buff.",
        "Burning dinner... again.",
        "Gordon Ramsay would ban me for this.",
        "Salt, pepper, and a little bit of magic dust.",
        "Great Feast incoming!",
        "Cooking over an open fire (because I'm homeless).",
        "The fire roars to life.",
        "Culinary adventure commences.",
        "Flames rise. Cooking begins.",
        "Food preparation: initiated.",
        "The campfire awaits offerings.",
        "Cooking magic: activate.",
        "Ingredients: questionable, yet combined.",
        "Fire + random items = sustenance.",
        "The feast takes shape.",
        "Cooking: part chemistry, part luck.",
        "Flames dance around the cauldron.",
        "Pre-raid feast initiated.",
        "The pot bubbles ominously.",
        "Culinary genius or complete disaster?",
        "Cooking: my second expertise.",
        "The campfire crackles hungrily.",
        "Food sizzles. Confidence wavers.",
        "Buff food: incoming (probably).",
        "Cooking for the masses. Barely.",
        "Fire and food: ancient pairing.",
        "The great feast experiment.",
        "Flames lick the pot eagerly.",
        "Stamina food: inbound.",
        "Cooking with confidence. Misplaced.",
        "The campfire and I create food.",
      },
    },
    {
      id = "hearthstone",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 8690 },
      messages = {
        "channels their hearthstone, preparing to teleport home.",
        "activates their hearthstone with a nostalgic sigh.",
        "uses their hearthstone to return home.",
        "begins the journey home via hearthstone.",
        "teleports back to their inn with magic.",
        "Hearthstone cast. There's no place like inn.",
        "Bubble heart? No, just heart.",
        "Clicking heels three times.",
        "Get me out of here!",
        "Hearthstone: The ultimate panic button.",
        "Homeward bound.",
        "Please don't interrupt the cast!",
        "Setting course for the Inn.",
        "Travel time: 10 seconds. Don't hit me.",
        "Returning to sanctuary.",
        "Hearthstone activated. Warmth incoming.",
        "Channel to home: beginning.",
        "The stone glows with purpose.",
        "Journey home commences.",
        "Hearthstone magic: flowing.",
        "Home calling. I answer.",
        "Portal to comfort opening.",
        "Ten seconds away from rest.",
        "The hearthstone pulses with power.",
        "Teleportation in progress.",
        "Home: locked and loaded.",
        "Hearthstone: my life's greatest love.",
        "Channel initiated. Fingers crossed.",
        "The warm glow of home awaits.",
        "Hearthstone: functional teleportation.",
        "Home is calling my name.",
        "The stone sings to me.",
        "Casting: escape plan engaged.",
        "Hearthstone, my truest ally.",
        "The inn beckons.",
        "Home awaits beyond the veil.",
        "Preparing departure via magic.",
        "The stone glows brighter.",
        "Channeling: survival instinct active.",
        "Home: my final destination (for now).",
      },
    },
    {
      id = "flight_path",
      event = "TAXIMAP_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "consults the flight master about travel routes.",
        "plans their next flight path.",
        "examines the available flight routes.",
        "considers where to fly next.",
        "speaks with the flight master.",
        "Taxi!",
        "Enjoying the scenic route (forced).",
        "Why does this flight path go in a circle?",
        "AFK for 5 minutes, flying.",
        "Gryphon Airlines: We get you there, eventually.",
        "Please keep your hands inside the beast at all times.",
        "I can see my house from here!",
        "Autopilot to the next zone.",
        "Mid-air snack time.",
        "If I fall off, I die. Fun.",
        "The flight master smiles knowingly.",
        "Aeronautical decisions pending.",
        "Flight path: analyzing options.",
        "The route home: mapped.",
        "Where shall my mount take me?",
        "Flying: the scenic route.",
        "Taxi route: consulted.",
        "The beast awaits my destination.",
        "Air travel: charted.",
        "The master of flight: consulted.",
        "Where to next, noble flyer?",
        "Flight consultation: underway.",
        "The skies call. Choose a path.",
        "Flying: the AFK transportation.",
        "The flight map: a puzzle.",
        "Destination unknown. Excitement high.",
        "The flight awaits initiation.",
        "Gryphons: ready for duty.",
        "The master points toward destiny.",
        "Air routes: many and varied.",
        "Flying: passive income mode activated.",
        "The beast knows the way.",
        "Flight path selected. Sit back.",
        "Air travel engaging. AFK accepted.",
        "Time to ride the skies.",
      },
    },

    -- ========================================
    -- Vanity / Utility
    -- ========================================
    {
      id = "transmog_apply",
      event = "TRANSMOGRIFY_SUCCESS",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "Fashion upgraded. Stats unchanged.",
        "New look. Same bad decisions.",
        "Drip check passed.",
        "I am not here to win. I am here to slay.",
        "Transmog complete. Please admire responsibly.",
        "I just spent gold to look incredible.",
        "Gear looks better. Performance still questionable.",
        "Endgame achieved. Outfit perfected.",
        "I changed my look. Mechanics are next.",
        "Fresh transmog. Fresh confidence.",
        "I am now 20 percent more heroic looking.",
        "I call this one: 'Raid Ready, Emotionally Fragile.'",
        "Glamour is the true currency of Azeroth.",
        "Look good. Pull good. Probably.",
        "Do not judge my mog. Judge my DPS. Actually don't.",
        "Transmog magic: applied.",
        "Fashion transformation complete.",
        "My drip: improved substantially.",
        "Aesthetics: upgraded.",
        "Looking fierce and fabulously.",
        "Mog: now legendary status.",
        "Style points: maximized.",
        "The glam is real.",
        "Transmog success: undeniable.",
        "Outfit: now worthy of a raid.",
        "Fashion game: elevated.",
        "My mog speaks for itself.",
        "Stylin' and profilin' intensifies.",
        "The transmog gods smile upon me.",
        "Fashion: my true endgame.",
        "Looking sharp. Hitting harder? Doubtful.",
        "Transmog applied with prejudice.",
        "The outfit now matches my ego.",
        "Glamour enabled. Humility: optional.",
        "The mog is complete. I am unstoppable.",
        "Fashion sense: activated.",
        "Transmog: worth every gold.",
        "My style: now undeniable.",
        "Looking good is half the battle.",
        "Transmog finished. Ready to slay.",
      },
    },
    {
      id = "portal_use",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellName = { "Portal:*", "Teleport:*" } },
      messages = {
        "Portal up. Try not to click the wrong one.",
        "Arcane express now boarding.",
        "Please use the portal. Walking is optional.",
        "Teleportation is just aggressive convenience.",
        "Portal online. Mind the step.",
        "I have opened a door through reality. You're welcome.",
        "Step through. Do not ask where it goes.",
        "Portal ready. No refunds.",
        "Arcane commute engaged.",
        "If you end up in Dalaran, that's on you.",
        "I am basically public transportation.",
        "Portal deployed. Please form an orderly stampede.",
        "Reality has been folded for your comfort.",
        "Free ride. Tips accepted in mana buns.",
        "Go on. Touch the magic circle.",
        "Portal established. Boarding now.",
        "Spatial gateway: open for business.",
        "The portal shimmers invitingly.",
        "Teleportation tech: activated.",
        "Arcane doorway: ready.",
        "The mage has provided transport.",
        "Portal magic: channeling strongly.",
        "Arcane travel: secured.",
        "The portal awaits your passage.",
        "Gateway: dimensional and open.",
        "Teleportation service: now available.",
        "The barrier between worlds: open.",
        "Hop through. Trust the mage.",
        "Portal established. Destination: somewhere.",
        "The gateway glows with purpose.",
        "Arcane pathways: mapped and ready.",
        "The mage opens doors. Literally.",
        "Portal: faster than your legs.",
        "Reality bends to my will.",
        "Hop in. Gravity: negotiable.",
        "The portal pulses with magic.",
        "Teleportation: now convenient.",
        "Arcane express departing.",
        "The gateway beckons adventurers.",
        "Portal magic: maximized for travel.",
      },
    },
    {
      id = "use_toy",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = { "Toy:*" } },
      messages = {
        "Deploying unnecessary fun.",
        "Toy time. Productivity down. Vibes up.",
        "This is important. For morale.",
        "I am contributing to the group experience.",
        "Tactical distraction engaged.",
        "Toy deployed. Please pretend to be impressed.",
        "This is my raid utility. Don't question it.",
        "Serious content requires unserious behavior.",
        "I paid gold for this. Therefore it must be used.",
        "Fun detected. Initiating chaos.",
        "I am roleplaying. Aggressively.",
        "Toy used. Emotional support activated.",
        "If we wipe, at least we had fun.",
        "Witness my collection of nonsense.",
        "This is why my bags are full.",
        "The toy is unleashed.",
        "Fun activated. Mechanics: optional.",
        "Toy time: because life is short.",
        "Nonsense: deployed for group morale.",
        "The toy serves a purpose.",
        "Whimsy: now active.",
        "Frivolous magic: engaged.",
        "The toy radiates joy (annoyance).",
        "Fun time: mandatory.",
        "My toy collection: put to use.",
        "Entertainment value: maximum.",
        "The toy speaks for itself.",
        "Fun is the best DPS.",
        "This toy: worth the bag space.",
        "Enjoyment: actively seeking.",
        "The toy summons pure joy.",
        "Ridiculous: embraced fully.",
        "This item: necessary and vital.",
        "Toy: more important than gear.",
        "The toy: my greatest achievement.",
        "Fun: not optional. Mandatory.",
        "Toys: why we raid.",
        "The toy glows with potential.",
        "Nonsense intensity: elevated.",
        "This toy: priceless entertainment.",
      },
    },
  },
}

addon:RegisterPack(pack)
