-- EmoteControl - Daily Activities Pack
-- Non-combat flavor triggers for everyday activities

EmoteControl = EmoteControl or {}
local addon = EmoteControl

local pack = {
  name = "DailyActivities",
  version = "0.8.0",
  triggers = {
    -- ========================================
    -- Mount Summons
    -- ========================================
    {
      id = "mount_ground",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Traveling Mount" },
      messages = {
        "summons their trusty mount.",
        "hops onto their mount with practiced ease.",
        "calls forth their mount.",
        "mounts up and prepares to ride.",
        "whistles for their loyal companion.",
        "Engaging travel mode.",
        "Get in loser, we're doing dailies.",
        "Mount up!",
        "My other ride is a dragon.",
        "Why walk when you can ride?",
        "Saddle sore incoming.",
        "Gotta go fast.",
        "Autopilot engaged.",
        "Summoning the beast of burden.",
        "Please don't daze me.",
      },
    },
    {
      id = "mount_flying",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Flying Mount" },
      messages = {
        "takes to the skies!",
        "spreads their wings and prepares for flight.",
        "summons their flying mount with a flourish.",
        "prepares for aerial travel.",
        "calls down their winged companion.",
        "Engaging travel mode.",
        "Get in loser, we're doing dailies.",
        "Mount up!",
        "My other ride is a dragon.",
        "Why walk when you can ride?",
        "Saddle sore incoming.",
        "Gotta go fast.",
        "Autopilot engaged.",
        "Summoning the beast of burden.",
        "Please don't daze me.",
      },
    },

    -- ========================================
    -- Hunter Pets
    -- ========================================
    {
      id = "call_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 883 }, -- Call Pet 1
      messages = {
        "whistles loudly, calling their faithful companion.",
        "summons their loyal beast.",
        "calls their pet to their side.",
        "beckons their animal companion.",
        "reunites with their trusted pet.",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
      },
    },
    {
      id = "revive_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellID = 982 }, -- Revive Pet
      messages = {
        "It's okay, <pet>. I've got you.",
        "Come back to me, friend.",
        "Not losing you today!",
        "Rise, my companion!",
        "Welcome back, <pet>!",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
      },
    },
    {
      id = "dismiss_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 2641 }, -- Dismiss Pet
      messages = {
        "sends their pet away for now.",
        "dismisses their companion.",
        "bids farewell to their pet temporarily.",
        "releases their beast from service.",
        "Get out here, whiskers.",
        "I choose you!",
        "Don't eat the healer.",
        "Go fetch.",
        "Back in the pokeball.",
        "He was just resting his eyes.",
        "Don't look at me like that, go tank.",
        "Sit. Stay. Attack.",
        "Best friend summoned.",
        "Go be a nuisance.",
        "Go to your room.",
        "Unsummoning the zoo.",
        "You're free... for now.",
      },
    },

    -- ========================================
    -- Warlock Pets
    -- ========================================
    {
      id = "summon_imp",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 688 },
      messages = {
        "summons an imp with a puff of fel energy.",
        "calls forth their impish servant.",
        "conjures an imp to do their bidding.",
        "beckons forth a cackling imp.",
        "Little firestarter, get out here.",
        "I need a stamina buff and sarcasm.",
        "Imp: 'Is this really necessary?' Me: 'Yes.'",
        "Don't touch the contract.",
        "Fireball cannon deployed.",
        "He's small, annoying, and burns things.",
        "Try not to pull the whole room.",
        "Portable lighter summoned.",
        "Stop complaining and shoot.",
        "The only friend I need is a chaotic imp.",
        "Phase shift isn't going to save you from work.",
      },
    },
    {
      id = "summon_voidwalker",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 697 },
      messages = {
        "tears open reality, summoning a voidwalker.",
        "calls a voidwalker from the shadows.",
        "conjures a hulking voidwalker guardian.",
        "rips a voidwalker from the void itself.",
        "I need a meat shield. Well, void shield.",
        "Blueberry, you're up.",
        "Prepare to suffer... for my benefit.",
        "Tank mode engaged.",
        "Big blue bodyguard.",
        "I don't like you, you don't like me, let's kill things.",
        "Send him in first.",
        "Absorb my problems, please.",
        "Voidwalker: 'Send me back.' Me: 'No.'",
        "Taunt everything.",
        "My personal wall of shadow.",
      },
    },
    {
      id = "summon_succubus",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 712 },
      messages = {
        "summons a seductive succubus.",
        "calls forth a deadly succubus.",
        "conjures a charming yet dangerous ally.",
        "beckons a succubus from the nether.",
        "Time for some charm.",
        "Don't get too attached.",
        "Seduction tactic initiated.",
        "Whip it good.",
        "She's just here for the DPS, I swear.",
        "Crowd control? Or crowd pleaser?",
        "Lash of pain incoming.",
        "Behave yourself.",
        "Kiss of death.",
        "Invisibility on.",
        "Distracting the humanoids.",
      },
    },
    {
      id = "summon_felhunter",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 691 },
      messages = {
        "summons a felhunter to devour magic.",
        "calls forth a mana-hungry felhunter.",
        "conjures a felhunter demon.",
        "releases a felhunter from the Twisting Nether.",
        "Sniff out the magic.",
        "Good dog. Scary dog.",
        "Time to eat some buffs.",
        "Silence the casters.",
        "Who's a good mage-eater?",
        "Anti-magic shield generator.",
        "Devour magic!",
        "He bites.",
        "Tracking demons and wizards.",
        "Interrupt bot engaged.",
        "Don't drool on the loot.",
      },
    },

    -- ========================================
    -- Mage Summons
    -- ========================================
    {
      id = "conjure_refreshment",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 190336 },
      messages = {
        "conjures fresh food and water from thin air.",
        "creates magical refreshments with a wave.",
        "summons a feast of arcane sustenance.",
        "produces food and drink through magic.",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the raid.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
      },
    },
    {
      id = "summon_table",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellID = 43987 },
      messages = {
        "Table's up! Help yourselves!",
        "Conjured a feast for everyone!",
        "Food and drink ready!",
        "Refreshments for all!",
        "Banquet is served!",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the raid.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
      },
    },

    -- ========================================
    -- Other Activities
    -- ========================================
    {
      id = "check_mail",
      event = "MAIL_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "checks their mailbox, hoping for a letter.",
        "opens the mailbox, expecting something important.",
        "rummages through the mail, looking for treasures.",
        "checks for new mail, a daily ritual.",
        "sorts through their correspondence.",
        "Checking for hate mail.",
        "Please be gold, please be gold.",
        "Postmaster again? I looted that!",
        "Spam mail in a fantasy game? Really?",
        "Collecting my auction house dividends.",
        "Fan mail? Nope, just expired auctions.",
        "Mailbox dance initiated.",
        "You've got mail! (In 2004 voice).",
        "Why is the mailbox always so far away?",
        "Sending angry letters to the RNG gods.",
      },
    },
    {
      id = "open_bank",
      event = "BANKFRAME_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "accesses their bank vault.",
        "opens their personal storage.",
        "digs through their stashed belongings.",
        "checks their savings and stored items.",
        "visits the bank to manage their hoard.",
        "Opening the vault.",
        "Dumping mats.",
        "Into the abyss of hoarding.",
        "Where did I put that item from three expansions ago?",
        "Visiting my frozen assets.",
        "Bag space is temporary, bank space is... also full.",
        "Depositing my regrets.",
        "I swear I have a sorting system (I don't).",
        "Goblins charge too much interest.",
        "Safe deposit box: Accessed.",
      },
    },
    {
      id = "talk_to_vendor",
      event = "MERCHANT_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "browses the merchant's wares.",
        "examines the goods for sale.",
        "haggles with the vendor.",
        "looks for useful supplies.",
        "considers making a purchase.",
        "Vendor: 'What can I do for you?' Me: 'Buy my trash.'",
        "Selling gray items. Profit: 4 copper.",
        "Show me your wares.",
        "I am here to sell 400 gray items.",
        "Do you accept exposure as payment?",
        "Just browsing, thanks.",
        "Repair my armor, you greedy NPC.",
        "Selling wolf tails. Don't ask where I got them.",
        "Liquidation sale in progress.",
        "Haggling protocol... failed.",
      },
    },
    {
      id = "start_fishing",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 131474 }, -- Fishing
      messages = {
        "casts their line, hoping for a bite.",
        "settles in for some peaceful fishing.",
        "patiently waits for a tug on the line.",
        "begins fishing, the water looks promising.",
        "drops a line into the water.",
        "Gone fishing. Don't text.",
        "Equipping the Pole of Patience.",
        "Time to stare at water for an hour.",
        "I hope I catch a mount this time.",
        "Master Angler mode: On.",
        "Splash. Now we wait.",
        "Fish fear me. Women fear me.",
        "Relaxing... or falling asleep?",
        "Is this bait fresh? It smells like ghoul.",
        "Just one more cast (said ten casts ago).",
      },
    },
    {
      id = "cooking",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 818 }, -- Basic Campfire
      messages = {
        "starts a fire and prepares to cook.",
        "sets up camp and lights a fire.",
        "creates a cozy campfire.",
        "kindles a fire for cooking.",
        "builds a campfire with practiced hands.",
        "Cooking skill: Burnt to perfection.",
        "Iron Chef Azeroth.",
        "Don't ask what kind of meat this is.",
        "Adding +30 Stamina to the pot.",
        "Preparing the pre-raid buff.",
        "Burning dinner... again.",
        "Gordon Ramsay would ban me for this.",
        "Salt, pepper, and a little bit of magic dust.",
        "Great Feast incoming!",
        "Cooking over an open fire (because I'm homeless).",
      },
    },
    {
      id = "hearthstone",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 8690 },
      messages = {
        "channels their hearthstone, preparing to teleport home.",
        "activates their hearthstone with a nostalgic sigh.",
        "uses their hearthstone to return home.",
        "begins the journey home via hearthstone.",
        "teleports back to their inn with magic.",
        "Hearthstone cast. There's no place like inn.",
        "Bubble heart? No, just heart.",
        "Clicking heels three times.",
        "Get me out of here!",
        "Hearthstone: The ultimate panic button.",
        "Homeward bound.",
        "Please don't interrupt the cast!",
        "Setting course for the Inn.",
        "Travel time: 10 seconds. Don't hit me.",
        "Returning to sanctuary.",
      },
    },
    {
      id = "flight_path",
      event = "TAXIMAP_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "consults the flight master about travel routes.",
        "plans their next flight path.",
        "examines the available flight routes.",
        "considers where to fly next.",
        "speaks with the flight master.",
        "Taxi!",
        "Enjoying the scenic route (forced).",
        "Why does this flight path go in a circle?",
        "AFK for 5 minutes, flying.",
        "Gryphon Airlines: We get you there, eventually.",
        "Please keep your hands inside the beast at all times.",
        "I can see my house from here!",
        "Autopilot to the next zone.",
        "Mid-air snack time.",
        "If I fall off, I die. Fun.",
      },
    },

    -- ========================================
    -- Vanity / Utility
    -- ========================================
    {
      id = "transmog_apply",
      event = "TRANSMOGRIFY_SUCCESS",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "Fashion upgraded. Stats unchanged.",
        "New look. Same bad decisions.",
        "Drip check passed.",
        "I am not here to win. I am here to slay.",
        "Transmog complete. Please admire responsibly.",
        "I just spent gold to look incredible.",
        "Gear looks better. Performance still questionable.",
        "Endgame achieved. Outfit perfected.",
        "I changed my look. Mechanics are next.",
        "Fresh transmog. Fresh confidence.",
        "I am now 20 percent more heroic looking.",
        "I call this one: 'Raid Ready, Emotionally Fragile.'",
        "Glamour is the true currency of Azeroth.",
        "Look good. Pull good. Probably.",
        "Do not judge my mog. Judge my DPS. Actually don't.",
      },
    },
    {
      id = "portal_use",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "SAY",
      conditions = { spellName = { "Portal:*", "Teleport:*" } },
      messages = {
        "Portal up. Try not to click the wrong one.",
        "Arcane express now boarding.",
        "Please use the portal. Walking is optional.",
        "Teleportation is just aggressive convenience.",
        "Portal online. Mind the step.",
        "I have opened a door through reality. You're welcome.",
        "Step through. Do not ask where it goes.",
        "Portal ready. No refunds.",
        "Arcane commute engaged.",
        "If you end up in Dalaran, that's on you.",
        "I am basically public transportation.",
        "Portal deployed. Please form an orderly stampede.",
        "Reality has been folded for your comfort.",
        "Free ride. Tips accepted in mana buns.",
        "Go on. Touch the magic circle.",
      },
    },
    {
      id = "use_toy",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = { "Toy:*" } },
      messages = {
        "Deploying unnecessary fun.",
        "Toy time. Productivity down. Vibes up.",
        "This is important. For morale.",
        "I am contributing to the group experience.",
        "Tactical distraction engaged.",
        "Toy deployed. Please pretend to be impressed.",
        "This is my raid utility. Don't question it.",
        "Serious content requires unserious behavior.",
        "I paid gold for this. Therefore it must be used.",
        "Fun detected. Initiating chaos.",
        "I am roleplaying. Aggressively.",
        "Toy used. Emotional support activated.",
        "If we wipe, at least we had fun.",
        "Witness my collection of nonsense.",
        "This is why my bags are full.",
      },
    },
  },
}

addon:RegisterPack(pack)
