-- EmoteControl - Daily Activities Pack
-- Non-combat flavor triggers for everyday activities

EmoteControl = EmoteControl or {}
local addon = EmoteControl

local pack = {
  name = "DailyActivities",
  version = "0.8.0",
  triggers = {
    -- ========================================
    -- Mount Summons
    -- ========================================
    {
      id = "mount_ground",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Traveling Mount" },
      messages = {
        "summons their trusty mount in <zone>.",
        "hops onto their mount in <subzone> with practiced ease.",
        "calls forth their mount in <zone>.",
        "mounts up and prepares to ride through <subzone>.",
        "whistles for their loyal companion in <zone>.",
        "Engaging travel mode in <zone>.",
        "Get in loser, we're doing dailies.",
        "Mount up!",
        "My other ride is a dragon.",
        "Why walk when you can ride?",
        "Saddle sore incoming.",
        "Gotta go fast through <subzone>.",
        "Autopilot engaged for <zone>.",
        "Summoning the beast of burden.",
        "Please don't daze me.",
        "Hops onto steed with confidence.",
        "Calls forth their land-based companion.",
        "Ground travel commencing.",
        "Mounts with practiced grace.",
        "Summons their overland transport.",
        "Ready to roam the world.",
        "Engaging speed mode.",
        "Let's hit the road in <zone>.",
        "Four hooves thundering forth.",
        "My personal carriage arrives.",
        "The beast answers the call.",
        "Saddle secured. Journey begins.",
        "No more foot travel.",
        "Transportation acquired.",
        "Journey mode: activated.",
        "Mounted and ready to explore <zone>.",
        "Stomping toward adventure.",
        "The mount emerges from shadow.",
        "Ride like the wind awaits.",
        "Sure-footed companion summoned.",
        "Let's cover some ground.",
        "The faithful steed returns.",
        "Mounted up. Distance is nothing.",
      },
    },
    {
      id = "mount_flying",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = "Summon Flying Mount" },
      messages = {
        "takes to the skies over <zone>!",
        "spreads their wings over <subzone>.",
        "summons their flying mount with a flourish in <zone>.",
        "prepares for aerial travel above <subzone>.",
        "calls down their winged companion in <zone>.",
        "Wings spread wide for adventure.",
        "Ascends toward the heavens.",
        "A flying creature emerges.",
        "Takes flight with determination.",
        "Airborne travel commencing.",
        "Ready to soar across the skies of <zone>.",
        "Engaging aerial mode.",
        "Up, up, and away from <subzone>!",
        "My kingdom for some wings.",
        "Watch me fly.",
        "The sky above <zone> awaits my presence.",
        "Flying high above the ground.",
        "Wings beating. Journey beginning.",
        "Sky travel acquired.",
        "Aerial transportation ready.",
        "Time to fly this route.",
        "Ascending gracefully.",
        "The mount rises majestically.",
        "Preparing to touch the clouds.",
        "Soaring toward <zone>.",
        "The sky over <zone> is my highway.",
        "Flying over the world below.",
        "Elevation gain: maximum.",
        "Airborne and heading out.",
      },
    },

    -- ========================================
    -- Other Activities
    -- ========================================
    {
      id = "check_mail",
      event = "MAIL_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "checks their mailbox in <zone>, hoping for a letter.",
        "opens the mailbox in <subzone>, expecting something important.",
        "rummages through the mail, looking for treasures.",
        "checks for new mail at <time>, a daily ritual.",
        "sorts through their correspondence.",
        "Checking for hate mail.",
        "Please be gold, please be gold.",
        "Postmaster again? I looted that!",
        "Spam mail in a fantasy game? Really?",
        "Collecting my auction house dividends in <zone>.",
        "Fan mail? Nope, just expired auctions.",
        "Mailbox dance initiated in <subzone>.",
        "You've got mail! (In 2004 voice).",
        "Why is the mailbox always so far away in <zone>?",
        "Sending angry letters to the RNG gods.",
        "Mail check time in <zone>. The daily grind continues.",
        "Perhaps this time there's treasure.",
        "Mailbox opens in <subzone>. Disappointment awaits.",
        "Checking correspondence.",
        "The postmaster visits again.",
        "Mail notifications: a cruel mistress.",
        "Opening: mostly junk mail.",
        "Auction house results revealed.",
        "Inbox investigation commencing at <time>.",
        "Sent items returned? Excellent.",
        "Mailbox: gateway to hope and despair.",
        "Is that gold? Probably not.",
        "Checking messages from five expansions ago.",
        "Mailbox contents: always disappointing.",
        "The postmaster knows my secrets.",
        "Mail received. Usually vendor spam.",
        "Mailbox in <zone>: where dreams go to die.",
        "Opening mail with low expectations. Still disappointed.",
        "The daily mail check ritual begins.",
        "Another round of auction House fees.",
        "Mailbox opens. Mostly cobwebs.",
        "Checking for letters of import.",
        "The mail awaits my attention.",
        "Mailbox unlocked. Contents: meh.",
        "Postal service: still overdue.",
      },
    },
    {
      id = "open_bank",
      event = "BANKFRAME_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "accesses their bank vault in <zone>.",
        "opens their personal storage in <subzone>.",
        "digs through their stashed belongings.",
        "checks their savings and stored items.",
        "visits the bank in <zone> to manage their hoard.",
        "Opening the vault at <time>.",
        "Dumping mats.",
        "Into the abyss of hoarding.",
        "Where did I put that item from three expansions ago?",
        "Visiting my frozen assets.",
        "Bag space is temporary, bank space in <zone> is... also full.",
        "Depositing my regrets.",
        "I swear I have a sorting system (I don't).",
        "Goblins charge too much interest.",
        "Safe deposit box: Accessed.",
        "Bank vault: time to organize chaos.",
        "The hoard grows larger in <zone>.",
        "Bank interface: unlocked in <subzone>.",
        "Storage solutions needed urgently.",
        "The dragon's treasure trove.",
        "Banking: separating junk from treasure.",
        "Vault contents: 80 percent vendor trash.",
        "Organized hoarding commences.",
        "Bank time: where did I put that?",
        "The deposit box welcomes me.",
        "Banking on hope and chaos.",
        "Opening: prepared for disappointment.",
        "Vaults within vaults.",
        "My financial empire displayed.",
        "Bank access: granted (with interest charges).",
        "Storing: more stuff than sense.",
        "The vault: my second home.",
        "Banking: professions hoarded.",
        "Storage optimization: failing.",
        "The deposit box awaits.",
        "Vault inspection time.",
        "Banks in <zone>: where gold goes to sleep.",
        "Organizing the carefully curated mess.",
        "Opening my treasure chest of mostly trash.",
      },
    },
    {
      id = "talk_to_vendor",
      event = "MERCHANT_SHOW",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "browses the merchant's wares in <zone>.",
        "examines the goods for sale in <subzone>.",
        "haggles with the vendor.",
        "looks for useful supplies in <zone>.",
        "considers making a purchase.",
        "Vendor: 'What can I do for you?' Me: 'Buy my trash from <zone>.'",
        "Selling gray items in <subzone>. Profit: 4 copper.",
        "Show me your wares.",
        "I am here to sell 400 gray items.",
        "Do you accept exposure as payment?",
        "Just browsing, thanks.",
        "Repair my armor, you greedy NPC in <zone>.",
        "Selling wolf tails. Don't ask where I got them.",
        "Liquidation sale in progress.",
        "Haggling protocol... failed.",
        "Vendor interaction engaged.",
        "Selling my valuables for pennies.",
        "Merchant assessment: expensive and unhelpful.",
        "Vendor wares: underwhelming.",
        "Hawking gray items for copper.",
        "The merchant's prices remain ridiculous.",
        "Browsing: looking for bargains.",
        "Vendor negotiation: imminent.",
        "Trade: one-sided economic depression.",
        "The vendor surveys my garbage.",
        "Shopping spree: curtailed by finances.",
        "Vendor window: opened with regret in <zone>.",
        "Gray items sold. Profits: negligible.",
        "The merchant calculates my worth.",
        "Selling stuff I don't need for stuff I don't need.",
        "Vendor assessment complete.",
        "Purchasing decisions: painful.",
        "The vendor marks me as predictable.",
        "Browsing goods I cannot afford.",
        "Vendor transaction: activated.",
        "Turning trash into copper.",
        "The merchant has seen better days. So have I.",
        "Shopping in <zone>: a necessary financial evil.",
        "Vendor: my best friend and worst enemy.",
        "Haggling: my specialty. His: not listening.",
      },
    },
    {
      id = "start_fishing",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 131474 }, -- Fishing
      messages = {
        "casts their line in <zone>, hoping for a bite.",
        "settles in for some peaceful fishing in <subzone>.",
        "patiently waits for a tug on the line.",
        "begins fishing in <zone>, the water looks promising.",
        "drops a line into the water.",
        "Gone fishing in <zone>. Don't text.",
        "Equipping the Pole of Patience.",
        "Time to stare at water in <subzone> for an hour.",
        "I hope I catch a mount this time.",
        "Master Angler mode: On in <zone>.",
        "Splash. Now we wait.",
        "Fish fear me. Women fear me.",
        "Relaxing... or falling asleep?",
        "Is this bait fresh? It smells like ghoul.",
        "Just one more cast in <subzone> (said ten casts ago).",
        "Fishing line: cast into destiny.",
        "Waiting for the aquatic to bite.",
        "The fishing begins in earnest.",
        "Patience activated. Actively.",
        "Water awaits my fishing expertise.",
        "Hook, line, and meditative sinker.",
        "Fishing meditation commences in <zone>.",
        "The catch awaits discovery.",
        "Line cast. Dreams await.",
        "Angler mode: fully engaged.",
        "The water calls to my fishing soul.",
        "Patience tested by boredom.",
        "Fishing rod: instrument of zen.",
        "Cast complete in <subzone>. Vibing with fish.",
        "Awaiting the ultimate catch.",
        "The pole awaits its purpose.",
        "Fish somewhere in this water.",
        "Fishing: meditation with a rod.",
        "The water keeps its secrets.",
        "Line cast toward fortune.",
        "Fishing for luck and sea creatures.",
        "Patient as stone. Well, trying.",
        "The water has spoken. Silence.",
        "Fishing in <zone>: the ultimate AFK activity.",
        "Cast. Wait. Hope.",
      },
    },
    {
      id = "cooking",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 818 }, -- Basic Campfire
      messages = {
        "starts a fire in <zone> and prepares to cook.",
        "sets up camp and lights a fire.",
        "creates a cozy campfire in <subzone>.",
        "kindles a fire for cooking.",
        "builds a campfire in <zone> with practiced hands.",
        "Cooking skill: Burnt to perfection in <zone>.",
        "Iron Chef Azeroth.",
        "Don't ask what kind of meat this is from <zone>.",
        "Adding +30 Stamina to the pot.",
        "Preparing the pre-raid buff.",
        "Burning dinner... again.",
        "Gordon Ramsay would ban me for this.",
        "Salt, pepper, and a little bit of magic dust.",
        "Great Feast incoming for <group-size> in <zone>!",
        "Cooking over an open fire (because I'm homeless).",
        "The fire roars to life in <subzone>.",
        "Culinary adventure commences.",
        "Flames rise. Cooking begins.",
        "Food preparation: initiated.",
        "The campfire awaits offerings.",
        "Cooking magic: activate.",
        "Ingredients: questionable, yet combined.",
        "Fire + random items = sustenance.",
        "The feast takes shape.",
        "Cooking: part chemistry, part luck.",
        "Flames dance around the cauldron.",
        "Pre-raid feast initiated.",
        "The pot bubbles ominously.",
        "Culinary genius or complete disaster?",
        "Cooking: my second expertise in <zone>.",
        "The campfire crackles hungrily.",
        "Food sizzles. Confidence wavers.",
        "Buff food: incoming in <zone> (probably).",
        "Cooking for the masses. Barely.",
        "Fire and food: ancient pairing.",
        "The great feast experiment.",
        "Flames lick the pot eagerly.",
        "Stamina food: inbound.",
        "Cooking with confidence. Misplaced.",
        "The campfire and I create food in <zone>.",
      },
    },
    {
      id = "hearthstone",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellID = 8690 },
      messages = {
        "channels their hearthstone, preparing to leave <zone>.",
        "activates their hearthstone in <subzone> with a nostalgic sigh.",
        "uses their hearthstone to return home from <zone>.",
        "begins the journey home from <subzone> via hearthstone.",
        "teleports back to their inn with magic.",
        "Hearthstone cast. There's no place like inn.",
        "Bubble heart? No, just heart.",
        "Clicking heels three times.",
        "Get me out of here!",
        "Hearthstone: The ultimate panic button.",
        "Homeward bound from <zone>.",
        "Please don't interrupt the cast!",
        "Setting course for the Inn.",
        "Travel time: 10 seconds. Don't hit me.",
        "Returning to sanctuary from <zone>.",
        "Hearthstone activated at <time>. Warmth incoming.",
        "Channel to home: beginning.",
        "The stone glows with purpose.",
        "Journey home commences from <subzone>.",
        "Hearthstone magic: flowing.",
        "Home calling. I answer.",
        "Portal to comfort opening.",
        "Ten seconds away from rest.",
        "The hearthstone pulses with power.",
        "Teleportation in progress from <zone>.",
        "Home: locked and loaded.",
        "Hearthstone: my life's greatest love.",
        "Channel initiated. Fingers crossed.",
        "The warm glow of home awaits.",
        "Hearthstone: functional teleportation.",
        "Home is calling my name.",
        "The stone sings to me.",
        "Casting: escape plan engaged.",
        "Hearthstone, my truest ally.",
        "The inn beckons.",
        "Home awaits beyond the veil.",
        "Preparing departure via magic.",
        "The stone glows brighter.",
        "Channeling: survival instinct active.",
        "Home: my final destination after <zone> (for now).",
      },
    },
    {
      id = "flight_path",
      event = "TAXIMAP_OPENED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "consults the flight master in <zone> about travel routes.",
        "plans their next flight path from <subzone>.",
        "examines the available flight routes from <zone>.",
        "considers where to fly next from <subzone>.",
        "speaks with the flight master.",
        "Taxi!",
        "Enjoying the scenic route (forced).",
        "Why does this flight path go in a circle?",
        "AFK for 5 minutes, flying.",
        "Gryphon Airlines: We get you there, eventually.",
        "Please keep your hands inside the beast at all times.",
        "I can see my house from here!",
        "Autopilot from <zone> to the next zone.",
        "Mid-air snack time.",
        "If I fall off over <zone>, I die. Fun.",
        "The flight master smiles knowingly.",
        "Aeronautical decisions pending.",
        "Flight path: analyzing options from <subzone>.",
        "The route home: mapped.",
        "Where shall my mount take me?",
        "Flying: the scenic route.",
        "Taxi route: consulted.",
        "The beast awaits my destination.",
        "Air travel: charted.",
        "The master of flight: consulted.",
        "Where to next, noble flyer?",
        "Flight consultation: underway.",
        "The skies call. Choose a path.",
        "Flying: the AFK transportation.",
        "The flight map: a puzzle.",
        "Destination unknown from <zone>. Excitement high.",
        "The flight awaits initiation.",
        "Gryphons: ready for duty.",
        "The master points toward destiny.",
        "Air routes: many and varied.",
        "Flying: passive income mode activated.",
        "The beast knows the way.",
        "Flight path selected from <zone>. Sit back.",
        "Air travel engaging. AFK accepted.",
        "Time to ride the skies over <zone>.",
      },
    },

    -- ========================================
    -- Vanity / Utility
    -- ========================================
    {
      id = "transmog_apply",
      event = "TRANSMOGRIFY_SUCCESS",
      cooldown = 30,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "Fashion upgraded in <zone>. Stats unchanged.",
        "New look in <subzone>. Same bad decisions.",
        "Drip check passed.",
        "I am not here to win. I am here to slay.",
        "Transmog complete in <zone>. Please admire responsibly.",
        "I just spent gold in <zone> to look incredible.",
        "Gear looks better. Performance still questionable.",
        "Endgame achieved in <zone>. Outfit perfected.",
        "I changed my look. Mechanics are next.",
        "Fresh transmog. Fresh confidence.",
        "I am now 20 percent more heroic looking.",
        "I call this one: 'Raid Ready, Emotionally Fragile.'",
        "Glamour is the true currency of Azeroth.",
        "Look good. Pull good. Probably.",
        "Do not judge my mog. Judge my DPS. Actually don't.",
        "Transmog magic: applied.",
        "Fashion transformation complete.",
        "My drip: improved substantially.",
        "Aesthetics: upgraded.",
        "Looking fierce and fabulously.",
        "Mog: now legendary status.",
        "Style points: maximized.",
        "The glam is real.",
        "Transmog success: undeniable.",
        "Outfit: now worthy of a raid.",
        "Fashion game: elevated.",
        "My mog speaks for itself.",
        "Stylin' and profilin' intensifies.",
        "The transmog gods smile upon me.",
        "Fashion: my true endgame.",
        "Looking sharp. Hitting harder? Doubtful.",
        "Transmog applied with prejudice in <subzone>.",
        "The outfit now matches my ego.",
        "Glamour enabled. Humility: optional.",
        "The mog is complete in <zone>. I am unstoppable.",
        "Fashion sense: activated.",
        "Transmog: worth every gold.",
        "My style: now undeniable.",
        "Looking good is half the battle.",
        "Transmog finished in <zone>. Ready to slay.",
      },
    },
    {
      id = "use_toy",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = { "Toy:*" } },
      messages = {
        "Deploying unnecessary fun in <zone>.",
        "Toy time in <subzone>. Productivity down. Vibes up.",
        "This is important. For morale.",
        "I am contributing to the group experience.",
        "Tactical distraction engaged in <zone>.",
        "Toy deployed in <zone>. Please pretend to be impressed.",
        "This is my raid utility. Don't question it.",
        "Serious content requires unserious behavior.",
        "I paid gold in <zone> for this. Therefore it must be used.",
        "Fun detected. Initiating chaos.",
        "I am roleplaying. Aggressively.",
        "Toy used in <subzone>. Emotional support activated.",
        "If we wipe, at least we had fun.",
        "Witness my collection of nonsense in <zone>.",
        "This is why my bags are full in <zone>.",
        "The toy is unleashed in <subzone>.",
        "Fun activated. Mechanics: optional.",
        "Toy time: because life is short.",
        "Nonsense: deployed for group morale.",
        "The toy serves a purpose.",
        "Whimsy: now active.",
        "Frivolous magic: engaged.",
        "The toy radiates joy (annoyance).",
        "Fun time: mandatory.",
        "My toy collection: put to use.",
        "Entertainment value: maximum.",
        "The toy speaks for itself.",
        "Fun is the best DPS in <zone>.",
        "This toy: worth the bag space.",
        "Enjoyment: actively seeking.",
        "The toy summons pure joy.",
        "Ridiculous: embraced fully.",
        "This item: necessary and vital.",
        "Toy: more important than gear.",
        "The toy: my greatest achievement.",
        "Fun: not optional. Mandatory.",
        "Toys: why we raid.",
        "The toy glows with potential.",
        "Nonsense intensity: elevated.",
        "This toy: priceless entertainment.",
      },
    },
  },
}

addon:RegisterPack(pack)
