-- EmoteControl - Professions Pack
-- Triggers for profession-related activities

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "professions",
  name = "Professions Pack",
  defaults = { category = "flavor", intensity = 1 },
  triggers = {
    -- Cooking Fire
    {
      id = "cooking_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Cooking Fire" },
      messages = {
        "sets up a cooking fire in <zone>, ready to prepare a feast.",
        "lights a fire in <subzone>, culinary mastery incoming.",
        "prepares to cook, Gordon Ramsay style.",
        "starts a cooking fire in <zone>, time to make something delicious.",
        "If it's black, it's done.",
        "Gordon Ramsay would yell at me.",
        "Adding 'secret spices' (it's dust).",
        "Anyone want a stat buff in <zone>?",
        "Bon appetit.",
        "Cooking weird monster meat.",
        "Making raid food.",
        "Don't stand in the fire, I'm cooking in it.",
        "Preparing a feast for <group-size> in <zone>.",
        "Smells like victory... and burnt hair.",
        "Who's hungry in <subzone>?",
        "Stoking the flames with expertise.",
        "Fire's ready for premium cuisine in <zone>.",
        "Time to work some kitchen magic.",
        "Flames dancing perfectly for cooking.",
        "This fire is hotter than my takes.",
        "Creating culinary masterpieces today.",
        "Nothing tastes better than campfire food.",
        "My cooking is legendary. Literally.",
        "Watch out, spatula wielder incoming.",
        "The smoke in <subzone> is just for flavor.",
        "Raid-ready meals about to happen.",
        "Nothing burns on my watch. Usually.",
        "Spice level: catastrophic.",
        "This feast will buff you to victory.",
        "Gathering around the warmth and food.",
        "Plate presentation is everything.",
        "My kitchen is this campfire.",
        "Seasonings unlocked and ready.",
        "Cooking fires create brotherhood.",
        "This meal deserves a five-star rating.",
        "Heat level: maximum deliciousness.",
        "Preparing something absolutely delectable.",
        "Every great hero needs sustenance.",
        "My recipes are battle-tested.",
        "Fire and food, a timeless combo.",
        "Let the feast begin soon in <zone>.",
      },
    },
    
    -- Fishing
    {
      id = "fishing_cast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      channel = "EMOTE",
      conditions = { spellName = "Fishing" },
      messages = {
        "casts their line in <zone>, waiting patiently.",
        "settles in for some peaceful fishing in <subzone>.",
        "tries their luck at fishing.",
        "casts into the water in <zone>, hoping for a big catch.",
        "Here fishy fishy.",
        "Patience is a virtue I don't have.",
        "I caught a boot.",
        "Bobber watching simulator 2026.",
        "Just one more cast in <subzone>.",
        "Is this a pool? It looks like a pool.",
        "Fishing for mounts in <zone>.",
        "Zen mode in <subzone>.",
        "Baiting the hook.",
        "Sloooosh.",
        "Old Man Pagle would be proud.",
        "The bobber is my meditation.",
        "Something's nibbling on my line.",
        "Cast and reel, the eternal rhythm.",
        "Fish are plentiful in these waters.",
        "My patience will be rewarded eventually.",
        "The water calls to me.",
        "Every cast in <zone> brings possibilities.",
        "Searching for that legendary catch.",
        "The tackle box is fully stocked.",
        "Waiting for that triumphant tug.",
        "A good fisherman knows when to strike.",
        "These waters are bountiful today.",
        "Reeling in nature's gifts.",
        "Fishing: where time disappears.",
        "The line is taut and ready.",
        "Every fish tells a story.",
        "Silent communion with the depths.",
        "The catch will make this worthwhile.",
        "My reflexes are sharp as hooks.",
        "Fishing wisdom from countless seasons.",
        "The great waters await my skill.",
        "Let's see what bites today in <subzone>.",
        "Peaceful waters inspire patient fishing.",
        "The universe provides through water.",
        "Another cast in <zone>, another chance.",
        "Hooked on fishing, always.",
      },
    },
    
    -- Archaeology Survey
    {
      id = "archaeology_survey",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      channel = "EMOTE",
      conditions = { spellName = "Survey" },
      messages = {
        "surveys the area in <zone> for ancient artifacts.",
        "searches <subzone> for archaeological treasures.",
        "investigates the ground, looking for history.",
        "uses their survey tools in <zone>, seeking the past.",
        "Digging for trash.",
        "It belongs in a museum!",
        "Survey says: Red light in <subzone>.",
        "More fragments?",
        "I hate this profession.",
        "Looking for the scope in <zone>.",
        "Triangle triangulation.",
        "Can I fly yet?",
        "Another keystone.",
        "History is buried here in <subzone>.",
        "X marks the spot.",
        "Excavating secrets from <zone>.",
        "These ruins hold untold stories.",
        "Archaeological wonders await discovery.",
        "Dust and destiny intertwined below.",
        "Ancient civilizations left their mark here.",
        "Surveying with historical precision.",
        "The scope guides my way through <zone>.",
        "Every fragment in <subzone> reveals the past.",
        "This dig site thrums with potential.",
        "History speaks through artifacts.",
        "Triangulation is my greatest tool.",
        "Uncovering secrets age-old and precious.",
        "The ground gives up its treasures.",
        "Each survey brings us closer.",
        "Archaeological magic is real.",
        "Fragments combining into knowledge.",
        "The scope spins toward destiny.",
        "This location resonates with power.",
        "We dig until we find it all.",
        "Keystones unlock historical wonders.",
        "My surveying never yields disappointment.",
        "This ruin predates kingdoms.",
        "Ancient wisdom lies beneath.",
        "Archaeology: the pursuit of timelessness.",
        "Every survey is a new revelation.",
        "History rewards the thorough scholar.",
      },
    },
    
    -- Herbalism gathering
    {
      id = "herb_gathering",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Herb Gathering" },
      messages = {
        "carefully harvests herbs in <zone>.",
        "gathers herbs in <subzone> with practiced hands.",
        "collects valuable herbs in <zone>.",
        "picks herbs in <subzone>, adding to their collection.",
        "Ooh, a piece of candy.",
        "Picking flowers in <zone> while the world ends.",
        "My allergies are flaring up.",
        "Peacebloom in <subzone>. Again.",
        "Tauren eat these, right?",
        "Lifeblood incoming.",
        "Druid in flight form beat me to it.",
        "Snip snip.",
        "Gathering mats for potions in <zone>.",
        "Don't aggro the flower.",
        "Botanist at work in <subzone>.",
        "Nature provides abundantly in <zone>.",
        "These herbs are potent and pure.",
        "The forest yields its bounty.",
        "Medicinal plants abound in this realm.",
        "Each herb serves a sacred purpose.",
        "Harvesting with reverence for life.",
        "The soil is rich with growth.",
        "Gathering remedies from nature.",
        "These petals are worth their weight.",
        "Every plant tells of ancient healing.",
        "The herbalist's work is never done.",
        "Potions start with the right plants.",
        "Roots and stems collected with care.",
        "This grove is an alchemist's paradise.",
        "Green thumbs unite us.",
        "Nature's pharmacy is open.",
        "Gathering legacy of herbcraft.",
        "These blooms are truly magnificent.",
        "The earth offers abundance freely.",
        "Stewardship of natural resources.",
        "Herbs empowered by moonlight and sun.",
        "Collecting ingredients for greatness.",
        "The garden speaks to those who listen.",
        "Every harvest strengthens future growth.",
        "Herbalism: the path of patience.",
      },
    },
    
    -- Mining
    {
      id = "mining_ore",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Mining" },
      messages = {
        "strikes the ore vein in <zone> with their pickaxe.",
        "mines ore in <subzone>, seeking valuable minerals.",
        "extracts ore from the deposit in <zone>.",
        "works the ore vein in <subzone>, pickaxe in hand.",
        "Smashing rocks.",
        "There's gold in them thar hills of <zone>.",
        "Ping! Clang! Loot!",
        "Just give me the jewel.",
        "Mining proficiency up.",
        "Rich Thorium Vein in <subzone>? Mine.",
        "My pickaxe is ready.",
        "Rock collecting.",
        "Prospecting potential.",
        "Stealing nodes in <zone>.",
        "Heavy lifting in <subzone>.",
        "The mountains of <zone> yield their treasures.",
        "Metal veins glint in the light.",
        "Swinging with all their might.",
        "Ore falls with a satisfying ring.",
        "The pickaxe knows its purpose.",
        "Deep earth reveals riches.",
        "Every strike brings reward.",
        "The vein calls to me.",
        "Gold and silver await within.",
        "Stone and strength combined.",
        "Mining is honest work.",
        "The depths are unforgiving.",
        "Ore accumulates in pockets and packs.",
        "The geological wonder unfolds.",
        "Valuable minerals are here.",
        "Extraction is an art form.",
        "These deposits are magnificent.",
        "The earth's treasures are mine.",
        "Metallic riches emerge slowly.",
        "Perseverance reveals precious ores.",
        "The vein seems endless.",
        "Rhythm and effort yield resources.",
        "Mining connects us to the earth.",
        "These ores will fuel empires.",
        "The pickaxe never tires.",
      },
    },
    
    -- Skinning
    {
      id = "skinning_beast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Skinning" },
      messages = {
        "skins the beast in <zone>, salvaging its hide.",
        "carefully removes the creature's hide in <subzone>.",
        "harvests leather from the fallen beast in <zone>.",
        "skins the corpse in <subzone> with practiced efficiency.",
        "Gross.",
        "It was dead when I got here.",
        "Leather for days in <zone>.",
        "Do I really need the intestines?",
        "Sorry, Bambi.",
        "Critter quality hide.",
        "Knife goes in, leather comes out.",
        "Skinning knife required.",
        "Waste not, want not.",
        "This smells terrible.",
        "Bag full of hides from <subzone>.",
        "The hide from <zone> is perfectly preserved.",
        "Practical butchery at its finest.",
        "Bones and sinew fall away cleanly.",
        "Quality leather from <subzone> awaits further crafting.",
        "Nothing goes to waste here.",
        "The creature contributed nobly.",
        "Leather of excellent condition obtained.",
        "Practiced hands work swiftly.",
        "The blade finds every seam.",
        "This hide will serve well.",
        "Skinning is a necessary craft.",
        "The leather pile grows larger.",
        "Beast mastery includes preparation.",
        "Quality leatherwork begins now.",
        "The hide is thick and useful.",
        "Nature provides resources and lessons.",
        "Every creature has value here.",
        "The work is messy but rewarding.",
        "Leather toughened by battle.",
        "This hide comes from a fierce beast.",
        "Masterful extraction of materials.",
        "Respect for the fallen creature.",
        "Future armor takes shape.",
        "The process yields premium leather.",
        "Skinning completes the circle.",
      },
    },
    
    -- Engineering gadgets
    {
      id = "engineering_gadget",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { spellName = "Nitro Boosts" },
      messages = {
        "Nitro Boosts! ZOOM in <zone>!",
        "Activating rocket boots in <subzone>. Hold on!",
        "Nitro engaged. Speed is life.",
        "Rocket boots firing. Wheee!",
        "This will probably explode in <zone>.",
        "Rocket boots engaged!",
        "Parachute? Check.",
        "Nitro boosts... fail.",
        "Jeeves, get the door.",
        "Wormhole generator spinning up in <subzone>.",
        "Tinkering.",
        "Safety not guaranteed in <zone>.",
        "Goblin tech best tech.",
        "It's not a bug, it's a feature.",
        "Deploying blingtron in <subzone>.",
        "Goblin engineering at its finest.",
        "Gears spinning at maximum efficiency.",
        "This contraption is brilliant.",
        "Precision engineering in action.",
        "The machine hums with power.",
        "Blueprints actualized perfectly.",
        "Technology transcends limitations.",
        "Engineering marvel completed.",
        "Mechanical genius unleashed.",
        "The gadget springs to life.",
        "Impressive craftsmanship evident.",
        "Innovation drives us forward.",
        "This device functions flawlessly.",
        "Engineering prowess demonstrated.",
        "Sparks fly with great promise.",
        "The mechanism activates smoothly.",
        "Goblin ingenuity prevails always.",
        "Technical mastery is clear.",
        "Crafted with extreme precision.",
        "The schematic comes alive.",
        "Mechanical perfection achieved today.",
        "Engineering solutions matter greatly.",
        "Tinkering transcends mere hobby.",
        "Gizmos and gadgets everywhere in <zone>.",
        "The device works as intended.",
      },
    },
    
    -- Alchemy transmute
    {
      id = "alchemy_transmute",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      channel = "EMOTE",
      conditions = { spellName = "Transmute" },
      messages = {
        "transmutes materials through alchemical mastery in <zone>.",
        "performs a transmutation in <subzone>, science and magic combined.",
        "transforms one substance into another.",
        "completes the transmutation ritual at <time>.",
        "Lead into gold in <zone>? Maybe iron.",
        "Transmute cooldown blown.",
        "Mixing volatile chemicals.",
        "Don't drink this.",
        "Flask duration extended.",
        "Proc! Please proc.",
        "Mad scientist vibes in <subzone>.",
        "Bubbling cauldron.",
        "Elixir mastery.",
        "Philosopher's Stone activated.",
        "Transmuting primal elements.",
        "The crucible glows with power.",
        "Essence merges into new forms.",
        "Alchemical reactions cascade beautifully.",
        "Transmutation defies natural law.",
        "The formula works perfectly.",
        "Potent concoctions materialize.",
        "Magical resonance builds within.",
        "Elements realign into purpose.",
        "Alchemical knowledge proves invaluable.",
        "The ritual reaches its apex.",
        "Transmutation succeeds gloriously.",
        "Essences merge in harmonious balance.",
        "The philosopher's work bears fruit.",
        "Catalysts trigger marvelous reactions.",
        "Transmutation is ancient wisdom.",
        "The cauldron sings with magic in <zone>.",
        "Creating substances of legend.",
        "Alchemy bridges worlds and elements.",
        "The reaction glows brilliantly.",
        "Transmutation transcends normal limits.",
        "Alchemical breakthrough achieved today.",
        "Purity crystallizes before us.",
        "The process concludes successfully.",
        "Essence transformation manifest now.",
        "Alchemy: where science meets mystique.",
      },
    },
    
    -- Enchanting
    {
      id = "enchanting_item",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Enchant" },
      messages = {
        "enchants the item with magical power in <zone>.",
        "imbues the equipment with arcane energy in <subzone>.",
        "applies an enchantment in <zone>, magic flowing.",
        "enhances the item through enchantment.",
        "Making it shiny in <subzone>.",
        "Disenchanting your hopes and dreams.",
        "Dust to dust.",
        "Vellum prepared.",
        "Glow effect added.",
        "That will be 50 gold in <zone>.",
        "Enchanting weapon: Beast slaying (oops).",
        "Magic sparkles.",
        "Replacing the weak enchantment.",
        "Power overwhelming.",
        "Strange dust everywhere.",
        "The equipment glimmers with power.",
        "Arcane threads bind to the item.",
        "Enchantment infuses brilliantly.",
        "Magical resonance strengthens vastly.",
        "Runes align in perfect harmony.",
        "The enchantment takes hold firmly.",
        "Arcane energy courses through.",
        "Enhancement radiates from the gear.",
        "The weave strengthens the whole.",
        "Magical infusion complete smoothly.",
        "Enchantment transcends ordinary gear.",
        "Power amplifies exponentially now.",
        "The item responds to magic.",
        "Arcane mastery evident in <subzone>.",
        "Enchanted and ready for battle.",
        "The magical enhancement glistens.",
        "Channeling pure arcane force.",
        "Spellwork culminates perfectly.",
        "The item blazes with mystique.",
        "Enhancement bonds eternally strong.",
        "Arcane infusion proves successful.",
        "Magical threads intertwine tightly.",
        "The enchantment holds magnificently.",
        "Power imbued at deepest levels.",
        "Arcane artistry perfected today.",
      },
    },
    
    -- Disenchanting
    {
      id = "disenchant_item",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Disenchant" },
      messages = {
        "Converting loot into sparkly dust in <zone>.",
        "Disenchanting. This item is now a suggestion.",
        "Turning gear into regret powder in <subzone>.",
        "Breaking down value into components.",
        "Shattering dreams into shards in <zone>.",
        "This is not destruction. It's recycling.",
        "Dust farming in <subzone>. Professionally.",
        "Disenchant complete. It never stood a chance.",
        "Goodbye item in <zone>. Hello materials.",
        "I am reducing this to atoms.",
        "Loot? No. Ingredients.",
        "Crushing gear into glitter.",
        "Turning purple into powder in <subzone>.",
        "The real loot is the dust we made along the way.",
        "Disenchanting. The circle of life.",
        "Unraveling enchantments methodically.",
        "Essence dissipates into essence dust.",
        "The magic unweaves completely.",
        "Arcane bonds dissolve gracefully.",
        "Breaking down becomes renewal.",
        "Components scatter into usable form.",
        "The spell dissolves into motes.",
        "Energy returns to its base elements.",
        "Disenchantment reveals hidden essence.",
        "The item yields its secrets.",
        "Magical threads unravel smoothly.",
        "From whole comes many parts.",
        "Deconstruction proves profitable.",
        "Enchantment reverses before me.",
        "The gear becomes constituent parts.",
        "Recycling magic into new forms.",
        "Dust accumulates in endless piles.",
        "Every item offers valuable essence.",
        "Unmaking is its own art.",
        "The disenchantment glows brightly in <zone>.",
        "Breaking apart grants enlightenment.",
        "Materials emerge from remnants.",
        "Essence coalesces from dispersion.",
        "The magic finds new purpose.",
        "Disenchantment completes the cycle.",
      },
    },
    
    -- Inscription
    {
      id = "inscription_glyph",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Inscription" },
      messages = {
        "carefully inscribes mystical symbols in <zone>.",
        "creates a glyph in <subzone> with precise strokes.",
        "works on their inscription in <zone>, art and magic.",
        "inscribes runes with practiced skill.",
        "Milling herbs.",
        "Paper cuts are lethal in <subzone>.",
        "Writing scrolls.",
        "Glyph of cosmetic uselessness.",
        "Ink on my fingers.",
        "Darkmoon Card crafted in <zone>.",
        "Shoulder enchants here.",
        "Forging documents.",
        "Pigment grinding.",
        "Staff crafting.",
        "Scroll of Recall.",
        "The quill flows with precision in <subzone>.",
        "Symbols align with power.",
        "Calligraphy meets arcane knowledge.",
        "Runes glow with purpose.",
        "The parchment receives the design.",
        "Inscribed with ancient wisdom.",
        "Each stroke matters greatly.",
        "Glyph components coalesce perfectly.",
        "The inscription shimmers subtly.",
        "Spellcraft rendered in written form.",
        "The scribe's art comes alive.",
        "Mystical marks bind power.",
        "Inscription magic flows freely.",
        "Parchment transformed into purpose.",
        "The glyph activates silently.",
        "Script weaves together seamlessly.",
        "Magical words hold true power.",
        "The inscription resonates deeply in <zone>.",
        "Runes bind together eternally.",
        "Parchment becomes conduit of force.",
        "Glyphs enhance capabilities vastly.",
        "The written word holds power.",
        "Inscription represents arcane mastery.",
        "Symbols transform written into powerful.",
        "The scribe's legacy endures.",
      },
    },
    
    -- Milling
    {
      id = "milling_herbs",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Milling" },
      messages = {
        "Grinding herbs into art supplies in <zone>.",
        "Milling herbs in <subzone>. Turning plants into pigment.",
        "Pulverizing leaves for profit in <zone>.",
        "Reducing flowers into paint. Like a professional.",
        "Milling complete in <subzone>. My hands are green now.",
        "Pigment production engaged.",
        "Herbal smoothie. Do not drink it.",
        "Turning herbs into ink fuel.",
        "I am an artist. With a mortar and pestle.",
        "Milling. Because normal crafting is too easy.",
        "Flour? No. Pigment.",
        "Crushing herbs into colorful disappointment.",
        "Ink factory online in <zone>.",
        "Milling in <subzone>. Please ignore the cloud of dust.",
        "This is basically magical gardening.",
        "The mortar grinds steadily forward in <zone>.",
        "Herbs transform into fine powder.",
        "Pigment yields from botanical matter.",
        "Grinding releases fragrant essence.",
        "The pestle crushes with expertise.",
        "Botanical reduction nears completion.",
        "Colorful powders accumulate abundantly.",
        "The milling process proves efficient.",
        "Herbs surrender to the grindstone.",
        "Pigment quality surpasses expectations.",
        "The mill spins with purpose.",
        "Botanical transformation yields richly.",
        "Fine powder emerges constantly.",
        "Milling produces inscription ink.",
        "The herbs break down completely.",
        "Powdered pigments glow brightly.",
        "Grinding is meditative work.",
        "Colorful dust clouds billow upward in <subzone>.",
        "Each batch improves artistry.",
        "The mortar knows its purpose.",
        "Crushing herbs creates beauty.",
        "Pigment production never ceases.",
        "The milling journey continues onward.",
        "Botanical resources multiply usefulness.",
        "Milling: where nature meets art.",
      },
    },
    
    -- Jewelcrafting
    {
      id = "jewelcrafting_gem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Jewelcrafting" },
      messages = {
        "cuts and polishes a precious gem in <zone>.",
        "crafts jewelry in <subzone> with expert precision.",
        "works the gem in <zone>, revealing its beauty.",
        "shapes the gemstone into perfection.",
        "Cutting glass.",
        "Shiny rocks from <subzone>!",
        "Socket to me.",
        "Prospecting ore stacks.",
        "Perfect cut in <zone>.",
        "Prismatic quality.",
        "Necklace crafting.",
        "Ring crafting.",
        "Gem of +20 stat.",
        "It sparkles in <subzone>.",
        "Jeweler's loupe equipped.",
        "Facets align with perfect angles.",
        "The stone reveals hidden brilliance.",
        "Gemcraft transcends mere material in <zone>.",
        "Precious stones respond to mastery.",
        "The cutting edge shapes destiny.",
        "Jewelry radiates refined elegance.",
        "Each gem tells of deep earth.",
        "Polished to impossible perfection.",
        "The jeweler's eye guides hands.",
        "Gemstones yield to expertise.",
        "Craftsmanship shines through brightly.",
        "The setting secures treasure.",
        "Jewels enhance strength immeasurably.",
        "The cut multiplies radiance.",
        "Precious work requires patience.",
        "Each facet reflects light beautifully.",
        "Gems glow with inner fire.",
        "The jewelry transforms wearers.",
        "Gemcraft is ancient art.",
        "Stones become instruments of power.",
        "The jeweler's skill never falters.",
        "Precious gems reshape destinies.",
        "Cutting reveals inherent majesty.",
        "The jewelry enhances natural gifts.",
        "Gemcraft connects earth to bearer.",
      },
    },
    
    -- Prospecting
    {
      id = "prospecting_ore",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Prospecting" },
      messages = {
        "Prospecting ore in <zone>. Gambling for shiny rocks.",
        "Crushing ore in <subzone> into potential.",
        "Let's see what the rocks in <zone> are hiding.",
        "Prospecting. This is how I get my serotonin.",
        "Ore from <subzone> goes in. Gems come out. Hopefully.",
        "I am turning rocks into jewelry. Science.",
        "Prospecting engaged in <zone>. RNG, be kind.",
        "Shaking ore until gems fall out.",
        "Smashing rocks for sparkles.",
        "I swear this is a profession.",
        "Prospecting in <subzone>. This is my casino.",
        "If I get another green gem, I will cry.",
        "Ore processing in <zone>. Glitter extraction.",
        "I have become a gem gremlin.",
        "Prospecting complete. My bags are worse now.",
        "Ore shatters under careful pressure.",
        "Gems materialize from broken stone.",
        "The prospecting yields treasures.",
        "Minerals sparkle within the fragments.",
        "Breaking ore reveals gems within.",
        "The process yields colored stones.",
        "Prospecting transforms raw ore.",
        "Gems hide inside each ore sample.",
        "The hammer strikes with precision.",
        "Ore fragments scatter everywhere.",
        "Gemstones emerge from the broken rock.",
        "Prospecting is hopeful work.",
        "Each sample holds potential.",
        "The ores surrender their secrets.",
        "Gems await discovery within.",
        "Prospecting rewards patience.",
        "The shattered ore yields wealth.",
        "Minerals scatter across the table.",
        "This batch from <subzone> looks particularly promising.",
        "Gems dance in the broken pieces.",
        "Prospecting fuels the gathering.",
        "The ore breaks open with promise.",
        "Colored stones emerge beautifully.",
        "Prospecting completes the cycle.",
        "Gems await their next purpose.",
      },
    },
    
    -- Leatherworking
    {
      id = "leatherworking_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Leatherworking" },
      messages = {
        "crafts leather armor in <zone> with skill.",
        "works the leather into useful gear in <subzone>.",
        "creates leatherwork in <zone>, sturdy and reliable.",
        "fashions leather into equipment.",
        "Stitching hides.",
        "Drums of War!",
        "Armor kits ready.",
        "Making mail armor.",
        "Pattern learned.",
        "Need more heavy leather from <subzone>.",
        "Curing salt.",
        "Leg enchants.",
        "Beast mastery set.",
        "Sewing machine sounds.",
        "Crafting cape in <zone>.",
        "The leather from <subzone> responds to skilled hands.",
        "Armor takes shape under careful work.",
        "Leathercraft creates protection.",
        "Stitches hold together perfectly.",
        "The armor strengthens its wearer.",
        "Leather becomes equipment of legend.",
        "Craftsmanship marks every piece.",
        "The gear provides reliable defense.",
        "Leatherwork demonstrates true skill.",
        "Each stitch reinforces durability.",
        "Armor crafted for champions in <zone>.",
        "The leather bends to purpose.",
        "Combat-ready gear emerges.",
        "Leatherworking requires strength.",
        "The armor glistens with quality.",
        "Protective gear takes final form.",
        "Leather strengthens through craft.",
        "The equipment stands ready.",
        "Leatherwork connects past heroes.",
        "Armor shields its wearer well.",
        "The craft produces lasting quality.",
        "Leather items enhance capabilities.",
        "Gear worthy of proud bearing.",
        "Leatherworking: ancient protective art.",
        "The armor will serve faithfully.",
      },
    },
    
    -- Tailoring
    {
      id = "tailoring_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Tailoring" },
      messages = {
        "sews cloth into fine garments in <zone>.",
        "tailors fabric in <subzone> with expert hands.",
        "creates cloth armor in <zone>, thread and needle.",
        "weaves cloth into useful equipment.",
        "Weaving cloth.",
        "Bags! Everyone needs bags.",
        "Flying carpet weaving.",
        "Need more cloth drops in <subzone>.",
        "Embroidery.",
        "Spellthread.",
        "Making a robe in <zone>.",
        "Bolt of linen.",
        "Scissors and thread.",
        "Fashion designer.",
        "Shirt crafting.",
        "The needle guides fabric in <subzone> into form.",
        "Cloth transforms under expert hands.",
        "Tailoring creates elegant wear.",
        "Threads interweave into garments.",
        "The fabric yields to the craft.",
        "Tailored robes shimmer beautifully.",
        "Each stitch shows expertise.",
        "The garment fits perfectly.",
        "Cloth becomes spellwoven armor.",
        "Tailoring demonstrates artistry.",
        "The needle moves with precision.",
        "Fabric becomes protective gear.",
        "Tailorwork requires steady hands.",
        "The robes hang with grace.",
        "Equipment emerges thread by thread.",
        "Cloth strengthened through skill.",
        "The garment protects elegantly.",
        "Tailoring connects form and function.",
        "Robes enhance magical potential in <zone>.",
        "The craft produces wearable art.",
        "Fabric items enhance wearer.",
        "Gear worthy of royal bearing.",
        "Tailoring: textile protection mastery.",
        "The garment will endure battles.",
        "Thread and skill bind together.",
      },
    },
    
    -- Blacksmithing
    {
      id = "blacksmithing_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Blacksmithing" },
      messages = {
        "hammers metal at the forge in <zone>.",
        "smiths equipment in <subzone> with fire and steel.",
        "forges metal into useful gear in <zone>.",
        "works the anvil, sparks flying.",
        "Hammer and anvil.",
        "Striking while the iron is hot in <subzone>.",
        "Plate armor incoming.",
        "Sharpening stone.",
        "Weapon smithing.",
        "Armorsmithing.",
        "Adding a belt buckle.",
        "Skeleton keys.",
        "Forging steel in <zone>.",
        "Heat treatment.",
        "Folded steel.",
        "The forge roars with intensity in <subzone>.",
        "Metal glows in the heat.",
        "Blacksmithing creates legendary gear.",
        "The hammer rings true and strong.",
        "Steel takes shape under the blow.",
        "Armor emerges from burning coals.",
        "Craftsmanship forged in fire.",
        "The metal bends to will.",
        "Equipment ready for warriors.",
        "Blacksmithing demonstrates mastery.",
        "The hammer never missteps.",
        "Metal becomes protective plate.",
        "The forge breathes mighty heat.",
        "The armor gleams with quality.",
        "Weapons emerge sharp and true in <zone>.",
        "Metal strengthened through craft.",
        "The equipment stands ready.",
        "Blacksmithing ancient noble art.",
        "Plate armor shields its wearer.",
        "The craft produces enduring works.",
        "Steel items enhance warrior.",
        "Gear worthy of legendary bearing.",
        "Blacksmithing: metal mastery.",
        "The armor will endure ages.",
        "Fire and skill forge greatness.",
      },
    },
    
    -- Soulwell (Warlock)
    {
      id = "soulwell",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "WARLOCK", spellName = "Create Soulwell" },
      messages = {
        "Soulwell deployed in <instanceName>. Healthstones for everyone!",
        "Creating a Soulwell in <zone>. Grab your stones.",
        "Soulwell up in <instanceName>. Click it before we pull.",
        "Healthstones available in <zone>. You're welcome.",
        "Get your cookies.",
        "Healthstones here.",
        "Click the portal.",
        "Green candy.",
        "Don't forget to eat it.",
        "Warlock vending machine in <subzone>.",
        "Soul shards consumed at <time>.",
        "It tastes like fel.",
        "One per customer.",
        "Life saving rocks.",
        "Ritual of Souls.",
        "Soulwell appears in <instanceName> before you.",
        "Healthstones materialize gloriously.",
        "Soul magic sustains your allies.",
        "The well glows with green power.",
        "Healthstones await consumption.",
        "The soulwell strengthens your <group-size> allies.",
        "Everyone gains health reserves.",
        "Warlock's gift manifests here.",
        "Stones pulse with vital energy.",
        "The portal steadies your group.",
        "Healthstones provided generously in <zone>.",
        "Soul sacrifice sustains comrades.",
        "The soulwell binds allies.",
        "Stones grant resilience vastly.",
        "The ritual completes successfully in <instanceName>.",
        "Healthstone magic flows freely.",
        "The well sustains without ceasing.",
        "Soul energy stabilizes everything.",
        "Stones connect to warlock power.",
        "The soulwell protects all.",
        "Healthstones empower recovery.",
        "The ritual bonds companions.",
        "Stones preserve precious lives.",
        "The soulwell proves invaluable.",
        "Healthstones grant peace of mind.",
      },
    },
    
    -- Refreshment Table (Mage)
    {
      id = "refreshment_table",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "MAGE", spellName = "Conjure Refreshment Table" },
      messages = {
        "Refreshment Table conjured in <instanceName>. Eat up!",
        "Food and water available in <zone>. Buffet's open.",
        "Conjured a feast for <group-size>. Help yourselves.",
        "Table's ready in <subzone>. Mage catering service.",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up in <instanceName>. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the <group-size> in <instanceName>.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
        "The table appears in <zone> before you.",
        "Conjured delicacies await tasting.",
        "Mage sustenance magic activates.",
        "The table glows with abundance.",
        "Food materializes at your feet.",
        "The feast strengthens your <group-size> allies.",
        "Everyone gains nourishment.",
        "Mage's gift manifests here.",
        "Sustenance pulses with mana.",
        "The table steadies your party.",
        "Refreshments provided generously in <zone>.",
        "Arcane sacrifice sustains comrades.",
        "The table binds allies together.",
        "Food grants resilience vastly.",
        "The conjuration completes successfully at <time>.",
        "Mana food flows freely.",
        "The table sustains without ceasing.",
        "Arcane energy revitalizes everything.",
        "Food connects to mage power.",
        "The table protects all.",
        "Refreshments empower recovery.",
        "The ritual bonds companions.",
        "Food preserves precious energies.",
        "The table proves invaluable.",
        "Refreshments grant peace of mind.",
      },
    },
  },
})
