-- EmoteControl - Professions Pack
-- Triggers for profession-related activities

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "professions",
  name = "Professions Pack",
  defaults = { category = "flavor", intensity = 1 },
  triggers = {
    -- Cooking Fire
    {
      id = "cooking_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Cooking Fire" },
      messages = {
        "sets up a cooking fire, ready to prepare a feast.",
        "lights a fire, culinary mastery incoming.",
        "prepares to cook, Gordon Ramsay style.",
        "starts a cooking fire, time to make something delicious.",
        "If it's black, it's done.",
        "Gordon Ramsay would yell at me.",
        "Adding 'secret spices' (it's dust).",
        "Anyone want a stat buff?",
        "Bon appetit.",
        "Cooking weird monster meat.",
        "Making raid food.",
        "Don't stand in the fire, I'm cooking in it.",
        "Preparing a feast.",
        "Smells like victory... and burnt hair.",
        "Who's hungry?",
      },
    },
    
    -- Fishing
    {
      id = "fishing_cast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      channel = "EMOTE",
      conditions = { spellName = "Fishing" },
      messages = {
        "casts their line, waiting patiently.",
        "settles in for some peaceful fishing.",
        "tries their luck at fishing.",
        "casts into the water, hoping for a big catch.",
        "Here fishy fishy.",
        "Patience is a virtue I don't have.",
        "I caught a boot.",
        "Bobber watching simulator 2026.",
        "Just one more cast.",
        "Is this a pool? It looks like a pool.",
        "Fishing for mounts.",
        "Zen mode.",
        "Baiting the hook.",
        "Sloooosh.",
        "Old Man Pagle would be proud.",
      },
    },
    
    -- Archaeology Survey
    {
      id = "archaeology_survey",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      channel = "EMOTE",
      conditions = { spellName = "Survey" },
      messages = {
        "surveys the area for ancient artifacts.",
        "searches for archaeological treasures.",
        "investigates the ground, looking for history.",
        "uses their survey tools, seeking the past.",
        "Digging for trash.",
        "It belongs in a museum!",
        "Survey says: Red light.",
        "More fragments?",
        "I hate this profession.",
        "Looking for the scope.",
        "Triangle triangulation.",
        "Can I fly yet?",
        "Another keystone.",
        "History is buried here.",
        "X marks the spot.",
      },
    },
    
    -- Herbalism gathering
    {
      id = "herb_gathering",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Herb Gathering" },
      messages = {
        "carefully harvests herbs from the ground.",
        "gathers herbs with practiced hands.",
        "collects valuable herbs.",
        "picks herbs, adding to their collection.",
        "Ooh, a piece of candy.",
        "Picking flowers while the world ends.",
        "My allergies are flaring up.",
        "Peacebloom. Again.",
        "Tauren eat these, right?",
        "Lifeblood incoming.",
        "Druid in flight form beat me to it.",
        "Snip snip.",
        "Gathering mats for potions.",
        "Don't aggro the flower.",
        "Botanist at work.",
      },
    },
    
    -- Mining
    {
      id = "mining_ore",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Mining" },
      messages = {
        "strikes the ore vein with their pickaxe.",
        "mines ore, seeking valuable minerals.",
        "extracts ore from the deposit.",
        "works the ore vein, pickaxe in hand.",
        "Smashing rocks.",
        "There's gold in them thar hills.",
        "Ping! Clang! Loot!",
        "Just give me the jewel.",
        "Mining proficiency up.",
        "Rich Thorium Vein? Mine.",
        "My pickaxe is ready.",
        "Rock collecting.",
        "Prospecting potential.",
        "Stealing nodes.",
        "Heavy lifting.",
      },
    },
    
    -- Skinning
    {
      id = "skinning_beast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      channel = "EMOTE",
      conditions = { spellName = "Skinning" },
      messages = {
        "skins the beast, salvaging its hide.",
        "carefully removes the creature's hide.",
        "harvests leather from the fallen beast.",
        "skins the corpse with practiced efficiency.",
        "Gross.",
        "It was dead when I got here.",
        "Leather for days.",
        "Do I really need the intestines?",
        "Sorry, Bambi.",
        "Critter quality hide.",
        "Knife goes in, leather comes out.",
        "Skinning knife required.",
        "Waste not, want not.",
        "This smells terrible.",
        "Bag full of hides.",
      },
    },
    
    -- Engineering gadgets
    {
      id = "engineering_gadget",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { spellName = "Nitro Boosts" },
      messages = {
        "Nitro Boosts! ZOOM!",
        "Activating rocket boots. Hold on!",
        "Nitro engaged. Speed is life.",
        "Rocket boots firing. Wheee!",
        "This will probably explode.",
        "Rocket boots engaged!",
        "Parachute? Check.",
        "Nitro boosts... fail.",
        "Jeeves, get the door.",
        "Wormhole generator spinning up.",
        "Tinkering.",
        "Safety not guaranteed.",
        "Goblin tech best tech.",
        "It's not a bug, it's a feature.",
        "Deploying blingtron.",
      },
    },
    
    -- Alchemy transmute
    {
      id = "alchemy_transmute",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      channel = "EMOTE",
      conditions = { spellName = "Transmute" },
      messages = {
        "transmutes materials through alchemical mastery.",
        "performs a transmutation, science and magic combined.",
        "transforms one substance into another.",
        "completes the transmutation ritual.",
        "Lead into gold? Maybe iron.",
        "Transmute cooldown blown.",
        "Mixing volatile chemicals.",
        "Don't drink this.",
        "Flask duration extended.",
        "Proc! Please proc.",
        "Mad scientist vibes.",
        "Bubbling cauldron.",
        "Elixir mastery.",
        "Philosopher's Stone activated.",
        "Transmuting primal elements.",
      },
    },
    
    -- Enchanting
    {
      id = "enchanting_item",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Enchant" },
      messages = {
        "enchants the item with magical power.",
        "imbues the equipment with arcane energy.",
        "applies an enchantment, magic flowing.",
        "enhances the item through enchantment.",
        "Making it shiny.",
        "Disenchanting your hopes and dreams.",
        "Dust to dust.",
        "Vellum prepared.",
        "Glow effect added.",
        "That will be 50 gold.",
        "Enchanting weapon: Beast slaying (oops).",
        "Magic sparkles.",
        "Replacing the weak enchantment.",
        "Power overwhelming.",
        "Strange dust everywhere.",
      },
    },
    
    -- Disenchanting
    {
      id = "disenchant_item",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Disenchant" },
      messages = {
        "Converting loot into sparkly dust.",
        "Disenchanting. This item is now a suggestion.",
        "Turning gear into regret powder.",
        "Breaking down value into components.",
        "Shattering dreams into shards.",
        "This is not destruction. It's recycling.",
        "Dust farming. Professionally.",
        "Disenchant complete. It never stood a chance.",
        "Goodbye item. Hello materials.",
        "I am reducing this to atoms.",
        "Loot? No. Ingredients.",
        "Crushing gear into glitter.",
        "Turning purple into powder.",
        "The real loot is the dust we made along the way.",
        "Disenchanting. The circle of life.",
      },
    },
    
    -- Inscription
    {
      id = "inscription_glyph",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Inscription" },
      messages = {
        "carefully inscribes mystical symbols.",
        "creates a glyph with precise strokes.",
        "works on their inscription, art and magic.",
        "inscribes runes with practiced skill.",
        "Milling herbs.",
        "Paper cuts are lethal.",
        "Writing scrolls.",
        "Glyph of cosmetic uselessness.",
        "Ink on my fingers.",
        "Darkmoon Card crafted.",
        "Shoulder enchants here.",
        "Forging documents.",
        "Pigment grinding.",
        "Staff crafting.",
        "Scroll of Recall.",
      },
    },
    
    -- Milling
    {
      id = "milling_herbs",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Milling" },
      messages = {
        "Grinding herbs into art supplies.",
        "Milling herbs. Turning plants into pigment.",
        "Pulverizing leaves for profit.",
        "Reducing flowers into paint. Like a professional.",
        "Milling complete. My hands are green now.",
        "Pigment production engaged.",
        "Herbal smoothie. Do not drink it.",
        "Turning herbs into ink fuel.",
        "I am an artist. With a mortar and pestle.",
        "Milling. Because normal crafting is too easy.",
        "Flour? No. Pigment.",
        "Crushing herbs into colorful disappointment.",
        "Ink factory online.",
        "Milling. Please ignore the cloud of dust.",
        "This is basically magical gardening.",
      },
    },
    
    -- Jewelcrafting
    {
      id = "jewelcrafting_gem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Jewelcrafting" },
      messages = {
        "cuts and polishes a precious gem.",
        "crafts jewelry with expert precision.",
        "works the gem, revealing its beauty.",
        "shapes the gemstone into perfection.",
        "Cutting glass.",
        "Shiny rocks!",
        "Socket to me.",
        "Prospecting ore stacks.",
        "Perfect cut.",
        "Prismatic quality.",
        "Necklace crafting.",
        "Ring crafting.",
        "Gem of +20 stat.",
        "It sparkles.",
        "Jeweler's loupe equipped.",
      },
    },
    
    -- Prospecting
    {
      id = "prospecting_ore",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Prospecting" },
      messages = {
        "Prospecting ore. Gambling for shiny rocks.",
        "Crushing ore into potential.",
        "Let's see what the rocks are hiding.",
        "Prospecting. This is how I get my serotonin.",
        "Ore goes in. Gems come out. Hopefully.",
        "I am turning rocks into jewelry. Science.",
        "Prospecting engaged. RNG, be kind.",
        "Shaking ore until gems fall out.",
        "Smashing rocks for sparkles.",
        "I swear this is a profession.",
        "Prospecting. This is my casino.",
        "If I get another green gem, I will cry.",
        "Ore processing. Glitter extraction.",
        "I have become a gem gremlin.",
        "Prospecting complete. My bags are worse now.",
      },
    },
    
    -- Leatherworking
    {
      id = "leatherworking_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Leatherworking" },
      messages = {
        "crafts leather armor with skill.",
        "works the leather into useful gear.",
        "creates leatherwork, sturdy and reliable.",
        "fashions leather into equipment.",
        "Stitching hides.",
        "Drums of War!",
        "Armor kits ready.",
        "Making mail armor.",
        "Pattern learned.",
        "Need more heavy leather.",
        "Curing salt.",
        "Leg enchants.",
        "Beast mastery set.",
        "Sewing machine sounds.",
        "Crafting cape.",
      },
    },
    
    -- Tailoring
    {
      id = "tailoring_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Tailoring" },
      messages = {
        "sews cloth into fine garments.",
        "tailors fabric with expert hands.",
        "creates cloth armor, thread and needle.",
        "weaves cloth into useful equipment.",
        "Weaving cloth.",
        "Bags! Everyone needs bags.",
        "Flying carpet weaving.",
        "Need more cloth drops.",
        "Embroidery.",
        "Spellthread.",
        "Making a robe.",
        "Bolt of linen.",
        "Scissors and thread.",
        "Fashion designer.",
        "Shirt crafting.",
      },
    },
    
    -- Blacksmithing
    {
      id = "blacksmithing_craft",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      channel = "EMOTE",
      conditions = { spellName = "Blacksmithing" },
      messages = {
        "hammers metal at the forge.",
        "smiths equipment with fire and steel.",
        "forges metal into useful gear.",
        "works the anvil, sparks flying.",
        "Hammer and anvil.",
        "Striking while the iron is hot.",
        "Plate armor incoming.",
        "Sharpening stone.",
        "Weapon smithing.",
        "Armorsmithing.",
        "Adding a belt buckle.",
        "Skeleton keys.",
        "Forging steel.",
        "Heat treatment.",
        "Folded steel.",
      },
    },
    
    -- Soulwell (Warlock)
    {
      id = "soulwell",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "WARLOCK", spellName = "Create Soulwell" },
      messages = {
        "Soulwell deployed. Healthstones for everyone!",
        "Creating a Soulwell. Grab your stones.",
        "Soulwell up. Click it before we pull.",
        "Healthstones available. You're welcome.",
        "Get your cookies.",
        "Healthstones here.",
        "Click the portal.",
        "Green candy.",
        "Don't forget to eat it.",
        "Warlock vending machine.",
        "Soul shards consumed.",
        "It tastes like fel.",
        "One per customer.",
        "Life saving rocks.",
        "Ritual of Souls.",
      },
    },
    
    -- Refreshment Table (Mage)
    {
      id = "refreshment_table",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "MAGE", spellName = "Conjure Refreshment Table" },
      messages = {
        "Refreshment Table conjured. Eat up!",
        "Food and water available. Buffet's open.",
        "Conjured a feast. Help yourselves.",
        "Table's ready. Mage catering service.",
        "Vending machine mode: Active.",
        "Get your mana buns here!",
        "Free food! (Tips appreciated).",
        "Conjuring strudel.",
        "Eat up, I'm not making more.",
        "Table is up. Click it.",
        "Magic food contains 0 calories.",
        "Sustenance for the raid.",
        "I am a glorified chef.",
        "Don't ignore the table.",
        "Refreshment ritual started.",
      },
    },
  },
})
