-- EmoteControl - Death Knight Pack

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

-- Design notes:
-- - Uses spellName so the core can resolve IDs at runtime.
-- - Cooldowns are intentionally higher for rotational spells to avoid spam.

EmoteControl:RegisterPack({
  id = "deathknight",
  name = "Death Knight Pack",
  triggers = {
    -- Emote flavor triggers
    {
      id = "dk_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      conditions = { class = "DEATHKNIGHT", unit = "player" },
      messages = {
        "unsheathes their runeblade, frost and death awakening.",
        "calls upon unholy power, ready to rend.",
        "enters combat with grim determination.",
        "channels the power of the Lich King.",
        "prepares to spread death and decay.",
      },
    },
    {
      id = "dk_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      conditions = { class = "DEATHKNIGHT", unit = "player" },
      messages = {
        "sheathes their runeblade, death satisfied.",
        "stands among fallen foes, victorious.",
        "nods coldly, another soul claimed.",
        "relaxes their grip, the reaping complete.",
        "stands firm, death eternal.",
      },
    },

    -- Utility / Control
    {
      id = "dk_death_grip",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Death Grip" },
      messages = {
        "Death Grip. Come here and regret it.",
        "<target>, your personal space has been revoked.",
        "Yoink. The Ebon Blade sends its regards.",
        "I brought you closer so we can have a meaningful argument.",
        "Gravity is a suggestion. I am the policy.",
        "Acherus says: get over here.",
        "If Midnight brings shadows, I bring traction.",
        "You were over there. That was a mistake.",
      },
    },
    {
      id = "dk_mind_freeze",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 8,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Mind Freeze" },
      messages = {
        "Mind Freeze. Thoughts cancelled.",
        "Shhh. No more spells. Only silence.",
        "Your cast has been declined by necromantic customer support.",
        "That incantation was going somewhere embarrassing. I stopped it.",
        "Spell interrupted. Ego next.",
        "The runeblade says no.",
        "Void whispers can wait. You're done talking.",
        "I have applied a mandatory quiet moment.",
      },
    },
    {
      id = "dk_chains_of_ice",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Chains of Ice" },
      messages = {
        "Chains of Ice. Running is no longer a lifestyle.",
        "<target>, your mobility subscription has expired.",
        "Hold still. The cold has opinions.",
        "I brought winter in a convenient chain format.",
        "Slow down. I am trying to look menacing.",
        "Consider this a polite reminder to stop.",
        "Midnight can keep its darkness. I brought the chill.",
        "You are now speed-limited by decree.",
      },
    },
    {
      id = "dk_asphyxiate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Asphyxiate" },
      messages = {
        "Asphyxiate. Please pause all activities.",
        "Time out, <target>.",
        "I have scheduled your breathing for later.",
        "Hold that thought. And everything else.",
        "Stunned. For your own personal growth.",
        "Your freedom has been temporarily archived.",
        "If the Void is choking the Sunwell, I can multitask.",
        "Silence and stillness. Nice look on you.",
      },
    },

    -- Defensives / Survival
    {
      id = "dk_anti_magic_shell",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Anti-Magic Shell" },
      messages = {
        "Anti-Magic Shell. Your spells are now decorative.",
        "Magic? In this economy? Not on me.",
        "Arcane nonsense detected. Firewall deployed.",
        "Your sorcery has been redirected to the trash.",
        "If Midnight brings Void magic, I brought receipts.",
        "Absorbing spells like it's a hobby.",
        "This is my 'no thank you' bubble.",
        "Shell up. Let the casters cope.",
      },
    },
    {
      id = "dk_icebound_fortitude",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Icebound Fortitude" },
      messages = {
        "Icebound Fortitude. I have become difficult.",
        "Pain is temporary. Spite is permanent.",
        "Fortitude online. Please submit damage in writing.",
        "I am now sturdier than your plans.",
        "If the Void tries to break me, it can take a number.",
        "I am a problem with armor.",
        "Icebound. Unbothered.",
        "Your burst window just became a suggestion.",
      },
    },
    {
      id = "dk_lichborne",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Lichborne" },
      messages = {
        "Lichborne. Mortality status: optional.",
        "I have entered my spooky era.",
        "Fear effects are now unpaid interns.",
        "Behold: undead confidence.",
        "The Light looks away. I do not.",
        "If Midnight is about darkness, I'm ahead of schedule.",
        "Lichborne engaged. Please admire the vibes.",
        "I am technically alive enough.",
      },
    },
    {
      id = "dk_death_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Death Strike" },
      messages = {
        "Death Strike. I paid for that health in violence.",
        "Borrowed life returned with interest.",
        "Your damage has been converted into my confidence.",
        "Siphon successful. Thank you for your contribution.",
        "I hit you, I heal me. Simple math.",
        "Self-care, but make it horrifying.",
        "Midnight can keep the despair. I prefer sustain.",
        "I am alive because I decided to be.",
      },
    },

    -- Area / Presence
    {
      id = "dk_death_and_decay",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Death and Decay" },
      messages = {
        "Death and Decay. Please enjoy the ambiance.",
        "I have placed a bad circle on the ground. Do not stand in it.",
        "Acherus-approved landscaping.",
        "This area is now legally unpleasant.",
        "If Midnight brings a Voidstorm, I brought a doom puddle.",
        "Welcome to my hazard zone.",
        "The floor has been cursed. You're welcome.",
        "Ground effects: because subtlety is dead.",
      },
    },

    -- Summons / Big moments
    {
      id = "dk_raise_dead",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Raise Dead" },
      messages = {
        "Raise Dead. Team meeting, attendance required.",
        "Skeleton assistant deployed.",
        "I brought a friend. They are mostly compliant.",
        "Necromancy: the original networking.",
        "If Midnight gets weird, I get weirder.",
        "Minion online. Please ignore the smell.",
        "Who needs friends when you have the unquiet dead.",
        "Workforce expanded via questionable ethics.",
      },
    },
    {
      id = "dk_army_of_the_dead",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 180,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Army of the Dead" },
      messages = {
        "Army of the Dead. I have brought backups.",
        "This is now a group project.",
        "Acherus HR has approved mass hiring.",
        "If the Sunwell goes dark, I'm bringing my own crowd.",
        "Welcome to the apocalypse, population: me.",
        "Undead union meeting. We are all invited.",
        "The battlefield just became very crowded.",
        "My solution involves more skeletons.",
      },
    },
    {
      id = "dk_dark_transformation",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Dark Transformation" },
      messages = {
        "Dark Transformation. Minion upgrade applied.",
        "Glow-up, but make it necrotic.",
        "Ghoul mode: deluxe edition.",
        "I pressed the button and the vibes got worse.",
        "Midnight can keep its shadows. I make my own.",
        "Enhancement complete. Please fear responsibly.",
        "My pet is now a bigger problem.",
        "Powering up the nightmare assistant.",
      },
    },
    {
      id = "dk_summon_gargoyle",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 90,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Summon Gargoyle" },
      messages = {
        "Summon Gargoyle. Air support is undead now.",
        "Look up. Bad news has wings.",
        "I have called in a flying lawsuit.",
        "Gargoyle deployed. Please panic politely.",
        "If the Void is in the sky, so is my gargoyle.",
        "Acherus delivers. Same-day shipping.",
        "My pet has taken the high ground.",
        "The atmosphere is now hostile.",
      },
    },

    -- Frost identity
    {
      id = "dk_pillar_of_frost",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Pillar of Frost" },
      messages = {
        "Pillar of Frost. I have become a winter thesis.",
        "Strength increased. Chill increased.",
        "I am now legally colder.",
        "Power spike: frosty edition.",
        "If Midnight brings darkness, I bring a blizzard attitude.",
        "The cold has arrived with paperwork.",
        "I am standing taller. Mostly out of spite.",
        "Frost pillar up. Feel free to regret it.",
      },
    },

    -- Blood identity
    {
      id = "dk_dancing_rune_weapon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Dancing Rune Weapon" },
      messages = {
        "Dancing Rune Weapon. I brought a plus-one.",
        "My weapon is now doing interpretive violence.",
        "Double the blade, double the problems.",
        "Runes are humming. Someone is about to have a bad time.",
        "If Midnight is full of shadows, I brought extra steel.",
        "Mirror match: me vs you. Spoiler: me.",
        "This is my weapon performing modern art.",
        "The runeblade has learned choreography.",
      },
    },

    -- Mobility
    {
      id = "dk_wraith_walk",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellName = "Wraith Walk" },
      messages = {
        "Wraith Walk. I am speed, but make it haunted.",
        "Ghosting this situation, literally.",
        "I am leaving. The floor cannot stop me.",
        "Phase through problems. Return later with violence.",
        "If Midnight gets spooky, I get spookier.",
        "I have become a fast nightmare.",
        "Wraith Walk engaged. Do not perceive me.",
        "Excuse me. I am becoming intangible.",
      },
    },

    -- Spec change (non-spell, DK flavored)
    {
      id = "dk_spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT" },
      messages = {
        "Spec shift detected: <spec>. Adjust your expectations.",
        "<spec> mode. The runes feel different.",
        "Acherus approves this new mood: <spec>.",
        "Switched to <spec>. The violence has been rescheduled.",
        "<spec> selected. Please file complaints with the Ebon Blade.",
      },
    },

    -- ====================================================================
    -- BLOOD DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 250)
    -- ====================================================================
    {
      id = "dk_heart_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Heart Strike" },
      messages = {
        "Heart Strike. Targeting vital organs with enthusiasm.",
        "Striking the heart. Metaphorically and literally.",
        "Heart Strike deployed. Cardiology, but hostile.",
        "I have opinions about your circulatory system.",
        "The heart is the problem. I am the solution.",
        "Precision violence, organ-specific.",
      },
    },
    {
      id = "dk_blood_boil",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Blood Boil" },
      messages = {
        "Blood Boil. Literally boiling blood.",
        "Your blood pressure just became my problem.",
        "Boiling blood. Not medically advisable.",
        "Internal temperature: rising. Prognosis: poor.",
        "If your blood was calm, it is not anymore.",
        "Blood Boil engaged. Biology regrets this.",
      },
    },
    {
      id = "dk_marrowrend",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Marrowrend" },
      messages = {
        "Marrowrend. Rending marrow. It's in the name.",
        "Bone deep regrets incoming.",
        "Your skeleton has filed a complaint.",
        "Marrow extracted. Aggressively.",
        "Structural integrity: compromised.",
        "I am going after the bones now.",
      },
    },
    {
      id = "dk_bonestorm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Bonestorm" },
      messages = {
        "Bonestorm. Skeleton tornado deployed.",
        "I have become a whirlwind of regret and calcium.",
        "Bonestorm engaged. Please admire the structural damage.",
        "Spinning bones. For health reasons.",
        "If Midnight wanted intact skeletons, too late.",
        "Hurricane of bone. Very metal.",
      },
    },
    {
      id = "dk_vampiric_blood",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "defensive",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Vampiric Blood" },
      messages = {
        "Vampiric Blood. I am temporarily more immortal.",
        "Blood thirst: maximum. Survival: ensured.",
        "Vampiric mode engaged. The count approves.",
        "My blood now has aggressive opinions.",
        "Vampiric sustain online. Death is optional.",
        "Blood magic: the self-care edition.",
      },
    },
    {
      id = "dk_blood_tap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Blood Tap" },
      messages = {
        "Blood Tap. Borrowing runes from my veins.",
        "Tapping into the crimson reservoir.",
        "Blood donation, but to myself.",
        "Rune economy: blood-based.",
        "Self-banking via bloodstream.",
      },
    },
    {
      id = "dk_consumption",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Consumption" },
      messages = {
        "Consumption. Healing through violence.",
        "Consuming health. Via attack.",
        "Life drain: aggressive edition.",
        "If I hit you, I heal me. Economics.",
        "Consumption online. Your HP is mine.",
      },
    },

    -- ====================================================================
    -- FROST DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 251)
    -- ====================================================================
    {
      id = "dk_obliterate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Obliterate" },
      messages = {
        "Obliterate. The name is self-explanatory.",
        "Obliterating with two weapons. Efficiency.",
        "Obliteration protocol: yes.",
        "Dual wield deletion engaged.",
        "If it existed, past tense.",
        "Two blades, one target, zero survivors.",
      },
    },
    {
      id = "dk_frost_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Frost Strike" },
      messages = {
        "Frost Strike. Cold and calculated.",
        "Striking with winter's approval.",
        "Frost Strike deployed. Temperature: hostile.",
        "The cold never bothered me. You, however.",
        "Icy violence engaged.",
        "Strike from the frozen north.",
      },
    },
    {
      id = "dk_howling_blast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Howling Blast" },
      messages = {
        "Howling Blast. AoE winter deployed.",
        "Blasting with audible cold.",
        "The wind howls. So does the damage.",
        "Howling Blast online. Volume: loud. Temperature: no.",
        "If you wanted warmth, wrong death knight.",
        "Frost AoE with sound effects.",
      },
    },
    {
      id = "dk_remorseless_winter",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Remorseless Winter" },
      messages = {
        "Remorseless Winter. Winter without regret.",
        "Deploying a blizzard with attitude.",
        "The cold is here. Remorse is not.",
        "Winter aura: merciless edition.",
        "If Midnight brought darkness, I brought frostbite.",
        "Remorseless and frozen. My brand.",
      },
    },
    {
      id = "dk_empower_rune_weapon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Empower Rune Weapon" },
      messages = {
        "Empower Rune Weapon. Instant runes deployed.",
        "Rune battery fully charged.",
        "Empowerment complete. The spam begins.",
        "Runes refreshed. Please stand back.",
        "If you wanted a break, denied.",
        "Power surge via runic overdrive.",
      },
    },
    {
      id = "dk_breath_of_sindragosa",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Breath of Sindragosa" },
      messages = {
        "Breath of Sindragosa. Channeling dragon winter.",
        "Sindragosa approved this breath attack.",
        "Dragon breath: frost edition.",
        "If Midnight wanted warmth, I brought the Frost Queen.",
        "Breath of the damned dragon engaged.",
        "Sindragosa says: freeze.",
      },
    },
    {
      id = "dk_frostwyrms_fury",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 90,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellName = "Frostwyrm's Fury" },
      messages = {
        "Frostwyrm's Fury. Summoning undead dragon rage.",
        "Frostwyrm deployed. The sky is now hostile.",
        "Dragon fury: frost zombie edition.",
        "If Midnight flies, the wyrm objects.",
        "Frostwyrm online. Panic politely.",
        "Undead dragon fury engaged. Run.",
      },
    },

    -- ====================================================================
    -- UNHOLY DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 252)
    -- ====================================================================
    {
      id = "dk_scourge_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Scourge Strike" },
      messages = {
        "Scourge Strike. Plague delivery system.",
        "Striking with infectious enthusiasm.",
        "Scourge deployed. Health inspector not invited.",
        "Disease transmission: weaponized.",
        "If you wanted hygiene, wrong death knight.",
        "Plague strike with commitment.",
      },
    },
    {
      id = "dk_festering_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Festering Strike" },
      messages = {
        "Festering Strike. Wounds festering on demand.",
        "Infection multiplication protocol.",
        "Festering engaged. Antibiotics not included.",
        "Your wounds have developed opinions.",
        "Medical condition: worsening. By design.",
        "Festering wounds deployed. Please do not lance.",
      },
    },
    {
      id = "dk_apocalypse",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Apocalypse" },
      messages = {
        "Apocalypse. End times on demand.",
        "Deploying the apocalypse. Locally.",
        "Apocalypse engaged. The horsemen approve.",
        "If Midnight wanted subtle, I brought Revelation.",
        "End of days protocol: activated.",
        "Apocalypse now. File your complaints in writing.",
      },
    },
    {
      id = "dk_outbreak",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Outbreak" },
      messages = {
        "Outbreak. Spreading diseases professionally.",
        "Plague distribution: initiated.",
        "Outbreak online. Please do not report to health authorities.",
        "If you wanted wellness, wrong class.",
        "Disease outbreak deployed. Quarantine optional.",
        "Infection control: abandoned.",
      },
    },
    {
      id = "dk_epidemic",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Epidemic" },
      messages = {
        "Epidemic. Plague AoE deployed.",
        "Disease spreads. By design.",
        "Epidemic engaged. Social distancing: irrelevant.",
        "If one plague is good, area plague is better.",
        "Infection radius: expanded.",
        "Epidemic protocol: active.",
      },
    },
    {
      id = "dk_unholy_blight",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Unholy Blight" },
      messages = {
        "Unholy Blight. Mass infection deployed.",
        "Blight engaged. Everyone gets sick.",
        "Unholy contamination protocol.",
        "If Midnight wanted health, I brought blight.",
        "Area plague: activated.",
        "Blight online. Please panic responsibly.",
      },
    },
    {
      id = "dk_soul_reaper",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Soul Reaper" },
      messages = {
        "Soul Reaper. Executing with soul theft.",
        "Reaping souls. It's a living. Sort of.",
        "Soul Reaper deployed. Your soul: harvested.",
        "If HP is low, soul collection begins.",
        "Reaping protocol: active.",
        "Soul harvest engaged.",
      },
    },
    {
      id = "dk_abomination_limb",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Abomination Limb" },
      messages = {
        "Abomination Limb. Summoning questionable anatomy.",
        "Giant arm deployed. Do not ask where from.",
        "Abomination limb online. Biology has filed a complaint.",
        "If Midnight wanted normal, I brought body horror.",
        "Limb of dubious origin: active.",
        "Abomination protocols engaged. Do not perceive closely.",
      },
    },
  },
})
