-- SpeakinLite - Warrior Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "warrior",
  name = "Warrior Pack",
  defaults = { class = "WARRIOR", unit = "player" },
  triggers = {
    -- Emote flavor triggers (Example: Mood-based messages)
    {
      id = "warrior_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messagesByMood = {
        default = {
          "roars into battle, weapon raised high.",
          "charges forward with unbridled fury.",
          "enters combat, ready to break things.",
          "grips their weapon, warrior rage awakening.",
          "prepares for glorious combat.",
        },
        serious = {
          "enters combat stance, weapon drawn.",
          "prepares for battle with grim determination.",
          "readies for combat, focused and alert.",
          "assumes a defensive posture, ready to strike.",
          "draws their weapon, eyes on the enemy.",
        },
        humorous = {
          "Oh boy, here we go again.",
          "Did someone order violence? Special delivery.",
          "Time to introduce weapons to faces.",
          "And now for my favorite part: hitting things.",
          "Combat? More like combat, am I right?",
        },
        dark = {
          "advances, hungering for blood.",
          "embraces the carnage to come.",
          "prepares to paint the ground red.",
          "grins wickedly, anticipating the slaughter.",
          "enters the fray, death in their eyes.",
        },
        heroic = {
          "FOR GLORY AND HONOR!",
          "Stands ready to defend the weak!",
          "Enters battle, champion of justice!",
          "For the Alliance/Horde! Forward!",
          "Courage and steel shall prevail!",
        },
      },
    },
    {
      id = "warrior_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "stands victorious, bloodied but unbowed.",
        "sheathes their weapon, another battle won.",
        "flexes, dominance asserted.",
        "grins, that was a good fight.",
        "nods approvingly, honor satisfied.",
      },
    },

    -- Charge / Mobility
    {
      id = "charge",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "movement",
      conditions = { spellName = "Charge" },
      messages = {
        "Charge. I have decided to be over there now.",
        "Incoming. Physics says hi.",
        "Closing distance. Aggressively.",
        "I am speed. Also fury.",
        "Gap: closed. Attitude: open.",
        "If Midnight wants to be dramatic, I can be dramatic too.",
        "Your personal space has been revoked.",
        "I have arrived. Violently.",
      },
    },
    {
      id = "heroic_leap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "movement",
      conditions = { spellName = "Heroic Leap" },
      messages = {
        "Heroic Leap. Gravity is a suggestion.",
        "I believe I can fly. Briefly.",
        "Launching myself at the problem.",
        "Airborne. Still angry.",
        "Up, over, and through.",
        "If the Void wants to fly, I can too.",
        "Tactical relocation via violence.",
        "Physics have been suspended for maintenance.",
      },
    },
    {
      id = "intervene",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Intervene" },
      messages = {
        "Intervene. I am on the way.",
        "Protective relocation engaged.",
        "I got you. Probably.",
        "Incoming bodyguard services.",
        "That was meant for me. Unfortunately for them.",
        "If Midnight targets you, I target Midnight.",
        "Redirecting violence to myself. Business as usual.",
        "Intervention deployed. Hold still.",
      },
    },

    -- Shouts / Utility
    {
      id = "battle_shout",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Battle Shout" },
      messages = {
        "Battle Shout. Everyone gets stronger now.",
        "Buffing the team via yelling.",
        "Loud noises make us better. I do not make the rules.",
        "Motivational screaming activated.",
        "If the Void whispers, I shout.",
        "Volume equals victory.",
        "Rally cry: deployed.",
        "I have opinions and they are loud.",
      },
    },
    {
      id = "commanding_shout",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Commanding Shout" },
      messages = {
        "Commanding Shout. Everyone gets healthier.",
        "Yelling health into existence.",
        "Protective screaming online.",
        "More HP for all. Via volume.",
        "Commanding presence activated.",
        "If Midnight wants to hurt us, it will have to work for it.",
        "Fortifying the group through sheer willpower.",
        "Vitality buff: deployed loudly.",
      },
    },
    {
      id = "rallying_cry",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Rallying Cry" },
      messages = {
        "Rallying Cry. Emergency HP engaged.",
        "Panic button pressed. Everyone lives.",
        "Shouting survival into reality.",
        "Group save via aggressive encouragement.",
        "If Midnight wants a wipe, I have opinions.",
        "Rally mode: maximum volume.",
        "Temporary immortality granted via yelling.",
        "Crisis management through screaming.",
      },
    },

    -- Defensive CDs
    {
      id = "shield_wall",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Shield Wall" },
      messages = {
        "Shield Wall. I am now a fortress.",
        "Damage reduction: extreme.",
        "I have become difficult to kill.",
        "Wall mode activated.",
        "If the Void hits me, it will be disappointed.",
        "Fortified. Unbothered.",
        "Try harder, Midnight.",
        "Defense protocol: shield everything.",
      },
    },
    {
      id = "die_by_the_sword",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Die by the Sword" },
      messages = {
        "Die by the Sword. Actually, I will not die.",
        "Parry mode: everything.",
        "Deflecting the entire encounter.",
        "My sword has a veto on damage.",
        "If Midnight swings, I parry.",
        "Block, dodge, parry. The full package.",
        "I have decided not to take damage right now.",
        "Defensive perfection engaged.",
      },
    },
    {
      id = "enraged_regeneration",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Enraged Regeneration" },
      messages = {
        "Enraged Regeneration. Healing via anger.",
        "I am too mad to die.",
        "Fury-based life support online.",
        "Rage heals all wounds. Literally.",
        "If Midnight wants me dead, it can wait.",
        "Angry recovery mode.",
        "Self-care through violence.",
        "Regenerating with attitude.",
      },
    },
    {
      id = "spell_reflection",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { spellName = "Spell Reflection" },
      messages = {
        "Spell Reflection. Return to sender.",
        "Your spell has been declined.",
        "Magic, but backwards.",
        "No thank you. You take it.",
        "Reflected. Consider yourself counter-spelled.",
        "If the Void casts, I reflect.",
        "Uno reverse card: activated.",
        "Your magic is now my magic. Briefly.",
      },
    },

    -- Offensive CDs
    {
      id = "recklessness",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Recklessness" },
      messages = {
        "Recklessness. Time to make questionable decisions.",
        "Critical strike guarantee activated.",
        "All hits, all crits, all anger.",
        "Reckless mode: engaged.",
        "If Midnight wants a fight, I am very available.",
        "Damage amplified. Caution discarded.",
        "Going all in. No regrets.",
        "Fury maximized. Strategy optional.",
      },
    },
    {
      id = "avatar",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Avatar" },
      messages = {
        "Avatar. I have become a problem.",
        "God mode: warrior edition.",
        "Ascended to violence.",
        "Ultimate form unlocked.",
        "If Midnight brought an army, I brought myself.",
        "Titan strength activated.",
        "Power spike incoming.",
        "Avatar online. Please panic responsibly.",
      },
    },
    {
      id = "bladestorm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { spellName = "Bladestorm" },
      messages = {
        "Bladestorm. I am a tornado of violence.",
        "Spinning to win.",
        "Whirlwind but with commitment.",
        "Helicopter mode activated.",
        "If Midnight gets close, it gets cut.",
        "Area denial via spinning.",
        "Blade tornado deployed.",
        "I have become a blender.",
      },
    },

    -- Execute
    {
      id = "execute",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { spellName = "Execute" },
      messages = {
        "Execute. Finishing the job.",
        "Low HP detected. Finishing blow deployed.",
        "Execution protocol activated.",
        "You were at low health. Past tense.",
        "Mercy is for other classes.",
        "If Midnight wanted to survive, it should not be at 20%.",
        "Finisher deployed.",
        "Execute order: yes.",
      },
    },

    -- Thunderclap
    {
      id = "thunder_clap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Thunder Clap" },
      messages = {
        "Thunder Clap. Everyone gets hit.",
        "AoE via anger.",
        "Clapping with thunder. Very loud.",
        "Area of effect: aggressive.",
        "If Midnight brought adds, I brought thunder.",
        "Thunderous applause. Also damage.",
        "Shock and awe deployed.",
        "Thunder mode: on.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Adjusting violence levels.",
        "<spec> mode. The method changes, the anger remains.",
        "Switched to <spec>. Still hitting things.",
        "<spec> selected. Recalibrating rage.",
        "New spec, same attitude: <spec>.",
      },
    },

    -- ====================================================================
    -- ARMS WARRIOR SPEC-SPECIFIC TRIGGERS (SpecID: 71)
    -- ====================================================================
    {
      id = "warrior_mortal_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 71, spellName = "Mortal Strike" },
      messages = {
        "Mortal Strike. Healing reduction applied.",
        "Strike with mortal consequences.",
        "Mortal blow delivered.",
        "If you wanted healing, should have dodged.",
        "Mortal damage engaged.",
        "The signature Arms attack.",
      },
    },
    {
      id = "warrior_colossus_smash",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 71, spellName = "Colossus Smash" },
      messages = {
        "Colossus Smash. Armor means nothing now.",
        "Smashing through defenses.",
        "Colossus impact deployed.",
        "Armor? What armor?",
        "Defense ignored. Pain delivered.",
        "If Midnight has armor, I have a solution.",
      },
    },
    {
      id = "warrior_warbreaker",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 71, spellName = "Warbreaker" },
      messages = {
        "Warbreaker. AoE armor shred.",
        "Breaking the will to defend.",
        "Warbreaker deployed. Everyone's vulnerable.",
        "Armor reduction via violence.",
        "The war breaks here.",
      },
    },
    {
      id = "warrior_overpower",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 71, spellName = "Overpower" },
      messages = {
        "Overpower. Tactical strike.",
        "Overpowering the opposition.",
        "Superior force applied.",
        "Overpower deployed. Dodge this.",
        "Too much power. That's the point.",
      },
    },

    -- ====================================================================
    -- FURY WARRIOR SPEC-SPECIFIC TRIGGERS (SpecID: 72)
    -- ====================================================================
    {
      id = "warrior_rampage",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 72, spellName = "Rampage" },
      messages = {
        "Rampage. Uncontrolled violence.",
        "Rampaging through the encounter.",
        "Fury unleashed. Stand back.",
        "Rage converted to pain. Theirs, not mine.",
        "Rampage mode: maximum anger.",
        "If Midnight wanted calm, wrong warrior.",
      },
    },
    {
      id = "warrior_bloodthirst",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 72, spellName = "Bloodthirst" },
      messages = {
        "Bloodthirst. Healing via violence.",
        "Thirsting for blood. And HP.",
        "Bloodthirst engaged. Damage and healing.",
        "Life stolen through fury.",
        "The thirst is real.",
      },
    },
    {
      id = "warrior_raging_blow",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 72, spellName = "Raging Blow" },
      messages = {
        "Raging Blow. Double strike deployed.",
        "Blow after raging blow.",
        "Fury attacks twice.",
        "Raging impact. Then another.",
        "Two-handed, twice over.",
      },
    },
    {
      id = "warrior_odyns_fury",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 72, spellName = "Odyn's Fury" },
      messages = {
        "Odyn's Fury. Channeling Valhalla.",
        "Fury of the storm god.",
        "Odyn approves this violence.",
        "Storm fury deployed.",
        "If Midnight wanted calm, Odyn disagrees.",
      },
    },

    -- ====================================================================
    -- PROTECTION WARRIOR SPEC-SPECIFIC TRIGGERS (SpecID: 73)
    -- ====================================================================
    {
      id = "warrior_shield_slam",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 73, spellName = "Shield Slam" },
      messages = {
        "Shield Slam. Shield as weapon.",
        "Slamming with defensive intent.",
        "Shield deployed offensively.",
        "Defensive equipment, aggressive application.",
        "If Midnight wants a face full of shield, here it is.",
      },
    },
    {
      id = "warrior_shield_block",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { specID = 73, spellName = "Shield Block" },
      messages = {
        "Shield Block. Blocking enhanced.",
        "Shield up. Good luck.",
        "Block chance: 100%.",
        "The shield says no.",
        "Blocking with authority.",
      },
    },
    {
      id = "warrior_last_stand",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { specID = 73, spellName = "Last Stand" },
      messages = {
        "Last Stand. Emergency HP engaged.",
        "Last stand deployed. I refuse to die.",
        "Temporary immortality via willpower.",
        "Last stand online. Death delayed.",
        "If Midnight wants me dead, it will have to work harder.",
      },
    },
    {
      id = "warrior_demoralizing_shout",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "defensive",
      conditions = { specID = 73, spellName = "Demoralizing Shout" },
      messages = {
        "Demoralizing Shout. Damage reduced via yelling.",
        "Shouting discouragement.",
        "Demoralized. Via volume.",
        "Protective screaming deployed.",
        "Loud noises weaken enemies.",
      },
    },
    {
      id = "warrior_ignore_pain",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "defensive",
      conditions = { specID = 73, spellName = "Ignore Pain" },
      messages = {
        "Ignore Pain. Pain is optional.",
        "Damage absorbed via stubbornness.",
        "Ignoring pain with attitude.",
        "If Midnight hits me, I am unbothered.",
        "Pain? What pain?",
      },
    },
    {
      id = "warrior_revenge",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 73, spellName = "Revenge" },
      messages = {
        "Revenge. Payback time.",
        "Revenge is a dish best served immediately.",
        "Retaliation engaged.",
        "You hit me. Now I hit back. Harder.",
        "Revenge deployed with satisfaction.",
      },
    },
  },
})
