-- SpeakinLite - Monk Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "monk",
  name = "Monk Pack",
  defaults = { class = "MONK", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "monk_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "assumes a fighting stance, zen and focus unified.",
        "enters combat, mind and body as one.",
        "prepares to strike with disciplined fury.",
        "channels chi for battle.",
        "readies their fists, calm yet deadly.",
      },
    },
    {
      id = "monk_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "returns to meditation stance.",
        "bows respectfully, combat complete.",
        "relaxes, inner peace restored.",
        "exhales slowly, balance maintained.",
        "stands serenely, another lesson learned.",
      },
    },

    -- Mobility
    {
      id = "roll",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "movement",
      conditions = { spellName = "Roll" },
      messages = {
        "Roll. Physics are optional.",
        "Rolling away from problems.",
        "Barrel roll deployed.",
        "If Midnight wanted me there, too late.",
        "Roll mode activated.",
        "Tumbling with purpose.",
        "Rolling thunder engaged.",
        "Physics? More like suggestions.",
      },
    },
    {
      id = "transcendence",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Transcendence" },
      messages = {
        "Transcendence. Placing my spirit.",
        "Spirit anchor deployed.",
        "Teleport point established.",
        "If Midnight wants me later, I have an out.",
        "Transcendence mark placed.",
        "Spirit location saved.",
        "Anchor point set.",
        "Teleport coordinates stored.",
      },
    },
    {
      id = "transcendence_transfer",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "movement",
      conditions = { spellName = "Transcendence: Transfer" },
      messages = {
        "Transcendence: Transfer. Teleporting.",
        "Spirit teleport activated.",
        "Returning to my anchor.",
        "If Midnight wanted me here, incorrect.",
        "Transfer complete.",
        "Teleported to spirit.",
        "Instant relocation via transcendence.",
        "Gone. Via mysticism.",
      },
    },

    -- Defensive
    {
      id = "fortifying_brew",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "defensive",
      conditions = { spellName = "Fortifying Brew" },
      messages = {
        "Fortifying Brew. Drinking defensively.",
        "Brew mode: fortified.",
        "If Midnight hits me, I am sturdy now.",
        "Defensive ale consumed.",
        "Fortification engaged.",
        "Brew shield active.",
        "Fortified via beverage.",
        "Defensive drink deployed.",
      },
    },
    {
      id = "diffuse_magic",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Diffuse Magic" },
      messages = {
        "Diffuse Magic. Spell damage reduced.",
        "Magic diffused. Less effective.",
        "If Midnight casts, I diffuse.",
        "Spell mitigation activated.",
        "Magic diffusion online.",
        "Spells weakened.",
        "Diffuse protocol engaged.",
        "Magic scattered harmlessly.",
      },
    },
    {
      id = "touch_of_karma",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "defensive",
      conditions = { spellName = "Touch of Karma" },
      messages = {
        "Touch of Karma. Damage reflected.",
        "Karma mode: aggressive.",
        "If Midnight hits me, it hits itself.",
        "Karmic justice deployed.",
        "Damage redirection active.",
        "Touch of karma engaged.",
        "What goes around, comes around.",
        "Karma protocol online.",
      },
    },

    -- Offensive CDs
    {
      id = "storm_earth_and_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Storm, Earth, and Fire" },
      messages = {
        "Storm, Earth, and Fire. I am now three problems.",
        "Splitting into elements.",
        "If Midnight wanted one monk, tough luck.",
        "Elemental clones deployed.",
        "Storm, Earth, Fire mode: on.",
        "Triple monk activated.",
        "Three-way split engaged.",
        "Elemental multiplication complete.",
      },
    },
    {
      id = "serenity",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Serenity" },
      messages = {
        "Serenity. Calm fury activated.",
        "Serenity mode: paradoxically aggressive.",
        "If Midnight wanted chaos, I brought calm violence.",
        "Serenity online. Damage maximized.",
        "Calm devastation engaged.",
        "Serene fury deployed.",
        "Peace through power.",
        "Serenity protocol active.",
      },
    },
    {
      id = "invoke_xuen",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Invoke Xuen, the White Tiger" },
      messages = {
        "Invoke Xuen. Tiger backup deployed.",
        "Xuen summoned. Tiger damage incoming.",
        "If Midnight wanted a monk, it gets a tiger too.",
        "White Tiger engaged.",
        "Celestial cat online.",
        "Xuen protocol activated.",
        "Tiger ally summoned.",
        "Invoke complete. Tiger time.",
      },
    },

    -- Utility
    {
      id = "paralysis",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Paralysis" },
      messages = {
        "Paralysis. Movement cancelled.",
        "Paralyzing touch deployed.",
        "If Midnight wanted to act, denied.",
        "Paralysis protocol engaged.",
        "Frozen via chi.",
        "Paralysis applied.",
        "Movement revoked.",
        "Paralyzed with precision.",
      },
    },
    {
      id = "ring_of_peace",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Ring of Peace" },
      messages = {
        "Ring of Peace. Silence zone deployed.",
        "Peace ring active. Violence paused.",
        "If Midnight wanted chaos, circle says no.",
        "Ring of tranquility engaged.",
        "Peace field online.",
        "Silence ring deployed.",
        "Peaceful zone activated.",
        "Ring of calm established.",
      },
    },
    {
      id = "leg_sweep",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Leg Sweep" },
      messages = {
        "Leg Sweep. Everyone falls down.",
        "Sweeping the leg. Literally.",
        "If Midnight stands, not anymore.",
        "AoE stun via footwork.",
        "Leg sweep deployed.",
        "Sweep protocol engaged.",
        "Everyone trips. Simultaneously.",
        "Leg sweep complete. Ground time.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Chi rebalanced.",
        "<spec> mode. The Way of the Monk adapts.",
        "Switched to <spec>. Harmony adjusted.",
        "<spec> selected. Meditation strategy changed.",
        "New spec, same monk: <spec>.",
      },
    },

    -- ====================================================================
    -- BREWMASTER MONK SPEC-SPECIFIC TRIGGERS (SpecID: 268)
    -- ====================================================================
    {
      id = "monk_keg_smash",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 268, spellName = "Keg Smash" },
      messages = {
        "Keg Smash. Barrel attack.",
        "Keg deployed.",
        "Smashing with brew.",
        "Keg strike online.",
        "Barrel smash engaged.",
      },
    },
    {
      id = "monk_breath_of_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 268, spellName = "Breath of Fire" },
      messages = {
        "Breath of Fire. Alcohol flame.",
        "Fire breath deployed.",
        "Breathing fire. From brew.",
        "Flame breath online.",
        "Drunk dragon engaged.",
      },
    },
    {
      id = "monk_purifying_brew",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { specID = 268, spellName = "Purifying Brew" },
      messages = {
        "Purifying Brew. Damage cleanse.",
        "Purify deployed.",
        "Damage purged.",
        "Cleansing brew online.",
        "Purification activated.",
      },
    },
    {
      id = "monk_celestial_brew",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { specID = 268, spellName = "Celestial Brew" },
      messages = {
        "Celestial Brew. Divine shield.",
        "Celestial drink deployed.",
        "Heavenly brew online.",
        "Divine shield engaged.",
        "Celestial defense activated.",
      },
    },
    {
      id = "monk_invoke_niuzao",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 268, spellName = "Invoke Niuzao, the Black Ox" },
      messages = {
        "Invoke Niuzao. Ox guardian.",
        "Black Ox deployed.",
        "Celestial tank online.",
        "Niuzao engaged.",
        "Ox guardian activated.",
      },
    },

    -- ====================================================================
    -- WINDWALKER MONK SPEC-SPECIFIC TRIGGERS (SpecID: 269)
    -- ====================================================================
    {
      id = "monk_rising_sun_kick",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 269, spellName = "Rising Sun Kick" },
      messages = {
        "Rising Sun Kick. Solar strike.",
        "Sun kick deployed.",
        "Rising strike online.",
        "Solar kick engaged.",
        "Sun attack activated.",
      },
    },
    {
      id = "monk_fists_of_fury",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 269, spellName = "Fists of Fury" },
      messages = {
        "Fists of Fury. Punch barrage.",
        "Fury deployed.",
        "Fist barrage online.",
        "Rapid punching engaged.",
        "Fury activated.",
      },
    },
    {
      id = "monk_spinning_crane_kick",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 269, spellName = "Spinning Crane Kick" },
      messages = {
        "Spinning Crane Kick. AoE spin.",
        "Crane kick deployed.",
        "Spinning attack online.",
        "AoE kick engaged.",
        "Crane style activated.",
      },
    },
    {
      id = "monk_strike_of_the_windlord",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 269, spellName = "Strike of the Windlord" },
      messages = {
        "Strike of the Windlord. Wind strike.",
        "Windlord deployed.",
        "Wind fury online.",
        "Windlord strike engaged.",
        "Wind attack activated.",
      },
    },

    -- ====================================================================
    -- MISTWEAVER MONK SPEC-SPECIFIC TRIGGERS (SpecID: 270)
    -- ====================================================================
    {
      id = "monk_soothing_mist",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 270, spellName = "Soothing Mist" },
      messages = {
        "Soothing Mist. Heal channel.",
        "Mist deployed.",
        "Soothing heal online.",
        "Mist healing engaged.",
        "Soothing activated.",
      },
    },
    {
      id = "monk_enveloping_mist",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 270, spellName = "Enveloping Mist" },
      messages = {
        "Enveloping Mist. Strong heal.",
        "Envelop deployed.",
        "Big heal online.",
        "Enveloping engaged.",
        "Mist heal activated.",
      },
    },
    {
      id = "monk_essence_font",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 270, spellName = "Essence Font" },
      messages = {
        "Essence Font. AoE heal.",
        "Font deployed.",
        "Essence healing online.",
        "Group heal engaged.",
        "Font activated.",
      },
    },
    {
      id = "monk_revival",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 270, spellName = "Revival" },
      messages = {
        "Revival. Mass heal.",
        "Revival deployed.",
        "Group revival online.",
        "Mass restoration engaged.",
        "Revival activated.",
      },
    },
    {
      id = "monk_invoke_yulon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 270, spellName = "Invoke Yu'lon, the Jade Serpent" },
      messages = {
        "Invoke Yu'lon. Serpent healer.",
        "Jade Serpent deployed.",
        "Celestial healer online.",
        "Yu'lon engaged.",
        "Serpent guardian activated.",
      },
    },
  },
})
