-- SpeakinLite - Hunter Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "hunter",
  name = "Hunter Pack",
  defaults = { class = "HUNTER", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "hunter_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "nocks an arrow, eyes on the target.",
        "signals their pet, hunt begins.",
        "assumes a marksman's stance.",
        "readies for the hunt.",
        "prepares to track and eliminate.",
      },
    },
    {
      id = "hunter_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "lowers their bow, prey eliminated.",
        "pets their companion, hunt successful.",
        "relaxes, another trophy claimed.",
        "stands victorious with their beast.",
        "grins, the wilds provide.",
      },
    },

    -- Pets
    {
      id = "call_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Call Pet" },
      messages = {
        "Call Pet. My friend is here.",
        "Pet deployed. Please do not feed it.",
        "Animal companion online.",
        "Summoning my emotional support damage dealer.",
        "If Midnight has minions, I have a pet.",
        "Best friend activated.",
        "Wildlife recruited.",
        "The beast answers. Probably.",
      },
    },
    {
      id = "mend_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Mend Pet" },
      messages = {
        "Mend Pet. Healing my friend.",
        "Pet maintenance in progress.",
        "Keeping the companion alive.",
        "My pet deserves better than this encounter.",
        "If the pet dies, I have feelings about it.",
        "Applying bandages. To the pet.",
        "Animal healthcare deployed.",
        "The beast gets better.",
      },
    },
    {
      id = "revive_pet",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Revive Pet" },
      messages = {
        "Revive Pet. Back from the void.",
        "Resurrecting my emotional support animal.",
        "The pet returns. Slightly inconvenienced.",
        "Death was temporary for the beast.",
        "If Midnight killed my pet, I am taking notes.",
        "Revival protocol activated.",
        "The companion lives again.",
        "Back to life. The pet edition.",
      },
    },

    -- Traps
    {
      id = "freezing_trap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Freezing Trap" },
      messages = {
        "Freezing Trap. Step carefully.",
        "Ice trap deployed. Wait for it.",
        "Frozen in place. Courtesy of a trap.",
        "Trap set. Patience rewarded.",
        "If Midnight walks here, it gets frozen.",
        "Cryogenic crowd control engaged.",
        "Trap activated. Stand by.",
        "Freeze protocol placed strategically.",
      },
    },
    {
      id = "tar_trap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Tar Trap" },
      messages = {
        "Tar Trap. Sticky situation deployed.",
        "Slowing field activated.",
        "The floor is now problematic.",
        "Tar placed strategically.",
        "If Midnight wants to run, good luck.",
        "Movement debuff via goo.",
        "Sticky trap online.",
        "The ground disagrees with speed.",
      },
    },

    -- Defensive
    {
      id = "feign_death",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "defensive",
      conditions = { spellName = "Feign Death" },
      messages = {
        "Feign Death. I am not here.",
        "Playing dead. Very convincingly.",
        "Threat dropped. I am a corpse now.",
        "If Midnight wants me, it can look elsewhere.",
        "Temporarily deceased. Do not panic.",
        "Acting skills: deployed.",
        "Death simulation engaged.",
        "I have become background scenery.",
      },
    },
    {
      id = "exhilaration",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Exhilaration" },
      messages = {
        "Exhilaration. Healing via enthusiasm.",
        "HP restored through sheer willpower.",
        "Self-heal deployed.",
        "Survival instincts activated.",
        "If death was imminent, I have declined.",
        "Health surge engaged.",
        "Living via determination.",
        "Exhilarated and healed.",
      },
    },
    {
      id = "aspect_of_the_turtle",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Aspect of the Turtle" },
      messages = {
        "Aspect of the Turtle. I am now a shell.",
        "Turtle mode: maximum defense.",
        "Immunity granted. Damage denied.",
        "The turtle has opinions about survival.",
        "If Midnight hits me, it will be disappointed.",
        "Shell defense online.",
        "Turtle power activated.",
        "I have become invincible. Briefly.",
      },
    },

    -- Offensive CDs
    {
      id = "bestial_wrath",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 40,
      category = "cooldowns",
      conditions = { spellName = "Bestial Wrath" },
      messages = {
        "Bestial Wrath. The pet is angry now.",
        "Maximum beast mode activated.",
        "My pet has opinions. Aggressive ones.",
        "Wrath engaged. The beast is unleashed.",
        "If Midnight wanted a calm pet, too bad.",
        "Fury protocol: beast edition.",
        "The animal is very motivated.",
        "Bestial power spike incoming.",
      },
    },
    {
      id = "aspect_of_the_wild",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Aspect of the Wild" },
      messages = {
        "Aspect of the Wild. Primal power online.",
        "The wild calls. It is very aggressive.",
        "Nature mode: maximum damage.",
        "Wild aspect activated.",
        "If Midnight thought hunters were tame, incorrect.",
        "Primal fury engaged.",
        "The wilderness approves this violence.",
        "Wild power unleashed.",
      },
    },

    -- Utility
    {
      id = "misdirection",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Misdirection" },
      messages = {
        "Misdirection. Threat redirected.",
        "My threat is now your problem.",
        "Aggro transfer complete.",
        "You wanted threat? Here you go.",
        "If Midnight hates me, it can hate you instead.",
        "Misdirect engaged. Good luck.",
        "Threat donation delivered.",
        "Redirecting violence elsewhere.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Adjusting hunting strategy.",
        "<spec> mode. The wild adapts.",
        "Switched to <spec>. Nature provides options.",
        "<spec> selected. Recalibrating beast tactics.",
        "New spec, same hunter: <spec>.",
      },
    },

    -- ====================================================================
    -- BEAST MASTERY HUNTER SPEC-SPECIFIC TRIGGERS (SpecID: 253)
    -- ====================================================================
    {
      id = "hunter_barbed_shot",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 253, spellName = "Barbed Shot" },
      messages = {
        "Barbed Shot. Keeping the pet frenzied.",
        "Barbed arrow deployed.",
        "Pet frenzy maintained.",
        "Barbed shot online. Beast mode engaged.",
        "Frenzy stack added.",
      },
    },
    {
      id = "hunter_kill_command_bm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 253, spellName = "Kill Command" },
      messages = {
        "Kill Command. Pet attack ordered.",
        "Commanding the kill.",
        "Pet deployed aggressively.",
        "Kill command issued.",
        "The beast obeys. Violently.",
      },
    },
    {
      id = "hunter_cobra_shot_bm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 253, spellName = "Cobra Shot" },
      messages = {
        "Cobra Shot. Quick and venomous.",
        "Cobra strike deployed.",
        "Fast shot online.",
        "Cobra engaged.",
        "Quick damage delivered.",
      },
    },
    {
      id = "hunter_dire_beast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 253, spellName = "Dire Beast" },
      messages = {
        "Dire Beast. Summoning extra animal.",
        "Dire beast deployed.",
        "Additional pet online. Temporarily.",
        "Dire companion summoned.",
        "The wild provides backup.",
      },
    },
    {
      id = "hunter_stampede",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 253, spellName = "Stampede" },
      messages = {
        "Stampede. Summoning the entire menagerie.",
        "Stampede deployed. All the pets.",
        "Animal army engaged.",
        "The zoo is now open. For violence.",
        "If Midnight wanted a fair fight, too bad.",
      },
    },

    -- ====================================================================
    -- MARKSMANSHIP HUNTER SPEC-SPECIFIC TRIGGERS (SpecID: 254)
    -- ====================================================================
    {
      id = "hunter_aimed_shot",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 254, spellName = "Aimed Shot" },
      messages = {
        "Aimed Shot. Precision damage deployed.",
        "Aiming carefully. Then shooting.",
        "Aimed shot online. Sniper mode.",
        "Precision strike engaged.",
        "If Midnight wanted to dodge, too slow.",
      },
    },
    {
      id = "hunter_rapid_fire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 254, spellName = "Rapid Fire" },
      messages = {
        "Rapid Fire. Machine gun mode activated.",
        "Rapid fire deployed. Hold still.",
        "Channeling speed and fury.",
        "Rapid shot barrage engaged.",
        "If Midnight blinks, it misses all of this.",
      },
    },
    {
      id = "hunter_double_tap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 254, spellName = "Double Tap" },
      messages = {
        "Double Tap. Next shot hits twice.",
        "Double tap engaged. Efficiency doubled.",
        "Two for the price of one.",
        "Double damage incoming.",
        "If Midnight wanted one shot, it gets two.",
      },
    },
    {
      id = "hunter_trueshot",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 254, spellName = "Trueshot" },
      messages = {
        "Trueshot. Focus and power maximized.",
        "Trueshot engaged. Perfect aim.",
        "Focus mode activated.",
        "True precision online.",
        "If Midnight wanted misses, wrong hunter.",
      },
    },
    {
      id = "hunter_arcane_shot_mm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 254, spellName = "Arcane Shot" },
      messages = {
        "Arcane Shot. Magic arrow deployed.",
        "Arcane arrow engaged.",
        "Shooting magic. With a bow.",
        "Arcane damage online.",
        "Magically enhanced projectile.",
      },
    },

    -- ====================================================================
    -- SURVIVAL HUNTER SPEC-SPECIFIC TRIGGERS (SpecID: 255)
    -- ====================================================================
    {
      id = "hunter_raptor_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 255, spellName = "Raptor Strike" },
      messages = {
        "Raptor Strike. Melee hunter engaged.",
        "Raptor strike deployed.",
        "Striking like a predator.",
        "Raptor mode online.",
        "Melee range. As intended.",
      },
    },
    {
      id = "hunter_mongoose_bite",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 255, spellName = "Mongoose Bite" },
      messages = {
        "Mongoose Bite. Quick melee strike.",
        "Mongoose deployed. Fast and furious.",
        "Bite engaged. Stacking damage.",
        "Mongoose mode activated.",
        "Fast strike, faster followup.",
      },
    },
    {
      id = "hunter_wildfire_bomb",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 255, spellName = "Wildfire Bomb" },
      messages = {
        "Wildfire Bomb. Explosive deployed.",
        "Wildfire engaged. AoE incoming.",
        "Bomb thrown. Fire spreads.",
        "Wildfire online. Stand back.",
        "If Midnight wanted safety, wrong hunter.",
      },
    },
    {
      id = "hunter_coordinated_assault",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 255, spellName = "Coordinated Assault" },
      messages = {
        "Coordinated Assault. Pet and hunter unite.",
        "Assault coordinated. Maximum damage.",
        "Coordination online. Teamwork engaged.",
        "Pet and I attack together.",
        "If Midnight wanted solo hunters, too bad.",
      },
    },
    {
      id = "hunter_harpoon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "movement",
      conditions = { specID = 255, spellName = "Harpoon" },
      messages = {
        "Harpoon. Gap closed via projectile.",
        "Harpoon deployed. Incoming.",
        "Grappling to target.",
        "Harpoon online. I am coming to you.",
        "Distance eliminated via harpoon.",
      },
    },
  },
})
