-- EmoteControl - Druid Pack

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "druid",
  name = "Druid Pack",
  defaults = { class = "DRUID", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "druid_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "calls upon the wilds, nature's wrath awakening.",
        "channels primal fury into battle form.",
        "enters combat, nature's balance demanding action.",
        "prepares to defend the wild.",
        "assumes a battle stance, beast and druid as one.",
      },
    },
    {
      id = "druid_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "relaxes, nature's balance restored.",
        "returns to peaceful form.",
        "stands calmly, the wilds protected.",
        "nods to the spirits, harmony maintained.",
        "thanks nature for its strength.",
      },
    },

    -- Shapeshifting
    {
      id = "cat_form",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Cat Form" },
      messages = {
        "Cat Form. Feline mode activated.",
        "Becoming a cat. For damage purposes.",
        "Meow mode engaged.",
        "If Midnight wanted a druid, it gets a cat.",
        "Cat transformation complete.",
        "Feral feline online.",
        "I am cat. Hear me roar.",
        "Kitty mode activated.",
      },
    },
    {
      id = "bear_form",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { spellName = "Bear Form" },
      messages = {
        "Bear Form. I am now a tank.",
        "Becoming bear. For survival.",
        "Bear mode activated.",
        "If Midnight hits me, I am fluffy.",
        "Guardian bear online.",
        "Tank form engaged.",
        "I am bear. Very sturdy.",
        "Bear transformation complete.",
      },
    },
    {
      id = "travel_form",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "movement",
      conditions = { spellName = "Travel Form" },
      messages = {
        "Travel Form. Fast druid mode.",
        "Shapeshifting for speed.",
        "Travel form engaged. Going places.",
        "If Midnight chases me, I have forms for that.",
        "Fast travel activated.",
        "Movement form online.",
        "Speed shape engaged.",
        "Travel transformation complete.",
      },
    },
    {
      id = "moonkin_form",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Moonkin Form" },
      messages = {
        "Moonkin Form. I am now a space chicken.",
        "Boomkin mode activated.",
        "If Midnight wanted elegant, wrong form.",
        "Laser chicken engaged.",
        "Balance druid mode: on.",
        "Moonkin transformation complete.",
        "I am bird. With cosmic power.",
        "Space owl online.",
      },
    },

    -- Defensive
    {
      id = "barkskin",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Barkskin" },
      messages = {
        "Barkskin. Tree mode: defensive.",
        "Bark armor activated.",
        "Damage reduction via nature.",
        "If Midnight hits me, it hits bark.",
        "Natural defense online.",
        "Tree shield engaged.",
        "Barkskin protocol activated.",
        "Bark protection deployed.",
      },
    },
    {
      id = "survival_instincts",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Survival Instincts" },
      messages = {
        "Survival Instincts. Bear defense maximum.",
        "Instincts engaged. Survival likely.",
        "If death comes, instincts say no.",
        "Guardian survival mode.",
        "Survival protocol activated.",
        "Instinctive defense online.",
        "Bear survival engaged.",
        "Living via animal instinct.",
      },
    },
    {
      id = "frenzied_regeneration",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "defensive",
      conditions = { spellName = "Frenzied Regeneration" },
      messages = {
        "Frenzied Regeneration. Bear heal engaged.",
        "Frenzy mode: healing.",
        "Self-heal via bear power.",
        "If HP was low, nature provides.",
        "Frenzy healing online.",
        "Bear regeneration activated.",
        "Frenzied recovery engaged.",
        "Healing with aggression.",
      },
    },

    -- Offensive CDs
    {
      id = "incarnation",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Incarnation" },
      messages = {
        "Incarnation. Ultimate form activated.",
        "Primal incarnation engaged.",
        "If Midnight wanted normal, denied.",
        "Power form online.",
        "Incarnation protocol activated.",
        "Ultimate druid mode.",
        "Primal power unleashed.",
        "Incarnation complete.",
      },
    },
    {
      id = "berserk",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Berserk" },
      messages = {
        "Berserk. Feral fury activated.",
        "Rage mode: feline.",
        "If Midnight wanted calm, wrong cooldown.",
        "Berserk cat engaged.",
        "Feral frenzy online.",
        "Berserk protocol activated.",
        "Cat rage deployed.",
        "Feral fury unleashed.",
      },
    },
    {
      id = "convoke_the_spirits",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Convoke the Spirits" },
      messages = {
        "Convoke the Spirits. Nature lottery engaged.",
        "Summoning random nature magic.",
        "If Midnight wanted predictable, denied.",
        "Spirit convocation active.",
        "Random spell barrage deployed.",
        "Convoke online. Chaos imminent.",
        "Spirits summoned. Results vary.",
        "Nature magic roulette activated.",
      },
    },

    -- Utility
    {
      id = "typhoon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Typhoon" },
      messages = {
        "Typhoon. Wind knockback deployed.",
        "Blowing away problems.",
        "If Midnight stands close, not anymore.",
        "Wind blast engaged.",
        "Typhoon protocol activated.",
        "Knockback via nature.",
        "Storm push deployed.",
        "Wind says: leave.",
      },
    },
    {
      id = "entangling_roots",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Entangling Roots" },
      messages = {
        "Entangling Roots. Nature holds you.",
        "Rooted in place.",
        "If Midnight wanted to move, denied.",
        "Roots deployed. Stay put.",
        "Nature binds all.",
        "Entangling protocol engaged.",
        "Root snare activated.",
        "Held by the earth.",
      },
    },
    {
      id = "rebirth",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "utility",
      conditions = { spellName = "Rebirth" },
      messages = {
        "Rebirth. Combat resurrection deployed.",
        "Bringing someone back. Mid-fight.",
        "If death happened, nature disagrees.",
        "Rebirth protocol activated.",
        "Combat rez online.",
        "Life restored in battle.",
        "Resurrection via nature.",
        "Rebirth complete. Welcome back.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Nature provides versatility.",
        "<spec> mode. Shapeshifting complete.",
        "Switched to <spec>. The wild adapts.",
        "<spec> selected. Druid strategy adjusted.",
        "New spec, same druid: <spec>.",
      },
    },

    -- ====================================================================
    -- BALANCE DRUID SPEC-SPECIFIC TRIGGERS (SpecID: 102)
    -- ====================================================================
    {
      id = "druid_starfire",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 102, spellName = "Starfire" },
      messages = {
        "Starfire. Star power deployed.",
        "Shooting stars. Literally.",
        "Cosmic fire engaged.",
        "Starfire online.",
        "Celestial damage deployed.",
      },
    },
    {
      id = "druid_wrath",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 102, spellName = "Wrath" },
      messages = {
        "Wrath. Nature's anger.",
        "Wrath deployed.",
        "Angry tree noises.",
        "Nature wrath engaged.",
        "Balance fury online.",
      },
    },
    {
      id = "druid_starsurge",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 102, spellName = "Starsurge" },
      messages = {
        "Starsurge. Cosmic burst.",
        "Star surge deployed.",
        "Celestial impact engaged.",
        "Surge online.",
        "Star power unleashed.",
      },
    },
    {
      id = "druid_starfall",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 102, spellName = "Starfall" },
      messages = {
        "Starfall. Stars from above.",
        "Starfall engaged.",
        "Cosmic rain deployed.",
        "Stars falling.",
        "Celestial bombardment online.",
      },
    },
    {
      id = "druid_celestial_alignment",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 102, spellName = "Celestial Alignment" },
      messages = {
        "Celestial Alignment. Stars aligned.",
        "Cosmic power maximized.",
        "Alignment complete.",
        "Celestial fury engaged.",
        "Balance perfected.",
      },
    },
    {
      id = "druid_fury_of_elune",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 102, spellName = "Fury of Elune" },
      messages = {
        "Fury of Elune. Moon fury.",
        "Elune's wrath deployed.",
        "Lunar fury engaged.",
        "Moon goddess online.",
        "Fury activated.",
      },
    },

    -- ====================================================================
    -- FERAL DRUID SPEC-SPECIFIC TRIGGERS (SpecID: 103)
    -- ====================================================================
    {
      id = "druid_rake",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 103, spellName = "Rake" },
      messages = {
        "Rake. Clawing engaged.",
        "Raking with claws.",
        "Cat scratch deployed.",
        "Rake online.",
        "Feral bleed applied.",
      },
    },
    {
      id = "druid_rip",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 103, spellName = "Rip" },
      messages = {
        "Rip. Tearing flesh.",
        "Rip deployed.",
        "Cat finisher engaged.",
        "Bleed maximized.",
        "Ripping attack online.",
      },
    },
    {
      id = "druid_ferocious_bite",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 103, spellName = "Ferocious Bite" },
      messages = {
        "Ferocious Bite. Cat chomp.",
        "Biting ferociously.",
        "Feral finisher deployed.",
        "Bite engaged.",
        "Ferocious attack online.",
      },
    },
    {
      id = "druid_tigers_fury",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "cooldowns",
      conditions = { specID = 103, spellName = "Tiger's Fury" },
      messages = {
        "Tiger's Fury. Cat rage.",
        "Fury engaged.",
        "Tiger power online.",
        "Feral fury activated.",
        "Rage mode: cat.",
      },
    },
    {
      id = "druid_feral_frenzy",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 103, spellName = "Feral Frenzy" },
      messages = {
        "Feral Frenzy. Multi-strike.",
        "Frenzy deployed.",
        "Rapid cat attacks.",
        "Frenzy online.",
        "Feral barrage engaged.",
      },
    },

    -- ====================================================================
    -- GUARDIAN DRUID SPEC-SPECIFIC TRIGGERS (SpecID: 104)
    -- ====================================================================
    {
      id = "druid_mangle",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 104, spellName = "Mangle" },
      messages = {
        "Mangle. Bear attack.",
        "Mangling deployed.",
        "Bear strike online.",
        "Mangle engaged.",
        "Guardian attack activated.",
      },
    },
    {
      id = "druid_thrash_bear",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 104, spellName = "Thrash" },
      messages = {
        "Thrash. Bear AoE.",
        "Thrashing deployed.",
        "Bear spin online.",
        "Thrash engaged.",
        "AoE bear attack.",
      },
    },
    {
      id = "druid_maul",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 104, spellName = "Maul" },
      messages = {
        "Maul. Heavy bear strike.",
        "Mauling deployed.",
        "Bear smash online.",
        "Maul engaged.",
        "Heavy attack activated.",
      },
    },
    {
      id = "druid_incarnation_bear",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 104, spellName = "Incarnation: Guardian of Ursoc" },
      messages = {
        "Incarnation. Ultimate bear.",
        "Ursoc form engaged.",
        "Bear god mode.",
        "Guardian incarnation online.",
        "Ultimate tank form.",
      },
    },

    -- ====================================================================
    -- RESTORATION DRUID SPEC-SPECIFIC TRIGGERS (SpecID: 105)
    -- ====================================================================
    {
      id = "druid_regrowth",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 105, spellName = "Regrowth" },
      messages = {
        "Regrowth. Direct heal.",
        "Regrowth deployed.",
        "Nature heal online.",
        "Healing engaged.",
        "Regrowth activated.",
      },
    },
    {
      id = "druid_wild_growth",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 105, spellName = "Wild Growth" },
      messages = {
        "Wild Growth. AoE HoTs.",
        "Wild growth deployed.",
        "Group heal online.",
        "HoT spread engaged.",
        "Wild healing activated.",
      },
    },
    {
      id = "druid_swiftmend",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 105, spellName = "Swiftmend" },
      messages = {
        "Swiftmend. Quick heal.",
        "Swiftmend deployed.",
        "Fast heal online.",
        "Emergency heal engaged.",
        "Swift healing activated.",
      },
    },
    {
      id = "druid_tranquility",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 105, spellName = "Tranquility" },
      messages = {
        "Tranquility. Mass heal.",
        "Tranquility deployed.",
        "Group healing engaged.",
        "Channeling peace.",
        "Tranquil restoration online.",
      },
    },
    {
      id = "druid_flourish",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 105, spellName = "Flourish" },
      messages = {
        "Flourish. HoT extension.",
        "Flourish deployed.",
        "HoTs extended.",
        "Healing prolonged.",
        "Flourish online.",
      },
    },
  },
})
