-- SpeakinLite - Shaman Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "shaman",
  name = "Shaman Pack",
  defaults = { class = "SHAMAN", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "shaman_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "calls upon the elements to fight.",
        "channels primal forces, ready to strike.",
        "communes with the spirits, battle begins.",
        "summons the fury of nature.",
        "enters combat, elements at their command.",
      },
    },
    {
      id = "shaman_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "thanks the spirits for their aid.",
        "releases the elements, balance restored.",
        "stands peacefully, nature satisfied.",
        "nods to the spirits, harmony returns.",
        "relaxes, the elements calm once more.",
      },
    },

    -- Totems
    {
      id = "healing_stream_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Healing Stream Totem" },
      messages = {
        "Healing Stream Totem. Water heals all.",
        "Totem deployed. HP restoration engaged.",
        "Placing a healing stick.",
        "If HP is low, the stream provides.",
        "Water totem online.",
        "Healing currents activated.",
        "Totem planted. Stay near it.",
        "Stream of life deployed.",
      },
    },
    {
      id = "earthbind_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Earthbind Totem" },
      messages = {
        "Earthbind Totem. Slowing field active.",
        "Earth totem deployed. Movement restricted.",
        "Totem of slow placed.",
        "If Midnight wants to run, the earth disagrees.",
        "Earthbind online. Move slowly.",
        "The ground has opinions about speed.",
        "Slow totem activated.",
        "Earth binds all.",
      },
    },
    {
      id = "capacitor_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Capacitor Totem" },
      messages = {
        "Capacitor Totem. Delayed stun incoming.",
        "Electric totem deployed. Wait for it.",
        "Capacitor placed. Stun pending.",
        "If Midnight stands near this, regrets follow.",
        "Lightning stun totem online.",
        "Charging capacitor deployed.",
        "Electric field totem activated.",
        "Shock stick placed.",
      },
    },

    -- Defensive
    {
      id = "astral_shift",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Astral Shift" },
      messages = {
        "Astral Shift. Damage reduction engaged.",
        "Shifting into the astral plane. Briefly.",
        "Ethereal defense online.",
        "If Midnight hits me, less effective.",
        "Astral protection activated.",
        "Shifted. Damage mitigated.",
        "Phase defense online.",
        "Astral shield deployed.",
      },
    },
    {
      id = "earth_elemental",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Earth Elemental" },
      messages = {
        "Earth Elemental. Rock friend summoned.",
        "Big stone bodyguard deployed.",
        "Elemental tank online.",
        "If Midnight wants me, it gets a rock first.",
        "Earth guardian activated.",
        "Stone protector summoned.",
        "Elemental defense engaged.",
        "Rock elemental deployed.",
      },
    },

    -- Offensive CDs
    {
      id = "bloodlust",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 180,
      category = "cooldowns",
      conditions = { spellName = "Bloodlust" },
      messages = {
        "Bloodlust. Everyone goes fast now.",
        "Lust deployed. Time to burn.",
        "Speed mode: maximum.",
        "If Midnight wanted slow, too bad.",
        "Bloodlust online. Panic faster.",
        "Haste for all. Courtesy of the elements.",
        "Lust engaged. Execute phase activated.",
        "Maximum speed granted.",
      },
    },
    {
      id = "heroism",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 180,
      category = "cooldowns",
      conditions = { spellName = "Heroism" },
      messages = {
        "Heroism. Everyone acts heroic now.",
        "Hero time engaged.",
        "Speed buff deployed.",
        "If Midnight wanted patience, denied.",
        "Heroism online. Let's go.",
        "Haste granted. Burn phase active.",
        "Heroic mode activated.",
        "Maximum haste for all.",
      },
    },
    {
      id = "ascendance",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Ascendance" },
      messages = {
        "Ascendance. Elemental form activated.",
        "Ascending beyond mortal limits.",
        "Elemental power unleashed.",
        "If Midnight wanted mortal, incorrect.",
        "Ascended mode: on.",
        "Elemental transformation complete.",
        "Power spike via ascension.",
        "Transcended. Temporarily.",
      },
    },
    {
      id = "stormkeeper",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Stormkeeper" },
      messages = {
        "Stormkeeper. Storm mode activated.",
        "Lightning on demand.",
        "Keeper of storms engaged.",
        "If Midnight wanted calm weather, denied.",
        "Storm protocol online.",
        "Lightning keeper deployed.",
        "Tempest control activated.",
        "Storm power unleashed.",
      },
    },

    -- Utility
    {
      id = "wind_shear",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "utility",
      conditions = { spellName = "Wind Shear" },
      messages = {
        "Wind Shear. Cast interrupted.",
        "Spell sheared by wind.",
        "Silenced via air elemental.",
        "If Midnight wanted to cast, denied.",
        "Wind interrupt deployed.",
        "Cast cancelled by breeze.",
        "Spell sheared. Interrupt successful.",
        "Wind says no.",
      },
    },
    {
      id = "hex",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Hex" },
      messages = {
        "Hex. Frog transformation applied.",
        "You are a frog now. Enjoy.",
        "Hexed into amphibian form.",
        "If Midnight wanted agency, it is a frog.",
        "Frog mode activated.",
        "Transformation hex deployed.",
        "Ribbit protocol engaged.",
        "You have been frogged.",
      },
    },

    -- Ghost Wolf
    {
      id = "ghost_wolf",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "movement",
      conditions = { spellName = "Ghost Wolf" },
      messages = {
        "Ghost Wolf. Wolf mode engaged.",
        "Transforming into spirit wolf.",
        "Fast travel via ghost dog.",
        "If Midnight chases me, good luck.",
        "Wolf form activated.",
        "Spirit wolf online.",
        "Running with the pack. Population: me.",
        "Ghost wolf deployed.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. The elements adapt.",
        "<spec> mode. Recalibrating elemental strategy.",
        "Switched to <spec>. Nature provides options.",
        "<spec> selected. Elemental balance adjusted.",
        "New spec, same shaman: <spec>.",
      },
    },

    -- ====================================================================
    -- ELEMENTAL SHAMAN SPEC-SPECIFIC TRIGGERS (SpecID: 262)
    -- ====================================================================
    {
      id = "shaman_lightning_bolt",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 262, spellName = "Lightning Bolt" },
      messages = {
        "Lightning Bolt. Electric damage.",
        "Bolt deployed.",
        "Lightning strike online.",
        "Electric attack engaged.",
        "Thunder bolt activated.",
      },
    },
    {
      id = "shaman_lava_burst",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 262, spellName = "Lava Burst" },
      messages = {
        "Lava Burst. Molten damage.",
        "Lava deployed.",
        "Volcanic burst online.",
        "Molten attack engaged.",
        "Lava strike activated.",
      },
    },
    {
      id = "shaman_earthquake",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 262, spellName = "Earthquake" },
      messages = {
        "Earthquake. Ground shake.",
        "Earthquake deployed.",
        "Earth fury online.",
        "Seismic attack engaged.",
        "Ground tremor activated.",
      },
    },
    {
      id = "shaman_elemental_blast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 262, spellName = "Elemental Blast" },
      messages = {
        "Elemental Blast. All elements.",
        "Blast deployed.",
        "Elemental fury online.",
        "Multi-element attack.",
        "Blast activated.",
      },
    },
    {
      id = "shaman_fire_elemental",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 262, spellName = "Fire Elemental" },
      messages = {
        "Fire Elemental. Flame guardian.",
        "Fire elemental deployed.",
        "Flame ally online.",
        "Elemental fire engaged.",
        "Fire guardian activated.",
      },
    },
    {
      id = "shaman_liquid_magma_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 262, spellName = "Liquid Magma Totem" },
      messages = {
        "Liquid Magma Totem. Lava totem.",
        "Magma totem deployed.",
        "Molten totem online.",
        "Lava stick engaged.",
        "Magma activated.",
      },
    },

    -- ====================================================================
    -- ENHANCEMENT SHAMAN SPEC-SPECIFIC TRIGGERS (SpecID: 263)
    -- ====================================================================
    {
      id = "shaman_stormstrike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 263, spellName = "Stormstrike" },
      messages = {
        "Stormstrike. Dual strike.",
        "Storm strike deployed.",
        "Melee fury online.",
        "Dual wield engaged.",
        "Storm attack activated.",
      },
    },
    {
      id = "shaman_lava_lash",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 263, spellName = "Lava Lash" },
      messages = {
        "Lava Lash. Fire strike.",
        "Lava lash deployed.",
        "Molten melee online.",
        "Fire strike engaged.",
        "Lava attack activated.",
      },
    },
    {
      id = "shaman_crash_lightning",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 263, spellName = "Crash Lightning" },
      messages = {
        "Crash Lightning. AoE melee.",
        "Lightning crash deployed.",
        "Electric melee online.",
        "AoE storm engaged.",
        "Crash activated.",
      },
    },
    {
      id = "shaman_feral_spirit",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 263, spellName = "Feral Spirit" },
      messages = {
        "Feral Spirit. Wolf guardians.",
        "Spirit wolves deployed.",
        "Feral allies online.",
        "Wolf spirits engaged.",
        "Guardians activated.",
      },
    },
    {
      id = "shaman_doom_winds",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 263, spellName = "Doom Winds" },
      messages = {
        "Doom Winds. Wind fury.",
        "Doom deployed.",
        "Windfury maximized.",
        "Doom winds engaged.",
        "Fury activated.",
      },
    },

    -- ====================================================================
    -- RESTORATION SHAMAN SPEC-SPECIFIC TRIGGERS (SpecID: 264)
    -- ====================================================================
    {
      id = "shaman_healing_wave",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 264, spellName = "Healing Wave" },
      messages = {
        "Healing Wave. Water heal.",
        "Wave deployed.",
        "Water healing online.",
        "Healing wave engaged.",
        "Restoration activated.",
      },
    },
    {
      id = "shaman_chain_heal",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 264, spellName = "Chain Heal" },
      messages = {
        "Chain Heal. Bouncing heal.",
        "Chain deployed.",
        "Healing chain online.",
        "Bounce heal engaged.",
        "Chain restoration activated.",
      },
    },
    {
      id = "shaman_riptide",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "utility",
      conditions = { specID = 264, spellName = "Riptide" },
      messages = {
        "Riptide. HoT deployed.",
        "Riptide online.",
        "Healing over time engaged.",
        "Water HoT activated.",
        "Tide healing deployed.",
      },
    },
    {
      id = "shaman_healing_rain",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 264, spellName = "Healing Rain" },
      messages = {
        "Healing Rain. AoE heal.",
        "Rain deployed.",
        "Healing rain online.",
        "Group heal engaged.",
        "Water rain activated.",
      },
    },
    {
      id = "shaman_spirit_link_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 264, spellName = "Spirit Link Totem" },
      messages = {
        "Spirit Link Totem. Sharing damage.",
        "Link totem deployed.",
        "Damage sharing online.",
        "Spirit link engaged.",
        "Link activated.",
      },
    },
    {
      id = "shaman_cloudburst_totem",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 264, spellName = "Cloudburst Totem" },
      messages = {
        "Cloudburst Totem. Healing storage.",
        "Cloudburst deployed.",
        "Heal bank online.",
        "Storage totem engaged.",
        "Cloudburst activated.",
      },
    },
  },
})
