-- SpeakinLite - Rogue Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "rogue",
  name = "Rogue Pack",
  defaults = { class = "ROGUE", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "rogue_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "emerges from the shadows, daggers ready.",
        "strikes from stealth, precision deadly.",
        "appears behind the enemy.",
        "attacks with cunning efficiency.",
        "enters combat, silent and lethal.",
      },
    },
    {
      id = "rogue_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "vanishes back into the shadows.",
        "cleans their blades, job complete.",
        "disappears, leaving no trace.",
        "smirks, another contract fulfilled.",
        "fades away, silent as arrival.",
      },
    },

    -- Stealth
    {
      id = "stealth",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Stealth" },
      messages = {
        "Stealth. I am not here.",
        "Vanishing into the shadows.",
        "Gone. Like my moral compass.",
        "If Midnight looks for me, good luck.",
        "Stealth mode: maximum.",
        "I have become a rumor.",
        "The shadows welcome me back.",
        "Not here. Never was.",
      },
    },
    {
      id = "vanish",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Vanish" },
      messages = {
        "Vanish. Threat reset via disappearing.",
        "Gone in an instant.",
        "Aggro dropped. I am a myth now.",
        "If Midnight wanted me, too late.",
        "Emergency vanish deployed.",
        "I have left the encounter. Emotionally and physically.",
        "Threat cancelled. I do not exist.",
        "Disappeared. Please do not look for me.",
      },
    },

    -- Defensive
    {
      id = "cloak_of_shadows",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Cloak of Shadows" },
      messages = {
        "Cloak of Shadows. Magic immunity engaged.",
        "Shadow cloak online. Spells declined.",
        "Magic? Not on me.",
        "The shadows protect from sorcery.",
        "If Midnight casts, I shrug.",
        "Spell immunity via darkness.",
        "Magic resistance: maximum.",
        "Shadow shield activated.",
      },
    },
    {
      id = "evasion",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Evasion" },
      messages = {
        "Evasion. Dodge mode engaged.",
        "Miss me. All of you.",
        "Attack avoidance: 100%.",
        "If Midnight swings, I am not there.",
        "Evasion protocol online.",
        "Too fast to hit.",
        "Dodging everything with style.",
        "You cannot hit what you cannot catch.",
      },
    },
    {
      id = "feint",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { spellName = "Feint" },
      messages = {
        "Feint. AoE damage reduced.",
        "Dodging the big scary things.",
        "Area damage? Less, please.",
        "Feinting through the fire.",
        "If Midnight uses AoE, I have opinions.",
        "Damage reduction via agility.",
        "Feint deployed. Survival improved.",
        "Avoiding collateral damage.",
      },
    },

    -- Offensive CDs
    {
      id = "adrenaline_rush",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Adrenaline Rush" },
      messages = {
        "Adrenaline Rush. Hyper speed activated.",
        "Energy regeneration: extreme.",
        "Rush mode engaged.",
        "Fast and efficient. Like crime.",
        "If Midnight blinks, it misses me.",
        "Adrenaline online. Let's go.",
        "Energy surge deployed.",
        "Rushing through the encounter.",
      },
    },
    {
      id = "shadow_blades",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Shadow Blades" },
      messages = {
        "Shadow Blades. Shadow-infused violence.",
        "Blades upgraded via darkness.",
        "Shadow damage online.",
        "If Midnight wanted light, wrong class.",
        "Darkness empowers my weapons.",
        "Shadow infusion complete.",
        "Blades of night deployed.",
        "Shadow power activated.",
      },
    },
    {
      id = "shadow_dance",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { spellName = "Shadow Dance" },
      messages = {
        "Shadow Dance. Dancing with death.",
        "Stealth abilities while visible. A paradox.",
        "The dance begins.",
        "If Midnight wanted predictable, too bad.",
        "Shadow dance mode: on.",
        "Dancing through the encounter.",
        "Stealth powers without the stealth.",
        "Paradoxical violence engaged.",
      },
    },

    -- Utility
    {
      id = "kick",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "utility",
      conditions = { spellName = "Kick" },
      messages = {
        "Kick. Cast interrupted.",
        "Your spell has been kicked.",
        "Silenced via boot.",
        "If Midnight wanted to cast, denied.",
        "Kick deployed. Spell cancelled.",
        "Interrupting with prejudice.",
        "Cast? Not anymore.",
        "Kicked into silence.",
      },
    },
    {
      id = "blind",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Blind" },
      messages = {
        "Blind. Can't see, can't fight.",
        "Pocket sand deployed.",
        "Blinded temporarily.",
        "If Midnight wanted vision, too bad.",
        "Sight removal successful.",
        "Blind crowd control engaged.",
        "The world goes dark. For them.",
        "Vision cancelled.",
      },
    },
    {
      id = "tricks_of_the_trade",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Tricks of the Trade" },
      messages = {
        "Tricks of the Trade. Threat redirected.",
        "My aggro is now your problem.",
        "Tricks deployed. Good luck.",
        "If Midnight hates me, it can hate you instead.",
        "Threat donation complete.",
        "Redirecting consequences.",
        "Tricks given. Threat transferred.",
        "Aggro: not my problem anymore.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Adjusting stealth tactics.",
        "<spec> mode. The shadows adapt.",
        "Switched to <spec>. Still sneaky.",
        "<spec> selected. Recalibrating daggers.",
        "New spec, same rogue: <spec>.",
      },
    },

    -- ====================================================================
    -- ASSASSINATION ROGUE SPEC-SPECIFIC TRIGGERS (SpecID: 259)
    -- ====================================================================
    {
      id = "rogue_envenom",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 259, spellName = "Envenom" },
      messages = {
        "Envenom. Poison finisher deployed.",
        "Venom delivered. Lethally.",
        "Poison peak achieved.",
        "Envenom online. Death is chemical.",
        "Toxic finale engaged.",
      },
    },
    {
      id = "rogue_garrote",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 259, spellName = "Garrote" },
      messages = {
        "Garrote. Silenced via strangulation.",
        "Garrote deployed. Breathing optional.",
        "Throat strike engaged.",
        "Silencing with extreme prejudice.",
        "Garrote online. Speak later.",
      },
    },
    {
      id = "rogue_rupture",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 259, spellName = "Rupture" },
      messages = {
        "Rupture. Bleed damage over time.",
        "Rupturing vital points.",
        "Bleed deployed. Slow death.",
        "Rupture online. HP drains.",
        "Critical strike, slow consequence.",
      },
    },
    {
      id = "rogue_kingsbane",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 259, spellName = "Kingsbane" },
      messages = {
        "Kingsbane. Poison amplified.",
        "Kingsbane deployed. Royalty slays.",
        "The king's poison engaged.",
        "Amplified toxins online.",
        "If Midnight wanted clean death, wrong rogue.",
      },
    },

    -- ====================================================================
    -- OUTLAW ROGUE SPEC-SPECIFIC TRIGGERS (SpecID: 260)
    -- ====================================================================
    {
      id = "rogue_dispatch",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 260, spellName = "Dispatch" },
      messages = {
        "Dispatch. Finisher with style.",
        "Dispatching with efficiency.",
        "Final blow delivered.",
        "Dispatch online. Problem solved.",
        "Quick and final.",
      },
    },
    {
      id = "rogue_between_the_eyes",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 260, spellName = "Between the Eyes" },
      messages = {
        "Between the Eyes. Precision shot.",
        "Headshot deployed.",
        "Right between the eyes.",
        "Critical precision engaged.",
        "If Midnight has eyes, I found them.",
      },
    },
    {
      id = "rogue_blade_flurry",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 260, spellName = "Blade Flurry" },
      messages = {
        "Blade Flurry. AoE piracy online.",
        "Flurry engaged. Everyone gets hit.",
        "Blades everywhere.",
        "Cleave mode activated.",
        "If Midnight brought adds, they all get cut.",
      },
    },
    {
      id = "rogue_killing_spree",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 260, spellName = "Killing Spree" },
      messages = {
        "Killing Spree. Pirate rage mode.",
        "Spree engaged. Watch out.",
        "Teleporting violence.",
        "Killing spree online. Chaos deployed.",
        "If Midnight wanted order, wrong class.",
      },
    },
    {
      id = "rogue_roll_the_bones",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { specID = 260, spellName = "Roll the Bones" },
      messages = {
        "Roll the Bones. Gambling for buffs.",
        "Rolling. Let's see what we get.",
        "Bones rolled. RNG engaged.",
        "Buff lottery activated.",
        "If Midnight wanted consistency, wrong spec.",
      },
    },

    -- ====================================================================
    -- SUBTLETY ROGUE SPEC-SPECIFIC TRIGGERS (SpecID: 261)
    -- ====================================================================
    {
      id = "rogue_eviscerate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 261, spellName = "Eviscerate" },
      messages = {
        "Eviscerate. Finisher from shadows.",
        "Eviscerating with precision.",
        "Shadow strike finalized.",
        "Eviscerate online. Death delivered.",
        "Critical finale engaged.",
      },
    },
    {
      id = "rogue_backstab",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 261, spellName = "Backstab" },
      messages = {
        "Backstab. Classic betrayal.",
        "Striking from behind.",
        "Backstab deployed. Trust no one.",
        "The classic rogue move.",
        "Behind you. Always.",
      },
    },
    {
      id = "rogue_nightblade",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 261, spellName = "Nightblade" },
      messages = {
        "Nightblade. Shadow bleed engaged.",
        "Blade of night deployed.",
        "Shadow damage over time.",
        "Nightblade online. Darkness drains.",
        "Bleeding into shadow.",
      },
    },
    {
      id = "rogue_symbols_of_death",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 261, spellName = "Symbols of Death" },
      messages = {
        "Symbols of Death. Shadow power surge.",
        "Death symbols activated.",
        "Empowered by darkness.",
        "Symbols online. Damage increased.",
        "The shadows empower me.",
      },
    },
    {
      id = "rogue_shuriken_storm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 261, spellName = "Shuriken Storm" },
      messages = {
        "Shuriken Storm. AoE via throwing stars.",
        "Storm of blades deployed.",
        "Shurikens everywhere.",
        "Shadow storm engaged.",
        "If Midnight brought adds, they all get stars.",
      },
    },
  },
})
