-- SpeakinLite - Demon Hunter Pack

if not SpeakinLite or type(SpeakinLite.RegisterPack) ~= "function" then
  return
end

SpeakinLite:RegisterPack({
  id = "demonhunter",
  name = "Demon Hunter Pack",
  defaults = { class = "DEMONHUNTER", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "dh_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "unleashes fel fury, glaives spinning.",
        "enters combat, prepared for chaos.",
        "channels demonic power, ready to hunt.",
        "assumes combat stance, blindfold no hindrance.",
        "prepares to sacrifice everything.",
      },
    },
    {
      id = "dh_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "sheathes their glaives, demon slain.",
        "stands victorious, fel energy subsiding.",
        "nods grimly, another foe vanquished.",
        "relaxes their stance, hunt complete.",
        "smirks, chaos contained.",
      },
    },

    -- Mobility
    {
      id = "fel_rush",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "movement",
      conditions = { spellName = "Fel Rush" },
      messages = {
        "Fel Rush. Green speed engaged.",
        "Rushing with fel energy.",
        "If Midnight wanted me there, too late.",
        "Fel-powered dash deployed.",
        "Rush mode: demonic.",
        "Green blur activated.",
        "Fel speed online.",
        "Rushing with chaos.",
      },
    },
    {
      id = "vengeful_retreat",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "movement",
      conditions = { spellName = "Vengeful Retreat" },
      messages = {
        "Vengeful Retreat. Backflip deployed.",
        "Flipping away. Stylishly.",
        "If Midnight wanted me close, denied.",
        "Revenge backflip engaged.",
        "Retreating with flair.",
        "Vengeful escape activated.",
        "Backflip protocol online.",
        "Flipping out. Literally.",
      },
    },

    -- Defensive
    {
      id = "blur",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Blur" },
      messages = {
        "Blur. Dodge mode maximum.",
        "Blurred into evasion.",
        "If Midnight hits me, unlikely.",
        "Blur protocol engaged.",
        "Dodge chance: extreme.",
        "Blurred defense online.",
        "Evasion via blurriness.",
        "Blur shield activated.",
      },
    },
    {
      id = "darkness",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Darkness" },
      messages = {
        "Darkness. Dodge field deployed.",
        "Shadow zone activated.",
        "If Midnight attacks, we dodge.",
        "Darkness protocol engaged.",
        "Evasion field online.",
        "Shadow dodge zone active.",
        "Darkness deployed.",
        "Dodge area established.",
      },
    },
    {
      id = "netherwalk",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Netherwalk" },
      messages = {
        "Netherwalk. Phase shifting engaged.",
        "Walking through the nether.",
        "If Midnight wanted to hit me, phased out.",
        "Nether phase online.",
        "Immunity via shadow realm.",
        "Netherwalk activated.",
        "Phase shift complete.",
        "Walking between worlds.",
      },
    },

    -- Offensive CDs
    {
      id = "metamorphosis",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Metamorphosis" },
      messages = {
        "Metamorphosis. Demon form activated.",
        "Transforming into my true self.",
        "If Midnight wanted elf, it gets demon.",
        "Demon mode engaged.",
        "Metamorphosis complete.",
        "True form unlocked.",
        "Demon transformation online.",
        "Ultimate form activated.",
      },
    },
    {
      id = "eye_beam",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 25,
      category = "cooldowns",
      conditions = { spellName = "Eye Beam" },
      messages = {
        "Eye Beam. Laser eyes deployed.",
        "Fel beams engaged.",
        "If Midnight stands in line, regrets follow.",
        "Eye lasers online.",
        "Beam protocol activated.",
        "Fel optics engaged.",
        "Laser vision deployed.",
        "Eye beam complete.",
      },
    },
    {
      id = "the_hunt",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 90,
      category = "cooldowns",
      conditions = { spellName = "The Hunt" },
      messages = {
        "The Hunt. Pursuing with prejudice.",
        "Hunt mode activated.",
        "If Midnight runs, I chase.",
        "Pursuit protocol engaged.",
        "The hunt begins.",
        "Chasing with fel fury.",
        "Hunt deployed.",
        "Pursuit online.",
      },
    },

    -- Utility
    {
      id = "consume_magic",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Consume Magic" },
      messages = {
        "Consume Magic. Eating buffs.",
        "Magic consumed.",
        "If Midnight had buffs, not anymore.",
        "Consumption protocol engaged.",
        "Magic devoured.",
        "Buff removal via consumption.",
        "Consuming magical energy.",
        "Magic eaten.",
      },
    },
    {
      id = "chaos_nova",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Chaos Nova" },
      messages = {
        "Chaos Nova. AoE stun deployed.",
        "Chaotic stun engaged.",
        "If Midnight stands close, stunned.",
        "Nova protocol activated.",
        "Chaos burst online.",
        "AoE stun via chaos.",
        "Nova deployed.",
        "Chaos stun complete.",
      },
    },
    {
      id = "sigil_of_flame",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Sigil of Flame" },
      messages = {
        "Sigil of Flame. Fel fire deployed.",
        "Flame sigil placed.",
        "If Midnight steps here, burns follow.",
        "Sigil protocol engaged.",
        "Fel flame online.",
        "Fire sigil activated.",
        "Flame zone deployed.",
        "Sigil complete.",
      },
    },
    {
      id = "immolation_aura",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { spellName = "Immolation Aura" },
      messages = {
        "Immolation Aura. I am now on fire.",
        "Burning aura engaged.",
        "If Midnight gets close, it burns.",
        "Immolation online.",
        "Fire aura activated.",
        "Burning protocol engaged.",
        "Aura of flames deployed.",
        "Immolation complete.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Fel tactics adjusted.",
        "<spec> mode. The Illidari adapt.",
        "Switched to <spec>. Demon within recalibrated.",
        "<spec> selected. Chaos strategy changed.",
        "New spec, same demon hunter: <spec>.",
      },
    },

    -- ====================================================================
    -- HAVOC DEMON HUNTER SPEC-SPECIFIC TRIGGERS (SpecID: 577)
    -- ====================================================================
    {
      id = "dh_chaos_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 577, spellName = "Chaos Strike" },
      messages = {
        "Chaos Strike. Chaotic damage.",
        "Chaos deployed.",
        "Strike online.",
        "Chaos engaged.",
        "Havoc attack activated.",
      },
    },
    {
      id = "dh_blade_dance",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 577, spellName = "Blade Dance" },
      messages = {
        "Blade Dance. Spinning blades.",
        "Dance deployed.",
        "Blade spin online.",
        "AoE dance engaged.",
        "Blade dance activated.",
      },
    },
    {
      id = "dh_death_sweep",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 577, spellName = "Death Sweep" },
      messages = {
        "Death Sweep. Meta blade dance.",
        "Sweep deployed.",
        "Death spin online.",
        "Meta dance engaged.",
        "Death sweep activated.",
      },
    },
    {
      id = "dh_glaive_tempest",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 577, spellName = "Glaive Tempest" },
      messages = {
        "Glaive Tempest. Blade storm.",
        "Tempest deployed.",
        "Glaive storm online.",
        "Blade tempest engaged.",
        "Storm activated.",
      },
    },
    {
      id = "dh_essence_break",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 577, spellName = "Essence Break" },
      messages = {
        "Essence Break. Damage amplified.",
        "Essence deployed.",
        "Break online.",
        "Amplification engaged.",
        "Essence activated.",
      },
    },

    -- ====================================================================
    -- VENGEANCE DEMON HUNTER SPEC-SPECIFIC TRIGGERS (SpecID: 581)
    -- ====================================================================
    {
      id = "dh_soul_cleave",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { specID = 581, spellName = "Soul Cleave" },
      messages = {
        "Soul Cleave. Tank attack.",
        "Soul cleave deployed.",
        "Cleave online.",
        "Soul strike engaged.",
        "Cleave activated.",
      },
    },
    {
      id = "dh_spirit_bomb",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 581, spellName = "Spirit Bomb" },
      messages = {
        "Spirit Bomb. Soul explosion.",
        "Spirit bomb deployed.",
        "Soul bomb online.",
        "Bomb engaged.",
        "Spirit explosion activated.",
      },
    },
    {
      id = "dh_fiery_brand",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { specID = 581, spellName = "Fiery Brand" },
      messages = {
        "Fiery Brand. Damage reduction.",
        "Brand deployed.",
        "Fiery debuff online.",
        "Brand engaged.",
        "Fire brand activated.",
      },
    },
    {
      id = "dh_demon_spikes",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { specID = 581, spellName = "Demon Spikes" },
      messages = {
        "Demon Spikes. Armor increased.",
        "Spikes deployed.",
        "Demon armor online.",
        "Spikes engaged.",
        "Armor activated.",
      },
    },
    {
      id = "dh_fel_devastation",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { specID = 581, spellName = "Fel Devastation" },
      messages = {
        "Fel Devastation. Fel beam.",
        "Devastation deployed.",
        "Fel channel online.",
        "Beam engaged.",
        "Devastation activated.",
      },
    },
  },
})
