-- EmoteControl - Priest Pack

if not EmoteControl or type(EmoteControl.RegisterPack) ~= "function" then
  return
end

EmoteControl:RegisterPack({
  id = "priest",
  name = "Priest Pack",
  defaults = { class = "PRIEST", unit = "player" },
  triggers = {
    -- Emote flavor triggers
    {
      id = "priest_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "channels the Light and Shadow in equal measure.",
        "prepares to heal and harm as needed.",
        "enters battle, faith unwavering.",
        "readies their magic, balanced and focused.",
        "stands ready, Light and Void at hand.",
      },
    },
    {
      id = "priest_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "relaxes, balance maintained.",
        "offers a quiet prayer.",
        "stands peacefully, crisis averted.",
        "exhales, returning to calm.",
        "nods, faith confirmed once more.",
      },
    },

    -- Healing
    {
      id = "power_word_shield",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "defensive",
      conditions = { spellName = "Power Word: Shield" },
      messages = {
        "Power Word: Shield. Bubble deployed.",
        "Absorb shield active.",
        "Protection via words of power.",
        "If damage comes, the shield says no.",
        "Shielded with holy confidence.",
        "Barrier erected. Damage absorbed.",
        "Power word protecting the faithful.",
        "Shield engaged. Stay safe.",
      },
    },
    {
      id = "flash_heal",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { spellName = "Flash Heal" },
      messages = {
        "Flash Heal. Emergency HP delivered.",
        "Quick heal deployed.",
        "Fast healing via holy light.",
        "If HP was low, it is less low now.",
        "Flash mode activated.",
        "Instant healing online.",
        "HP restored with urgency.",
        "Fast heal complete.",
      },
    },

    -- Defensive
    {
      id = "desperate_prayer",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { spellName = "Desperate Prayer" },
      messages = {
        "Desperate Prayer. Self-heal deployed.",
        "Praying for HP. It worked.",
        "Desperate times, desperate prayers.",
        "If I was low, I am less low now.",
        "Emergency prayer answered.",
        "Self-preservation via faith.",
        "Desperate healing online.",
        "Prayer accepted. HP granted.",
      },
    },
    {
      id = "fade",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "defensive",
      conditions = { spellName = "Fade" },
      messages = {
        "Fade. Threat reduced.",
        "Becoming less interesting to enemies.",
        "Fading into the background.",
        "If Midnight wanted me, it can reconsider.",
        "Aggro management via disappearing.",
        "Threat dropped. I am unimportant now.",
        "Fade online. Please ignore me.",
        "Becoming forgettable.",
      },
    },
    {
      id = "dispersion",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Dispersion" },
      messages = {
        "Dispersion. Shadow form intensified.",
        "Dispersing into shadow.",
        "Damage reduction: maximum.",
        "I have become less corporeal.",
        "If Midnight hits me now, good luck.",
        "Shadow protection online.",
        "Dispersed. Mostly invulnerable.",
        "Shadow immunity engaged.",
      },
    },
    {
      id = "guardian_spirit",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "defensive",
      conditions = { spellName = "Guardian Spirit" },
      messages = {
        "Guardian Spirit. Divine protection deployed.",
        "Angel on duty.",
        "If death comes, the spirit disagrees.",
        "Guardian assigned. Death prevention mode.",
        "Divine watchdog activated.",
        "Protective spirit online.",
        "Guardian angel deployed.",
        "Spirit protection granted.",
      },
    },

    -- Offensive CDs
    {
      id = "power_infusion",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Power Infusion" },
      messages = {
        "Power Infusion. Haste injected.",
        "Speed boost granted.",
        "If Midnight wanted slow, incorrect.",
        "Power infused. Cast faster.",
        "Haste buff deployed.",
        "Infusion complete. Speed increased.",
        "Power surge activated.",
        "Casting speed amplified.",
      },
    },
    {
      id = "shadow_fiend",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { spellName = "Shadowfiend" },
      messages = {
        "Shadowfiend. Summoning dark backup.",
        "Shadow creature deployed.",
        "Fiend online. Damage incoming.",
        "If Midnight wanted Light, wrong class.",
        "Dark minion summoned.",
        "Shadow assistant activated.",
        "Fiend of shadow released.",
        "Dark ally deployed.",
      },
    },
    {
      id = "void_eruption",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { spellName = "Void Eruption" },
      messages = {
        "Void Eruption. The darkness explodes.",
        "Void form activated.",
        "Embracing the Void. Aggressively.",
        "If Midnight is Void, I can Void too.",
        "Shadow mode: maximum.",
        "Void power unleashed.",
        "Eruption complete. Void engaged.",
        "The Void provides. Violently.",
      },
    },

    -- Utility
    {
      id = "mass_dispel",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "utility",
      conditions = { spellName = "Mass Dispel" },
      messages = {
        "Mass Dispel. Magic removal engaged.",
        "Dispelling everyone. You're welcome.",
        "Mass cleanse deployed.",
        "If buffs/debuffs exist, not anymore.",
        "Purging magic on a large scale.",
        "Mass purification online.",
        "Dispel protocol: area effect.",
        "Magic removed in bulk.",
      },
    },
    {
      id = "leap_of_faith",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellName = "Leap of Faith" },
      messages = {
        "Leap of Faith. Pulling you to safety.",
        "Life Grip deployed.",
        "Come here. Now.",
        "If you are in fire, not anymore.",
        "Faith-based relocation.",
        "Yanking to safety.",
        "Grip of salvation activated.",
        "Pulled via holy authority.",
      },
    },

    -- Spec change
    {
      id = "spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      messages = {
        "Spec shift detected: <spec>. Adjusting holy strategy.",
        "<spec> mode. The Light and Shadow adapt.",
        "Switched to <spec>. Faith recalibrated.",
        "<spec> selected. Divine tactics adjusted.",
        "New spec, same priest: <spec>.",
      },
    },

    -- ====================================================================
    -- DISCIPLINE PRIEST SPEC-SPECIFIC TRIGGERS (SpecID: 256)
    -- ====================================================================
    {
      id = "priest_penance",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 256, spellName = "Penance" },
      messages = {
        "Penance. Healing or harming via penance.",
        "Penance deployed. Light channeled.",
        "Penitent healing engaged.",
        "Penance online. Repentance optional.",
        "The Light absolves. Or condemns.",
      },
    },
    {
      id = "priest_power_word_radiance",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 256, spellName = "Power Word: Radiance" },
      messages = {
        "Power Word: Radiance. AoE atonement.",
        "Radiance deployed. Shields spread.",
        "Power word: group protection.",
        "Radiant shielding engaged.",
        "The Light spreads via words.",
      },
    },
    {
      id = "priest_rapture",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 256, spellName = "Rapture" },
      messages = {
        "Rapture. Free shields for everyone.",
        "Rapture engaged. Mass shielding online.",
        "Divine rapture deployed.",
        "Shields without cost. The Light provides.",
        "Rapture mode: protective frenzy.",
      },
    },
    {
      id = "priest_evangelism",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 256, spellName = "Evangelism" },
      messages = {
        "Evangelism. Atonement extended.",
        "Spreading the word. And the heals.",
        "Evangelist mode activated.",
        "Atonement prolonged via faith.",
        "The Light's message: endurance.",
      },
    },
    {
      id = "priest_pain_suppression",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "defensive",
      conditions = { specID = 256, spellName = "Pain Suppression" },
      messages = {
        "Pain Suppression. Damage reduced dramatically.",
        "Suppressing pain via holy power.",
        "Emergency mitigation deployed.",
        "Pain cancelled. The Light says no.",
        "Suppression online. Stay safe.",
      },
    },

    -- ====================================================================
    -- HOLY PRIEST SPEC-SPECIFIC TRIGGERS (SpecID: 257)
    -- ====================================================================
    {
      id = "priest_prayer_of_mending",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 257, spellName = "Prayer of Mending" },
      messages = {
        "Prayer of Mending. Healing relay established.",
        "Mending prayer deployed. Bounces between allies.",
        "Prayer online. Healing spreads.",
        "The Light hops from friend to friend.",
        "Mending activated. Group healing engaged.",
      },
    },
    {
      id = "priest_circle_of_healing",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "utility",
      conditions = { specID = 257, spellName = "Circle of Healing" },
      messages = {
        "Circle of Healing. AoE HP deployed.",
        "Healing circle engaged.",
        "Circle online. Everyone heals.",
        "The Light spreads in a circle.",
        "Group heal deployed.",
      },
    },
    {
      id = "priest_holy_word_serenity",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 257, spellName = "Holy Word: Serenity" },
      messages = {
        "Holy Word: Serenity. Calm restoration.",
        "Serenity deployed. Big heal.",
        "The Light speaks calmly. HP restored.",
        "Serene healing engaged.",
        "Holy word: peace and HP.",
      },
    },
    {
      id = "priest_holy_word_sanctify",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "utility",
      conditions = { specID = 257, spellName = "Holy Word: Sanctify" },
      messages = {
        "Holy Word: Sanctify. AoE blessing.",
        "Sanctification deployed. Ground heals.",
        "Holy territory established.",
        "The Light sanctifies this area.",
        "Sanctify online. Stand in the Light.",
      },
    },
    {
      id = "priest_divine_hymn",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 257, spellName = "Divine Hymn" },
      messages = {
        "Divine Hymn. Channeling mass healing.",
        "Hymn deployed. Everyone heals.",
        "Singing holy restoration.",
        "The Light sings. HP restores.",
        "Divine chorus online.",
      },
    },
    {
      id = "priest_apotheosis",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { specID = 257, spellName = "Apotheosis" },
      messages = {
        "Apotheosis. Ascended healing form.",
        "Divine form activated.",
        "Apotheosis engaged. Maximum holy.",
        "Ascension protocol online.",
        "The Light elevates me.",
      },
    },

    -- ====================================================================
    -- SHADOW PRIEST SPEC-SPECIFIC TRIGGERS (SpecID: 258)
    -- ====================================================================
    {
      id = "priest_mind_blast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 258, spellName = "Mind Blast" },
      messages = {
        "Mind Blast. Psychic damage deployed.",
        "Blasting minds with shadow.",
        "Mental assault engaged.",
        "Mind Blast online. Think fast.",
        "Psychic pain delivered.",
      },
    },
    {
      id = "priest_mind_flay",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 258, spellName = "Mind Flay" },
      messages = {
        "Mind Flay. Flaying thoughts.",
        "Mental erosion in progress.",
        "Flay deployed. Sanity optional.",
        "Flaying the mind slowly.",
        "Shadow erosion engaged.",
      },
    },
    {
      id = "priest_vampiric_touch",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 258, spellName = "Vampiric Touch" },
      messages = {
        "Vampiric Touch. Life drain engaged.",
        "Draining via shadow.",
        "Vampiric contact established.",
        "Your life is now mine. Slowly.",
        "Touch deployed. HP transferred.",
      },
    },
    {
      id = "priest_shadow_word_death",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { specID = 258, spellName = "Shadow Word: Death" },
      messages = {
        "Shadow Word: Death. Execute protocol.",
        "Death word deployed.",
        "The shadow speaks finality.",
        "Word of death delivered.",
        "If HP is low, it is now lower.",
      },
    },
    {
      id = "priest_dark_ascension",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { specID = 258, spellName = "Dark Ascension" },
      messages = {
        "Dark Ascension. Shadow form empowered.",
        "Ascending into darkness.",
        "Dark power maximized.",
        "Ascension: shadow edition.",
        "The Void elevates me.",
      },
    },
    {
      id = "priest_shadow_crash",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { specID = 258, spellName = "Shadow Crash" },
      messages = {
        "Shadow Crash. Void impact.",
        "Crashing shadow deployed.",
        "Void collision engaged.",
        "Shadow meteors incoming.",
        "The darkness falls hard.",
      },
    },
  },
})
